// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	capacity "gv-api/internal/capacity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// FreeBusyRange provides a mock function with given fields: ctx, from, to
func (_m *MockServiceInterface) FreeBusyRange(ctx context.Context, from time.Time, to time.Time) ([]capacity.DayFreeBusy, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FreeBusyRange")
	}

	var r0 []capacity.DayFreeBusy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]capacity.DayFreeBusy, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []capacity.DayFreeBusy); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]capacity.DayFreeBusy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_FreeBusyRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FreeBusyRange'
type MockServiceInterface_FreeBusyRange_Call struct {
	*mock.Call
}

// FreeBusyRange is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockServiceInterface_Expecter) FreeBusyRange(ctx interface{}, from interface{}, to interface{}) *MockServiceInterface_FreeBusyRange_Call {
	return &MockServiceInterface_FreeBusyRange_Call{Call: _e.mock.On("FreeBusyRange", ctx, from, to)}
}

func (_c *MockServiceInterface_FreeBusyRange_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockServiceInterface_FreeBusyRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockServiceInterface_FreeBusyRange_Call) Return(_a0 []capacity.DayFreeBusy, _a1 error) *MockServiceInterface_FreeBusyRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_FreeBusyRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]capacity.DayFreeBusy, error)) *MockServiceInterface_FreeBusyRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
