// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package habitsdb

import (
	"context"
	"time"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (name, description, frequency, target_min, target_max, recording_required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, frequency, target_min, target_max, recording_required, current_streak, longest_streak
`

type CreateHabitParams struct {
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
}

type CreateHabitRow struct {
	ID                int32    `db:"id" json:"id"`
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
	CurrentStreak     int32    `db:"current_streak" json:"current_streak"`
	LongestStreak     int32    `db:"longest_streak" json:"longest_streak"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (CreateHabitRow, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.Name,
		arg.Description,
		arg.Frequency,
		arg.TargetMin,
		arg.TargetMax,
		arg.RecordingRequired,
	)
	var i CreateHabitRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Frequency,
		&i.TargetMin,
		&i.TargetMax,
		&i.RecordingRequired,
		&i.CurrentStreak,
		&i.LongestStreak,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHabit, id)
	return err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, name, description, frequency, target_min, target_max, recording_required, current_streak, longest_streak
FROM habits WHERE id = $1
`

type GetHabitByIDRow struct {
	ID                int32    `db:"id" json:"id"`
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
	CurrentStreak     int32    `db:"current_streak" json:"current_streak"`
	LongestStreak     int32    `db:"longest_streak" json:"longest_streak"`
}

func (q *Queries) GetHabitByID(ctx context.Context, id int32) (GetHabitByIDRow, error) {
	row := q.db.QueryRow(ctx, getHabitByID, id)
	var i GetHabitByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Frequency,
		&i.TargetMin,
		&i.TargetMax,
		&i.RecordingRequired,
		&i.CurrentStreak,
		&i.LongestStreak,
	)
	return i, err
}

const getHabitHistory = `-- name: GetHabitHistory :many
SELECT
    date_trunc($1::text, hl.log_date::timestamp)::date AS date,
    SUM(hl.value)::REAL AS value
FROM habit_logs hl
WHERE hl.habit_id = $2
  AND hl.log_date >= $3::date
  AND hl.log_date <= $4::date
GROUP BY date_trunc($1::text, hl.log_date::timestamp)
ORDER BY date
`

type GetHabitHistoryParams struct {
	Frequency string    `db:"frequency" json:"frequency"`
	HabitID   int32     `db:"habit_id" json:"habit_id"`
	StartAt   time.Time `db:"start_at" json:"start_at"`
	EndAt     time.Time `db:"end_at" json:"end_at"`
}

type GetHabitHistoryRow struct {
	Date  time.Time `db:"date" json:"date"`
	Value float32   `db:"value" json:"value"`
}

func (q *Queries) GetHabitHistory(ctx context.Context, arg GetHabitHistoryParams) ([]GetHabitHistoryRow, error) {
	rows, err := q.db.Query(ctx, getHabitHistory,
		arg.Frequency,
		arg.HabitID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHabitHistoryRow{}
	for rows.Next() {
		var i GetHabitHistoryRow
		if err := rows.Scan(&i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitHistoryAvg = `-- name: GetHabitHistoryAvg :many
SELECT
    date_trunc($1::text, hl.log_date::timestamp)::date AS date,
    AVG(hl.value)::REAL AS value
FROM habit_logs hl
WHERE hl.habit_id = $2
  AND hl.log_date >= $3::date
  AND hl.log_date <= $4::date
GROUP BY date_trunc($1::text, hl.log_date::timestamp)
ORDER BY date
`

type GetHabitHistoryAvgParams struct {
	Frequency string    `db:"frequency" json:"frequency"`
	HabitID   int32     `db:"habit_id" json:"habit_id"`
	StartAt   time.Time `db:"start_at" json:"start_at"`
	EndAt     time.Time `db:"end_at" json:"end_at"`
}

type GetHabitHistoryAvgRow struct {
	Date  time.Time `db:"date" json:"date"`
	Value float32   `db:"value" json:"value"`
}

func (q *Queries) GetHabitHistoryAvg(ctx context.Context, arg GetHabitHistoryAvgParams) ([]GetHabitHistoryAvgRow, error) {
	rows, err := q.db.Query(ctx, getHabitHistoryAvg,
		arg.Frequency,
		arg.HabitID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHabitHistoryAvgRow{}
	for rows.Next() {
		var i GetHabitHistoryAvgRow
		if err := rows.Scan(&i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitLogs = `-- name: GetHabitLogs :many
SELECT habit_id, log_date, value
FROM habit_logs
WHERE habit_id = $1
ORDER BY log_date DESC
`

func (q *Queries) GetHabitLogs(ctx context.Context, habitID int32) ([]HabitLog, error) {
	rows, err := q.db.Query(ctx, getHabitLogs, habitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitLog{}
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(&i.HabitID, &i.LogDate, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitsWithLogs = `-- name: GetHabitsWithLogs :many
SELECT
    h.id, h.name, h.description,
    h.frequency, h.target_min, h.target_max, h.recording_required,
    h.current_streak, h.longest_streak,
    hl.value AS log_value,
    COALESCE(
        (SELECT SUM(hl2.value)
         FROM habit_logs hl2
         WHERE hl2.habit_id = h.id
           AND hl2.log_date BETWEEN
               CASE h.frequency
                   WHEN 'daily' THEN $1::date
                   WHEN 'weekly' THEN date_trunc('week', $1::date)::date
                   WHEN 'monthly' THEN date_trunc('month', $1::date)::date
               END
               AND
               CASE h.frequency
                   WHEN 'daily' THEN $1::date
                   WHEN 'weekly' THEN (date_trunc('week', $1::date) + INTERVAL '6 days')::date
                   WHEN 'monthly' THEN (date_trunc('month', $1::date) + INTERVAL '1 month - 1 day')::date
               END
        ), 0
    )::REAL AS period_value
FROM habits h
LEFT JOIN habit_logs hl ON h.id = hl.habit_id AND hl.log_date = $1
ORDER BY h.id
`

type GetHabitsWithLogsRow struct {
	ID                int32    `db:"id" json:"id"`
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
	CurrentStreak     int32    `db:"current_streak" json:"current_streak"`
	LongestStreak     int32    `db:"longest_streak" json:"longest_streak"`
	LogValue          *float32 `db:"log_value" json:"log_value"`
	PeriodValue       float32  `db:"period_value" json:"period_value"`
}

func (q *Queries) GetHabitsWithLogs(ctx context.Context, targetDate time.Time) ([]GetHabitsWithLogsRow, error) {
	rows, err := q.db.Query(ctx, getHabitsWithLogs, targetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHabitsWithLogsRow{}
	for rows.Next() {
		var i GetHabitsWithLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Frequency,
			&i.TargetMin,
			&i.TargetMax,
			&i.RecordingRequired,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LogValue,
			&i.PeriodValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabitStreak = `-- name: UpdateHabitStreak :exec
UPDATE habits
SET current_streak = $2, longest_streak = $3
WHERE id = $1
`

type UpdateHabitStreakParams struct {
	ID            int32 `db:"id" json:"id"`
	CurrentStreak int32 `db:"current_streak" json:"current_streak"`
	LongestStreak int32 `db:"longest_streak" json:"longest_streak"`
}

func (q *Queries) UpdateHabitStreak(ctx context.Context, arg UpdateHabitStreakParams) error {
	_, err := q.db.Exec(ctx, updateHabitStreak, arg.ID, arg.CurrentStreak, arg.LongestStreak)
	return err
}

const upsertLog = `-- name: UpsertLog :exec
INSERT INTO habit_logs (habit_id, log_date, value)
VALUES ($1, $2, $3)
ON CONFLICT (habit_id, log_date)
DO UPDATE SET value = excluded.value
`

type UpsertLogParams struct {
	HabitID int32     `db:"habit_id" json:"habit_id"`
	LogDate time.Time `db:"log_date" json:"log_date"`
	Value   float32   `db:"value" json:"value"`
}

func (q *Queries) UpsertLog(ctx context.Context, arg UpsertLogParams) error {
	_, err := q.db.Exec(ctx, upsertLog, arg.HabitID, arg.LogDate, arg.Value)
	return err
}
