// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package habitsdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Habit struct {
	ID                int32    `db:"id" json:"id"`
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	CurrentStreak     int32    `db:"current_streak" json:"current_streak"`
	LongestStreak     int32    `db:"longest_streak" json:"longest_streak"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
}

type HabitLog struct {
	HabitID int32     `db:"habit_id" json:"habit_id"`
	LogDate time.Time `db:"log_date" json:"log_date"`
	Value   float32   `db:"value" json:"value"`
}

type Project struct {
	ID          int32              `db:"id" json:"id"`
	ParentID    *int32             `db:"parent_id" json:"parent_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type Task struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   *int32             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	TaskType    string             `db:"task_type" json:"task_type"`
	Recurrence  *int32             `db:"recurrence" json:"recurrence"`
}

type TaskDependency struct {
	TaskID    int32 `db:"task_id" json:"task_id"`
	DependsOn int32 `db:"depends_on" json:"depends_on"`
}

type TimeEntry struct {
	ID         int32              `db:"id" json:"id"`
	TaskID     int32              `db:"task_id" json:"task_id"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Comment    *string            `db:"comment" json:"comment"`
}

type Todo struct {
	ID     int32  `db:"id" json:"id"`
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
	IsDone bool   `db:"is_done" json:"is_done"`
}
