ALTER TABLE projects ALTER COLUMN started_at TYPE TIMESTAMP USING started_at AT TIME ZONE 'UTC';
ALTER TABLE projects ALTER COLUMN finished_at TYPE TIMESTAMP USING finished_at AT TIME ZONE 'UTC';

ALTER TABLE tasks ALTER COLUMN started_at TYPE TIMESTAMP USING started_at AT TIME ZONE 'UTC';
ALTER TABLE tasks ALTER COLUMN finished_at TYPE TIMESTAMP USING finished_at AT TIME ZONE 'UTC';

ALTER TABLE time_entries ALTER COLUMN started_at TYPE TIMESTAMP USING started_at AT TIME ZONE 'UTC';
ALTER TABLE time_entries ALTER COLUMN finished_at TYPE TIMESTAMP USING finished_at AT TIME ZONE 'UTC';
