// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lights.sql

package gvdb

import (
	"context"
)

const createLight = `-- name: CreateLight :one
INSERT INTO lights (id, name, model, address, protocol, supports_color, supports_color_temp,
                    min_color_temp, max_color_temp, options)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, model, address, protocol, supports_color, supports_color_temp,
          min_color_temp, max_color_temp, options
`

type CreateLightParams struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Address           string  `db:"address" json:"address"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

type CreateLightRow struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Address           string  `db:"address" json:"address"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

func (q *Queries) CreateLight(ctx context.Context, arg CreateLightParams) (CreateLightRow, error) {
	row := q.db.QueryRow(ctx, createLight,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.Address,
		arg.Protocol,
		arg.SupportsColor,
		arg.SupportsColorTemp,
		arg.MinColorTemp,
		arg.MaxColorTemp,
		arg.Options,
	)
	var i CreateLightRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Address,
		&i.Protocol,
		&i.SupportsColor,
		&i.SupportsColorTemp,
		&i.MinColorTemp,
		&i.MaxColorTemp,
		&i.Options,
	)
	return i, err
}

const deleteLight = `-- name: DeleteLight :execrows
DELETE FROM lights WHERE id = $1
`

func (q *Queries) DeleteLight(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLight, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLight = `-- name: GetLight :one
SELECT id, name, model, address, protocol, supports_color, supports_color_temp,
       min_color_temp, max_color_temp, options
FROM lights
WHERE id = $1
`

type GetLightRow struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Address           string  `db:"address" json:"address"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

func (q *Queries) GetLight(ctx context.Context, id string) (GetLightRow, error) {
	row := q.db.QueryRow(ctx, getLight, id)
	var i GetLightRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Address,
		&i.Protocol,
		&i.SupportsColor,
		&i.SupportsColorTemp,
		&i.MinColorTemp,
		&i.MaxColorTemp,
		&i.Options,
	)
	return i, err
}

const listLights = `-- name: ListLights :many
SELECT id, name, model, address, protocol, supports_color, supports_color_temp,
       min_color_temp, max_color_temp, options
FROM lights
ORDER BY name
`

type ListLightsRow struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Address           string  `db:"address" json:"address"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

func (q *Queries) ListLights(ctx context.Context) ([]ListLightsRow, error) {
	rows, err := q.db.Query(ctx, listLights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLightsRow{}
	for rows.Next() {
		var i ListLightsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Model,
			&i.Address,
			&i.Protocol,
			&i.SupportsColor,
			&i.SupportsColorTemp,
			&i.MinColorTemp,
			&i.MaxColorTemp,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLight = `-- name: UpdateLight :one
UPDATE lights
SET name = $2, model = $3, protocol = $4, supports_color = $5, supports_color_temp = $6,
    min_color_temp = $7, max_color_temp = $8, options = $9
WHERE id = $1
RETURNING id, name, model, address, protocol, supports_color, supports_color_temp,
          min_color_temp, max_color_temp, options
`

type UpdateLightParams struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

type UpdateLightRow struct {
	ID                string  `db:"id" json:"id"`
	Name              string  `db:"name" json:"name"`
	Model             string  `db:"model" json:"model"`
	Address           string  `db:"address" json:"address"`
	Protocol          string  `db:"protocol" json:"protocol"`
	SupportsColor     bool    `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool    `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64 `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64 `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte  `db:"options" json:"options"`
}

func (q *Queries) UpdateLight(ctx context.Context, arg UpdateLightParams) (UpdateLightRow, error) {
	row := q.db.QueryRow(ctx, updateLight,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.Protocol,
		arg.SupportsColor,
		arg.SupportsColorTemp,
		arg.MinColorTemp,
		arg.MaxColorTemp,
		arg.Options,
	)
	var i UpdateLightRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Address,
		&i.Protocol,
		&i.SupportsColor,
		&i.SupportsColorTemp,
		&i.MinColorTemp,
		&i.MaxColorTemp,
		&i.Options,
	)
	return i, err
}
