// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gvdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	txtype "gv-api/internal/finance/txtype"
)

type Account struct {
	ID        int32              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Total     decimal.Decimal    `db:"total" json:"total"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AssistantUsage struct {
	ID               int32              `db:"id" json:"id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Model            string             `db:"model" json:"model"`
	Phase            string             `db:"phase" json:"phase"`
	InputTokens      int32              `db:"input_tokens" json:"input_tokens"`
	OutputTokens     int32              `db:"output_tokens" json:"output_tokens"`
	CacheReadTokens  int32              `db:"cache_read_tokens" json:"cache_read_tokens"`
	CacheWriteTokens int32              `db:"cache_write_tokens" json:"cache_write_tokens"`
	CostUsd          decimal.Decimal    `db:"cost_usd" json:"cost_usd"`
}

type Calendar struct {
	ID                 int32              `db:"id" json:"id"`
	AccountID          int32              `db:"account_id" json:"account_id"`
	GoogleCalendarID   string             `db:"google_calendar_id" json:"google_calendar_id"`
	Summary            string             `db:"summary" json:"summary"`
	Description        string             `db:"description" json:"description"`
	TimeZone           string             `db:"time_zone" json:"time_zone"`
	BackgroundColor    string             `db:"background_color" json:"background_color"`
	ForegroundColor    string             `db:"foreground_color" json:"foreground_color"`
	ColorOverride      string             `db:"color_override" json:"color_override"`
	AccessRole         string             `db:"access_role" json:"access_role"`
	IsPrimary          bool               `db:"is_primary" json:"is_primary"`
	SyncEnabled        bool               `db:"sync_enabled" json:"sync_enabled"`
	Visible            bool               `db:"visible" json:"visible"`
	SyncToken          *string            `db:"sync_token" json:"sync_token"`
	SyncTokenUpdatedAt pgtype.Timestamptz `db:"sync_token_updated_at" json:"sync_token_updated_at"`
	LastFullSyncAt     pgtype.Timestamptz `db:"last_full_sync_at" json:"last_full_sync_at"`
	LastSyncAt         pgtype.Timestamptz `db:"last_sync_at" json:"last_sync_at"`
	LastSyncError      *string            `db:"last_sync_error" json:"last_sync_error"`
	WatchChannelID     *string            `db:"watch_channel_id" json:"watch_channel_id"`
	WatchResourceID    *string            `db:"watch_resource_id" json:"watch_resource_id"`
	WatchToken         *string            `db:"watch_token" json:"watch_token"`
	WatchExpiresAt     pgtype.Timestamptz `db:"watch_expires_at" json:"watch_expires_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CalendarEvent struct {
	ID               int32              `db:"id" json:"id"`
	CalendarID       int32              `db:"calendar_id" json:"calendar_id"`
	GoogleEventID    string             `db:"google_event_id" json:"google_event_id"`
	IcalUid          string             `db:"ical_uid" json:"ical_uid"`
	Etag             string             `db:"etag" json:"etag"`
	Sequence         int32              `db:"sequence" json:"sequence"`
	Status           string             `db:"status" json:"status"`
	EventType        string             `db:"event_type" json:"event_type"`
	Summary          string             `db:"summary" json:"summary"`
	Description      string             `db:"description" json:"description"`
	Location         string             `db:"location" json:"location"`
	AllDay           bool               `db:"all_day" json:"all_day"`
	StartsAt         pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt           pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	StartTz          string             `db:"start_tz" json:"start_tz"`
	EndTz            string             `db:"end_tz" json:"end_tz"`
	Recurrence       []string           `db:"recurrence" json:"recurrence"`
	RecurringEventID *string            `db:"recurring_event_id" json:"recurring_event_id"`
	MasterID         *int32             `db:"master_id" json:"master_id"`
	OriginalStartsAt pgtype.Timestamptz `db:"original_starts_at" json:"original_starts_at"`
	OrganizerEmail   string             `db:"organizer_email" json:"organizer_email"`
	CreatorEmail     string             `db:"creator_email" json:"creator_email"`
	Attendees        []byte             `db:"attendees" json:"attendees"`
	Reminders        []byte             `db:"reminders" json:"reminders"`
	Transparency     string             `db:"transparency" json:"transparency"`
	Visibility       string             `db:"visibility" json:"visibility"`
	ColorID          string             `db:"color_id" json:"color_id"`
	HtmlLink         string             `db:"html_link" json:"html_link"`
	HangoutLink      string             `db:"hangout_link" json:"hangout_link"`
	CreatedByGv      bool               `db:"created_by_gv" json:"created_by_gv"`
	GoogleUpdatedAt  pgtype.Timestamptz `db:"google_updated_at" json:"google_updated_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CalendarSyncRun struct {
	ID         int32              `db:"id" json:"id"`
	CalendarID *int32             `db:"calendar_id" json:"calendar_id"`
	Trigger    string             `db:"trigger" json:"trigger"`
	Kind       string             `db:"kind" json:"kind"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Pages      int32              `db:"pages" json:"pages"`
	Upserted   int32              `db:"upserted" json:"upserted"`
	Deleted    int32              `db:"deleted" json:"deleted"`
	Error      *string            `db:"error" json:"error"`
}

type Category struct {
	ID        int32              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	ParentID  *int32             `db:"parent_id" json:"parent_id"`
	Type      txtype.Type        `db:"type" json:"type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ConcelloMark struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	VisitedOn   time.Time          `db:"visited_on" json:"visited_on"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GoogleAccount struct {
	ID                   int32              `db:"id" json:"id"`
	Email                string             `db:"email" json:"email"`
	Label                string             `db:"label" json:"label"`
	Color                string             `db:"color" json:"color"`
	RefreshToken         []byte             `db:"refresh_token" json:"refresh_token"`
	AccessToken          []byte             `db:"access_token" json:"access_token"`
	AccessTokenExpiresAt pgtype.Timestamptz `db:"access_token_expires_at" json:"access_token_expires_at"`
	Scopes               string             `db:"scopes" json:"scopes"`
	Status               string             `db:"status" json:"status"`
	LastSyncAt           pgtype.Timestamptz `db:"last_sync_at" json:"last_sync_at"`
	LastSyncError        *string            `db:"last_sync_error" json:"last_sync_error"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Habit struct {
	ID                int32    `db:"id" json:"id"`
	Name              string   `db:"name" json:"name"`
	Description       *string  `db:"description" json:"description"`
	Frequency         string   `db:"frequency" json:"frequency"`
	CurrentStreak     int32    `db:"current_streak" json:"current_streak"`
	LongestStreak     int32    `db:"longest_streak" json:"longest_streak"`
	TargetMin         *float32 `db:"target_min" json:"target_min"`
	TargetMax         *float32 `db:"target_max" json:"target_max"`
	RecordingRequired bool     `db:"recording_required" json:"recording_required"`
}

type HabitLog struct {
	HabitID int32     `db:"habit_id" json:"habit_id"`
	LogDate time.Time `db:"log_date" json:"log_date"`
	Value   float32   `db:"value" json:"value"`
}

type Light struct {
	ID                string             `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Model             string             `db:"model" json:"model"`
	Address           string             `db:"address" json:"address"`
	Protocol          string             `db:"protocol" json:"protocol"`
	SupportsColor     bool               `db:"supports_color" json:"supports_color"`
	SupportsColorTemp bool               `db:"supports_color_temp" json:"supports_color_temp"`
	MinColorTemp      float64            `db:"min_color_temp" json:"min_color_temp"`
	MaxColorTemp      float64            `db:"max_color_temp" json:"max_color_temp"`
	Options           []byte             `db:"options" json:"options"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PlanBlock struct {
	ID           int32              `db:"id" json:"id"`
	PlanDate     time.Time          `db:"plan_date" json:"plan_date"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt      pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	TaskID       *int32             `db:"task_id" json:"task_id"`
	Label        string             `db:"label" json:"label"`
	Note         *string            `db:"note" json:"note"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EventRef     *string            `db:"event_ref" json:"event_ref"`
	CommitmentID *int32             `db:"commitment_id" json:"commitment_id"`
}

type Project struct {
	ID          int32              `db:"id" json:"id"`
	ParentID    *int32             `db:"parent_id" json:"parent_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type RecurringCommitment struct {
	ID         int32              `db:"id" json:"id"`
	TaskID     int32              `db:"task_id" json:"task_id"`
	Label      string             `db:"label" json:"label"`
	DaysOfWeek []int16            `db:"days_of_week" json:"days_of_week"`
	StartTime  pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time        `db:"end_time" json:"end_time"`
	Active     bool               `db:"active" json:"active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RecurringCommitmentSkip struct {
	CommitmentID int32     `db:"commitment_id" json:"commitment_id"`
	SkipDate     time.Time `db:"skip_date" json:"skip_date"`
}

type Task struct {
	ID            int32              `db:"id" json:"id"`
	ProjectID     *int32             `db:"project_id" json:"project_id"`
	Name          string             `db:"name" json:"name"`
	Description   *string            `db:"description" json:"description"`
	DueAt         pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt    pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	TaskType      string             `db:"task_type" json:"task_type"`
	Recurrence    *int32             `db:"recurrence" json:"recurrence"`
	Priority      int32              `db:"priority" json:"priority"`
	EstimateHours *decimal.Decimal   `db:"estimate_hours" json:"estimate_hours"`
}

type TaskDependency struct {
	TaskID    int32 `db:"task_id" json:"task_id"`
	DependsOn int32 `db:"depends_on" json:"depends_on"`
}

type TimeEntry struct {
	ID         int32              `db:"id" json:"id"`
	TaskID     int32              `db:"task_id" json:"task_id"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Comment    *string            `db:"comment" json:"comment"`
}

type Todo struct {
	ID     int32  `db:"id" json:"id"`
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
	IsDone bool   `db:"is_done" json:"is_done"`
}

type Transaction struct {
	ID          int32              `db:"id" json:"id"`
	Type        txtype.Type        `db:"type" json:"type"`
	Amount      decimal.Decimal    `db:"amount" json:"amount"`
	AccountID   int32              `db:"account_id" json:"account_id"`
	ToAccountID *int32             `db:"to_account_id" json:"to_account_id"`
	Description *string            `db:"description" json:"description"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CategoryID  *int32             `db:"category_id" json:"category_id"`
}
