// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	backup "gv-api/internal/backup"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// List provides a mock function with no fields
func (_m *MockServiceInterface) List() ([]backup.Backup, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []backup.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]backup.Backup, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []backup.Backup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backup.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockServiceInterface_Expecter) List() *MockServiceInterface_List_Call {
	return &MockServiceInterface_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockServiceInterface_List_Call) Run(run func()) *MockServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceInterface_List_Call) Return(_a0 []backup.Backup, _a1 error) *MockServiceInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_List_Call) RunAndReturn(run func() ([]backup.Backup, error)) *MockServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function with given fields: name
func (_m *MockServiceInterface) Path(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockServiceInterface_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
//   - name string
func (_e *MockServiceInterface_Expecter) Path(name interface{}) *MockServiceInterface_Path_Call {
	return &MockServiceInterface_Path_Call{Call: _e.mock.On("Path", name)}
}

func (_c *MockServiceInterface_Path_Call) Run(run func(name string)) *MockServiceInterface_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceInterface_Path_Call) Return(_a0 string, _a1 error) *MockServiceInterface_Path_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Path_Call) RunAndReturn(run func(string) (string, error)) *MockServiceInterface_Path_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *MockServiceInterface) Run(ctx context.Context) (*backup.Backup, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *backup.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*backup.Backup, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *backup.Backup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backup.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockServiceInterface_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) Run(ctx interface{}) *MockServiceInterface_Run_Call {
	return &MockServiceInterface_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockServiceInterface_Run_Call) Run(run func(ctx context.Context)) *MockServiceInterface_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_Run_Call) Return(_a0 *backup.Backup, _a1 error) *MockServiceInterface_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Run_Call) RunAndReturn(run func(context.Context) (*backup.Backup, error)) *MockServiceInterface_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
