from enum import Enum


class Icons(str, Enum):
    check = "fas fa-check"
    times = "fas fa-times"
    edit = "fas fa-edit"
    trash = "fas fa-trash"
    plus = "fas fa-plus"
    minus = "fas fa-minus"
    calendar = "fas fa-calendar"
    clock = "fas fa-clock"
    bell = "fas fa-bell"
    info = "fas fa-info"
    question = "fas fa-question"
    dumbbell = "fas fa-dumbbell"
    book = "fas fa-book"
    droplet = "fas fa-droplet"
    brain = "fas fa-brain"
    scale = "fas fa-weight-scale"
    utensils = "fas fa-utensils"
    shoe_prints = "fas fa-shoe-prints"
    mobile_screen = "fas fa-mobile-screen"
    mug_hot = "fas fa-mug-hot"
    smoking = "fas fa-smoking"
