all: false
with-expecter: true
packages:
  gv-api/internal/tasks:
    config:
      dir: internal/tasks/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/habits:
    config:
      dir: internal/habits/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/plan:
    config:
      dir: internal/plan/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/finance:
    config:
      dir: internal/finance/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/calendar:
    config:
      dir: internal/calendar/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/rutas:
    config:
      dir: internal/rutas/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
  gv-api/internal/uptime:
    config:
      dir: internal/uptime/mocks
      outpkg: mocks
    interfaces:
      Repository:
      ServiceInterface:
