// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package varietiesdb

import (
	"context"
)

type Querier interface {
	CreateVariety(ctx context.Context, arg CreateVarietyParams) (WeedVariety, error)
	DeleteVariety(ctx context.Context, id int32) error
	GetVariety(ctx context.Context, id int32) (WeedVariety, error)
	ListVarieties(ctx context.Context) ([]WeedVariety, error)
	UpdateVariety(ctx context.Context, arg UpdateVarietyParams) (WeedVariety, error)
}

var _ Querier = (*Queries)(nil)
