// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	plan "gv-api/internal/plan"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) Create(ctx context.Context, req plan.CreatePlanBlockRequest) (plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plan.CreatePlanBlockRequest) (plan.PlanBlockResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plan.CreatePlanBlockRequest) plan.PlanBlockResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(plan.PlanBlockResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, plan.CreatePlanBlockRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req plan.CreatePlanBlockRequest
func (_e *MockServiceInterface_Expecter) Create(ctx interface{}, req interface{}) *MockServiceInterface_Create_Call {
	return &MockServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockServiceInterface_Create_Call) Run(run func(ctx context.Context, req plan.CreatePlanBlockRequest)) *MockServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plan.CreatePlanBlockRequest))
	})
	return _c
}

func (_c *MockServiceInterface_Create_Call) Return(_a0 plan.PlanBlockResponse, _a1 error) *MockServiceInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Create_Call) RunAndReturn(run func(context.Context, plan.CreatePlanBlockRequest) (plan.PlanBlockResponse, error)) *MockServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCommitment provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) CreateCommitment(ctx context.Context, req plan.CreateCommitmentRequest) (plan.RecurringCommitmentResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommitment")
	}

	var r0 plan.RecurringCommitmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plan.CreateCommitmentRequest) (plan.RecurringCommitmentResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plan.CreateCommitmentRequest) plan.RecurringCommitmentResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(plan.RecurringCommitmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, plan.CreateCommitmentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_CreateCommitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommitment'
type MockServiceInterface_CreateCommitment_Call struct {
	*mock.Call
}

// CreateCommitment is a helper method to define mock.On call
//   - ctx context.Context
//   - req plan.CreateCommitmentRequest
func (_e *MockServiceInterface_Expecter) CreateCommitment(ctx interface{}, req interface{}) *MockServiceInterface_CreateCommitment_Call {
	return &MockServiceInterface_CreateCommitment_Call{Call: _e.mock.On("CreateCommitment", ctx, req)}
}

func (_c *MockServiceInterface_CreateCommitment_Call) Run(run func(ctx context.Context, req plan.CreateCommitmentRequest)) *MockServiceInterface_CreateCommitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plan.CreateCommitmentRequest))
	})
	return _c
}

func (_c *MockServiceInterface_CreateCommitment_Call) Return(_a0 plan.RecurringCommitmentResponse, _a1 error) *MockServiceInterface_CreateCommitment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_CreateCommitment_Call) RunAndReturn(run func(context.Context, plan.CreateCommitmentRequest) (plan.RecurringCommitmentResponse, error)) *MockServiceInterface_CreateCommitment_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockServiceInterface) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockServiceInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockServiceInterface_Delete_Call {
	return &MockServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServiceInterface_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockServiceInterface_Delete_Call) Return(_a0 error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommitment provides a mock function with given fields: ctx, id
func (_m *MockServiceInterface) DeleteCommitment(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommitment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_DeleteCommitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommitment'
type MockServiceInterface_DeleteCommitment_Call struct {
	*mock.Call
}

// DeleteCommitment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockServiceInterface_Expecter) DeleteCommitment(ctx interface{}, id interface{}) *MockServiceInterface_DeleteCommitment_Call {
	return &MockServiceInterface_DeleteCommitment_Call{Call: _e.mock.On("DeleteCommitment", ctx, id)}
}

func (_c *MockServiceInterface_DeleteCommitment_Call) Run(run func(ctx context.Context, id int32)) *MockServiceInterface_DeleteCommitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockServiceInterface_DeleteCommitment_Call) Return(_a0 error) *MockServiceInterface_DeleteCommitment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_DeleteCommitment_Call) RunAndReturn(run func(context.Context, int32) error) *MockServiceInterface_DeleteCommitment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFuture provides a mock function with given fields: ctx
func (_m *MockServiceInterface) DeleteFuture(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFuture")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_DeleteFuture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFuture'
type MockServiceInterface_DeleteFuture_Call struct {
	*mock.Call
}

// DeleteFuture is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) DeleteFuture(ctx interface{}) *MockServiceInterface_DeleteFuture_Call {
	return &MockServiceInterface_DeleteFuture_Call{Call: _e.mock.On("DeleteFuture", ctx)}
}

func (_c *MockServiceInterface_DeleteFuture_Call) Run(run func(ctx context.Context)) *MockServiceInterface_DeleteFuture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_DeleteFuture_Call) Return(_a0 error) *MockServiceInterface_DeleteFuture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_DeleteFuture_Call) RunAndReturn(run func(context.Context) error) *MockServiceInterface_DeleteFuture_Call {
	_c.Call.Return(run)
	return _c
}

// GetRange provides a mock function with given fields: ctx, from, to
func (_m *MockServiceInterface) GetRange(ctx context.Context, from time.Time, to time.Time) (plan.PlanRangeResponse, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetRange")
	}

	var r0 plan.PlanRangeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (plan.PlanRangeResponse, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) plan.PlanRangeResponse); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Get(0).(plan.PlanRangeResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRange'
type MockServiceInterface_GetRange_Call struct {
	*mock.Call
}

// GetRange is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockServiceInterface_Expecter) GetRange(ctx interface{}, from interface{}, to interface{}) *MockServiceInterface_GetRange_Call {
	return &MockServiceInterface_GetRange_Call{Call: _e.mock.On("GetRange", ctx, from, to)}
}

func (_c *MockServiceInterface_GetRange_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockServiceInterface_GetRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockServiceInterface_GetRange_Call) Return(_a0 plan.PlanRangeResponse, _a1 error) *MockServiceInterface_GetRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (plan.PlanRangeResponse, error)) *MockServiceInterface_GetRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetToday provides a mock function with given fields: ctx
func (_m *MockServiceInterface) GetToday(ctx context.Context) (plan.PlanTodayResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetToday")
	}

	var r0 plan.PlanTodayResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (plan.PlanTodayResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) plan.PlanTodayResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(plan.PlanTodayResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToday'
type MockServiceInterface_GetToday_Call struct {
	*mock.Call
}

// GetToday is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) GetToday(ctx interface{}) *MockServiceInterface_GetToday_Call {
	return &MockServiceInterface_GetToday_Call{Call: _e.mock.On("GetToday", ctx)}
}

func (_c *MockServiceInterface_GetToday_Call) Run(run func(ctx context.Context)) *MockServiceInterface_GetToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_GetToday_Call) Return(_a0 plan.PlanTodayResponse, _a1 error) *MockServiceInterface_GetToday_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetToday_Call) RunAndReturn(run func(context.Context) (plan.PlanTodayResponse, error)) *MockServiceInterface_GetToday_Call {
	_c.Call.Return(run)
	return _c
}

// ListCommitments provides a mock function with given fields: ctx
func (_m *MockServiceInterface) ListCommitments(ctx context.Context) ([]plan.RecurringCommitmentResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCommitments")
	}

	var r0 []plan.RecurringCommitmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]plan.RecurringCommitmentResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []plan.RecurringCommitmentResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plan.RecurringCommitmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_ListCommitments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommitments'
type MockServiceInterface_ListCommitments_Call struct {
	*mock.Call
}

// ListCommitments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) ListCommitments(ctx interface{}) *MockServiceInterface_ListCommitments_Call {
	return &MockServiceInterface_ListCommitments_Call{Call: _e.mock.On("ListCommitments", ctx)}
}

func (_c *MockServiceInterface_ListCommitments_Call) Run(run func(ctx context.Context)) *MockServiceInterface_ListCommitments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_ListCommitments_Call) Return(_a0 []plan.RecurringCommitmentResponse, _a1 error) *MockServiceInterface_ListCommitments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_ListCommitments_Call) RunAndReturn(run func(context.Context) ([]plan.RecurringCommitmentResponse, error)) *MockServiceInterface_ListCommitments_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) Update(ctx context.Context, req plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdatePlanBlockRequest) plan.PlanBlockResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(plan.PlanBlockResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, plan.UpdatePlanBlockRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req plan.UpdatePlanBlockRequest
func (_e *MockServiceInterface_Expecter) Update(ctx interface{}, req interface{}) *MockServiceInterface_Update_Call {
	return &MockServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockServiceInterface_Update_Call) Run(run func(ctx context.Context, req plan.UpdatePlanBlockRequest)) *MockServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plan.UpdatePlanBlockRequest))
	})
	return _c
}

func (_c *MockServiceInterface_Update_Call) Return(_a0 plan.PlanBlockResponse, _a1 error) *MockServiceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Update_Call) RunAndReturn(run func(context.Context, plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error)) *MockServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommitment provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) UpdateCommitment(ctx context.Context, req plan.UpdateCommitmentRequest) (plan.RecurringCommitmentResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommitment")
	}

	var r0 plan.RecurringCommitmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdateCommitmentRequest) (plan.RecurringCommitmentResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdateCommitmentRequest) plan.RecurringCommitmentResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(plan.RecurringCommitmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, plan.UpdateCommitmentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_UpdateCommitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommitment'
type MockServiceInterface_UpdateCommitment_Call struct {
	*mock.Call
}

// UpdateCommitment is a helper method to define mock.On call
//   - ctx context.Context
//   - req plan.UpdateCommitmentRequest
func (_e *MockServiceInterface_Expecter) UpdateCommitment(ctx interface{}, req interface{}) *MockServiceInterface_UpdateCommitment_Call {
	return &MockServiceInterface_UpdateCommitment_Call{Call: _e.mock.On("UpdateCommitment", ctx, req)}
}

func (_c *MockServiceInterface_UpdateCommitment_Call) Run(run func(ctx context.Context, req plan.UpdateCommitmentRequest)) *MockServiceInterface_UpdateCommitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plan.UpdateCommitmentRequest))
	})
	return _c
}

func (_c *MockServiceInterface_UpdateCommitment_Call) Return(_a0 plan.RecurringCommitmentResponse, _a1 error) *MockServiceInterface_UpdateCommitment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_UpdateCommitment_Call) RunAndReturn(run func(context.Context, plan.UpdateCommitmentRequest) (plan.RecurringCommitmentResponse, error)) *MockServiceInterface_UpdateCommitment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
