// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	plan "gv-api/internal/plan"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, planDate, startedAt, endedAt, taskID, label, note
func (_m *MockRepository) Create(ctx context.Context, planDate time.Time, startedAt time.Time, endedAt time.Time, taskID *int32, label string, note *string) (plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, planDate, startedAt, endedAt, taskID, label, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, time.Time, *int32, string, *string) (plan.PlanBlockResponse, error)); ok {
		return rf(ctx, planDate, startedAt, endedAt, taskID, label, note)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, time.Time, *int32, string, *string) plan.PlanBlockResponse); ok {
		r0 = rf(ctx, planDate, startedAt, endedAt, taskID, label, note)
	} else {
		r0 = ret.Get(0).(plan.PlanBlockResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, time.Time, *int32, string, *string) error); ok {
		r1 = rf(ctx, planDate, startedAt, endedAt, taskID, label, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - planDate time.Time
//   - startedAt time.Time
//   - endedAt time.Time
//   - taskID *int32
//   - label string
//   - note *string
func (_e *MockRepository_Expecter) Create(ctx interface{}, planDate interface{}, startedAt interface{}, endedAt interface{}, taskID interface{}, label interface{}, note interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, planDate, startedAt, endedAt, taskID, label, note)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, planDate time.Time, startedAt time.Time, endedAt time.Time, taskID *int32, label string, note *string)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(time.Time), args[4].(*int32), args[5].(string), args[6].(*string))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 plan.PlanBlockResponse, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, time.Time, *int32, string, *string) (plan.PlanBlockResponse, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id int32) (plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (plan.PlanBlockResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) plan.PlanBlockResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(plan.PlanBlockResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 plan.PlanBlockResponse, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, int32) (plan.PlanBlockResponse, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskName provides a mock function with given fields: ctx, taskID
func (_m *MockRepository) GetTaskName(ctx context.Context, taskID int32) (string, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (string, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) string); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTaskName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskName'
type MockRepository_GetTaskName_Call struct {
	*mock.Call
}

// GetTaskName is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
func (_e *MockRepository_Expecter) GetTaskName(ctx interface{}, taskID interface{}) *MockRepository_GetTaskName_Call {
	return &MockRepository_GetTaskName_Call{Call: _e.mock.On("GetTaskName", ctx, taskID)}
}

func (_c *MockRepository_GetTaskName_Call) Run(run func(ctx context.Context, taskID int32)) *MockRepository_GetTaskName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetTaskName_Call) Return(_a0 string, _a1 error) *MockRepository_GetTaskName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTaskName_Call) RunAndReturn(run func(context.Context, int32) (string, error)) *MockRepository_GetTaskName_Call {
	_c.Call.Return(run)
	return _c
}

// HasOverlap provides a mock function with given fields: ctx, planDate, startedAt, endedAt, excludeID
func (_m *MockRepository) HasOverlap(ctx context.Context, planDate time.Time, startedAt time.Time, endedAt time.Time, excludeID *int32) (bool, error) {
	ret := _m.Called(ctx, planDate, startedAt, endedAt, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for HasOverlap")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, time.Time, *int32) (bool, error)); ok {
		return rf(ctx, planDate, startedAt, endedAt, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, time.Time, *int32) bool); ok {
		r0 = rf(ctx, planDate, startedAt, endedAt, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, time.Time, *int32) error); ok {
		r1 = rf(ctx, planDate, startedAt, endedAt, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_HasOverlap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOverlap'
type MockRepository_HasOverlap_Call struct {
	*mock.Call
}

// HasOverlap is a helper method to define mock.On call
//   - ctx context.Context
//   - planDate time.Time
//   - startedAt time.Time
//   - endedAt time.Time
//   - excludeID *int32
func (_e *MockRepository_Expecter) HasOverlap(ctx interface{}, planDate interface{}, startedAt interface{}, endedAt interface{}, excludeID interface{}) *MockRepository_HasOverlap_Call {
	return &MockRepository_HasOverlap_Call{Call: _e.mock.On("HasOverlap", ctx, planDate, startedAt, endedAt, excludeID)}
}

func (_c *MockRepository_HasOverlap_Call) Run(run func(ctx context.Context, planDate time.Time, startedAt time.Time, endedAt time.Time, excludeID *int32)) *MockRepository_HasOverlap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(time.Time), args[4].(*int32))
	})
	return _c
}

func (_c *MockRepository_HasOverlap_Call) Return(_a0 bool, _a1 error) *MockRepository_HasOverlap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_HasOverlap_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, time.Time, *int32) (bool, error)) *MockRepository_HasOverlap_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDate provides a mock function with given fields: ctx, date
func (_m *MockRepository) ListByDate(ctx context.Context, date time.Time) ([]plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for ListByDate")
	}

	var r0 []plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]plan.PlanBlockResponse, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []plan.PlanBlockResponse); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plan.PlanBlockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDate'
type MockRepository_ListByDate_Call struct {
	*mock.Call
}

// ListByDate is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
func (_e *MockRepository_Expecter) ListByDate(ctx interface{}, date interface{}) *MockRepository_ListByDate_Call {
	return &MockRepository_ListByDate_Call{Call: _e.mock.On("ListByDate", ctx, date)}
}

func (_c *MockRepository_ListByDate_Call) Run(run func(ctx context.Context, date time.Time)) *MockRepository_ListByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListByDate_Call) Return(_a0 []plan.PlanBlockResponse, _a1 error) *MockRepository_ListByDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByDate_Call) RunAndReturn(run func(context.Context, time.Time) ([]plan.PlanBlockResponse, error)) *MockRepository_ListByDate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockRepository) Update(ctx context.Context, req plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 plan.PlanBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plan.UpdatePlanBlockRequest) plan.PlanBlockResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(plan.PlanBlockResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, plan.UpdatePlanBlockRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req plan.UpdatePlanBlockRequest
func (_e *MockRepository_Expecter) Update(ctx interface{}, req interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, req plan.UpdatePlanBlockRequest)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(plan.UpdatePlanBlockRequest))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 plan.PlanBlockResponse, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, plan.UpdatePlanBlockRequest) (plan.PlanBlockResponse, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
