// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package financedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	txtype "gv-api/internal/finance/txtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name)
VALUES ($1)
RETURNING id, name, total, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id, type)
VALUES ($1, $2, $3)
RETURNING id, name, parent_id, type, created_at
`

type CreateCategoryParams struct {
	Name     string      `db:"name" json:"name"`
	ParentID *int32      `db:"parent_id" json:"parent_id"`
	Type     txtype.Type `db:"type" json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ParentID, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (type, amount, account_id, to_account_id, category_id, description, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7::timestamptz, now()))
RETURNING id, type, amount, account_id, to_account_id, description, occurred_at, created_at, category_id
`

type CreateTransactionParams struct {
	Type        txtype.Type        `db:"type" json:"type"`
	Amount      decimal.Decimal    `db:"amount" json:"amount"`
	AccountID   int32              `db:"account_id" json:"account_id"`
	ToAccountID *int32             `db:"to_account_id" json:"to_account_id"`
	CategoryID  *int32             `db:"category_id" json:"category_id"`
	Description *string            `db:"description" json:"description"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Type,
		arg.Amount,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Description,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.AccountID,
		&i.ToAccountID,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, total, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountsTotal = `-- name: GetAccountsTotal :one
SELECT COALESCE(SUM(total), 0::numeric)::numeric AS total
FROM accounts
`

func (q *Queries) GetAccountsTotal(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getAccountsTotal)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, parent_id, type, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryType = `-- name: GetCategoryType :one
SELECT type
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryType(ctx context.Context, id int32) (txtype.Type, error) {
	row := q.db.QueryRow(ctx, getCategoryType, id)
	var type_ txtype.Type
	err := row.Scan(&type_)
	return type_, err
}

const getMonthlyTotals = `-- name: GetMonthlyTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'::transaction_type),  0::numeric)::numeric AS income,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'::transaction_type), 0::numeric)::numeric AS expense
FROM transactions
WHERE occurred_at >= $1
`

type GetMonthlyTotalsRow struct {
	Income  decimal.Decimal `db:"income" json:"income"`
	Expense decimal.Decimal `db:"expense" json:"expense"`
}

func (q *Queries) GetMonthlyTotals(ctx context.Context, occurredAt pgtype.Timestamptz) (GetMonthlyTotalsRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyTotals, occurredAt)
	var i GetMonthlyTotalsRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, amount, account_id, to_account_id, description, occurred_at, created_at, category_id
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.AccountID,
		&i.ToAccountID,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, total, created_at
FROM accounts
ORDER BY name ASC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, type, created_at
FROM categories
ORDER BY type ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT
    t.id,
    t.type,
    t.amount,
    a.name  AS account_name,
    ta.name AS to_account_name,
    c.name  AS category_name,
    t.description,
    t.occurred_at
FROM transactions t
JOIN accounts a       ON a.id  = t.account_id
LEFT JOIN accounts ta ON ta.id = t.to_account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.occurred_at >= $1
ORDER BY t.occurred_at DESC, t.id DESC
`

type ListRecentTransactionsRow struct {
	ID            int32              `db:"id" json:"id"`
	Type          txtype.Type        `db:"type" json:"type"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	AccountName   string             `db:"account_name" json:"account_name"`
	ToAccountName *string            `db:"to_account_name" json:"to_account_name"`
	CategoryName  *string            `db:"category_name" json:"category_name"`
	Description   *string            `db:"description" json:"description"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) ListRecentTransactions(ctx context.Context, occurredAt pgtype.Timestamptz) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentTransactions, occurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransactionsRow{}
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.AccountName,
			&i.ToAccountName,
			&i.CategoryName,
			&i.Description,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, type, amount, account_id, to_account_id, description, occurred_at, created_at, category_id
FROM transactions
ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.AccountID,
			&i.ToAccountID,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, type, amount, account_id, to_account_id, description, occurred_at, created_at, category_id
FROM transactions
WHERE account_id = $1 OR to_account_id = $1
ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.AccountID,
			&i.ToAccountID,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2
WHERE id = $1
RETURNING id, name, total, created_at
`

type UpdateAccountParams struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, parent_id = $3, type = $4
WHERE id = $1
RETURNING id, name, parent_id, type, created_at
`

type UpdateCategoryParams struct {
	ID       int32       `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	ParentID *int32      `db:"parent_id" json:"parent_id"`
	Type     txtype.Type `db:"type" json:"type"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = $2, amount = $3, account_id = $4, to_account_id = $5, category_id = $6, description = $7, occurred_at = $8
WHERE id = $1
RETURNING id, type, amount, account_id, to_account_id, description, occurred_at, created_at, category_id
`

type UpdateTransactionParams struct {
	ID          int32              `db:"id" json:"id"`
	Type        txtype.Type        `db:"type" json:"type"`
	Amount      decimal.Decimal    `db:"amount" json:"amount"`
	AccountID   int32              `db:"account_id" json:"account_id"`
	ToAccountID *int32             `db:"to_account_id" json:"to_account_id"`
	CategoryID  *int32             `db:"category_id" json:"category_id"`
	Description *string            `db:"description" json:"description"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.Amount,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Description,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.AccountID,
		&i.ToAccountID,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}
