// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package financedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	txtype "gv-api/internal/finance/txtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, name string) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteTransaction(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccountsTotal(ctx context.Context) (decimal.Decimal, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCategoryType(ctx context.Context, id int32) (txtype.Type, error)
	GetMonthlyTotals(ctx context.Context, occurredAt pgtype.Timestamptz) (GetMonthlyTotalsRow, error)
	GetTransaction(ctx context.Context, id int32) (Transaction, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListRecentTransactions(ctx context.Context, occurredAt pgtype.Timestamptz) ([]ListRecentTransactionsRow, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	ListTransactionsByAccount(ctx context.Context, accountID int32) ([]Transaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
