"""add_big_step_small_step

Revision ID: 002
Revises: 001
Create Date: 2026-01-05 20:24:20.138992

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habit", sa.Column("big_step", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(
        "habit", sa.Column("small_step", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habit", "small_step")
    op.drop_column("habit", "big_step")
    # ### end Alembic commands ###
