// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package plandb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOverlappingPlanBlocks(ctx context.Context, arg CountOverlappingPlanBlocksParams) (int64, error)
	CreatePlanBlock(ctx context.Context, arg CreatePlanBlockParams) (CreatePlanBlockRow, error)
	DeletePlanBlock(ctx context.Context, id int32) error
	DeletePlanBlocksEndingAfter(ctx context.Context, endedAt pgtype.Timestamptz) error
	GetPlanBlock(ctx context.Context, id int32) (GetPlanBlockRow, error)
	GetTaskName(ctx context.Context, id int32) (string, error)
	ListPlanBlocksByDate(ctx context.Context, planDate time.Time) ([]ListPlanBlocksByDateRow, error)
	UpdatePlanBlock(ctx context.Context, arg UpdatePlanBlockParams) (UpdatePlanBlockRow, error)
}

var _ Querier = (*Queries)(nil)
