// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	habits "gv-api/internal/habits"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateHabit provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) CreateHabit(ctx context.Context, req habits.CreateHabitRequest) (habits.CreateHabitResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateHabit")
	}

	var r0 habits.CreateHabitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, habits.CreateHabitRequest) (habits.CreateHabitResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, habits.CreateHabitRequest) habits.CreateHabitResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(habits.CreateHabitResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, habits.CreateHabitRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_CreateHabit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHabit'
type MockServiceInterface_CreateHabit_Call struct {
	*mock.Call
}

// CreateHabit is a helper method to define mock.On call
//   - ctx context.Context
//   - req habits.CreateHabitRequest
func (_e *MockServiceInterface_Expecter) CreateHabit(ctx interface{}, req interface{}) *MockServiceInterface_CreateHabit_Call {
	return &MockServiceInterface_CreateHabit_Call{Call: _e.mock.On("CreateHabit", ctx, req)}
}

func (_c *MockServiceInterface_CreateHabit_Call) Run(run func(ctx context.Context, req habits.CreateHabitRequest)) *MockServiceInterface_CreateHabit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(habits.CreateHabitRequest))
	})
	return _c
}

func (_c *MockServiceInterface_CreateHabit_Call) Return(_a0 habits.CreateHabitResponse, _a1 error) *MockServiceInterface_CreateHabit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_CreateHabit_Call) RunAndReturn(run func(context.Context, habits.CreateHabitRequest) (habits.CreateHabitResponse, error)) *MockServiceInterface_CreateHabit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHabit provides a mock function with given fields: ctx, id
func (_m *MockServiceInterface) DeleteHabit(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHabit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_DeleteHabit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHabit'
type MockServiceInterface_DeleteHabit_Call struct {
	*mock.Call
}

// DeleteHabit is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockServiceInterface_Expecter) DeleteHabit(ctx interface{}, id interface{}) *MockServiceInterface_DeleteHabit_Call {
	return &MockServiceInterface_DeleteHabit_Call{Call: _e.mock.On("DeleteHabit", ctx, id)}
}

func (_c *MockServiceInterface_DeleteHabit_Call) Run(run func(ctx context.Context, id int32)) *MockServiceInterface_DeleteHabit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockServiceInterface_DeleteHabit_Call) Return(_a0 error) *MockServiceInterface_DeleteHabit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_DeleteHabit_Call) RunAndReturn(run func(context.Context, int32) error) *MockServiceInterface_DeleteHabit_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyView provides a mock function with given fields: ctx, dateStr
func (_m *MockServiceInterface) GetDailyView(ctx context.Context, dateStr string) ([]habits.HabitWithLog, error) {
	ret := _m.Called(ctx, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyView")
	}

	var r0 []habits.HabitWithLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]habits.HabitWithLog, error)); ok {
		return rf(ctx, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []habits.HabitWithLog); ok {
		r0 = rf(ctx, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]habits.HabitWithLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetDailyView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyView'
type MockServiceInterface_GetDailyView_Call struct {
	*mock.Call
}

// GetDailyView is a helper method to define mock.On call
//   - ctx context.Context
//   - dateStr string
func (_e *MockServiceInterface_Expecter) GetDailyView(ctx interface{}, dateStr interface{}) *MockServiceInterface_GetDailyView_Call {
	return &MockServiceInterface_GetDailyView_Call{Call: _e.mock.On("GetDailyView", ctx, dateStr)}
}

func (_c *MockServiceInterface_GetDailyView_Call) Run(run func(ctx context.Context, dateStr string)) *MockServiceInterface_GetDailyView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServiceInterface_GetDailyView_Call) Return(_a0 []habits.HabitWithLog, _a1 error) *MockServiceInterface_GetDailyView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetDailyView_Call) RunAndReturn(run func(context.Context, string) ([]habits.HabitWithLog, error)) *MockServiceInterface_GetDailyView_Call {
	_c.Call.Return(run)
	return _c
}

// LogHabit provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) LogHabit(ctx context.Context, req habits.LogUpsertRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogHabit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, habits.LogUpsertRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_LogHabit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogHabit'
type MockServiceInterface_LogHabit_Call struct {
	*mock.Call
}

// LogHabit is a helper method to define mock.On call
//   - ctx context.Context
//   - req habits.LogUpsertRequest
func (_e *MockServiceInterface_Expecter) LogHabit(ctx interface{}, req interface{}) *MockServiceInterface_LogHabit_Call {
	return &MockServiceInterface_LogHabit_Call{Call: _e.mock.On("LogHabit", ctx, req)}
}

func (_c *MockServiceInterface_LogHabit_Call) Run(run func(ctx context.Context, req habits.LogUpsertRequest)) *MockServiceInterface_LogHabit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(habits.LogUpsertRequest))
	})
	return _c
}

func (_c *MockServiceInterface_LogHabit_Call) Return(_a0 error) *MockServiceInterface_LogHabit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_LogHabit_Call) RunAndReturn(run func(context.Context, habits.LogUpsertRequest) error) *MockServiceInterface_LogHabit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
