// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rutasdb

import (
	"context"
)

type Querier interface {
	CreateConcelloMark(ctx context.Context, arg CreateConcelloMarkParams) (ConcelloMark, error)
	DeleteConcelloMark(ctx context.Context, id int32) error
	GetConcelloMark(ctx context.Context, id int32) (ConcelloMark, error)
	ListConcelloMarks(ctx context.Context) ([]ConcelloMark, error)
	UpdateConcelloMark(ctx context.Context, arg UpdateConcelloMarkParams) (ConcelloMark, error)
	UpsertConcelloMark(ctx context.Context, arg UpsertConcelloMarkParams) (ConcelloMark, error)
}

var _ Querier = (*Queries)(nil)
