// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	finance "gv-api/internal/finance"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	time "time"

	txtype "gv-api/internal/finance/txtype"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, req
func (_m *MockRepository) CreateAccount(ctx context.Context, req finance.CreateAccountRequest) (finance.Account, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 finance.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateAccountRequest) (finance.Account, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateAccountRequest) finance.Account); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.CreateAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.CreateAccountRequest
func (_e *MockRepository_Expecter) CreateAccount(ctx interface{}, req interface{}) *MockRepository_CreateAccount_Call {
	return &MockRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, req)}
}

func (_c *MockRepository_CreateAccount_Call) Run(run func(ctx context.Context, req finance.CreateAccountRequest)) *MockRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.CreateAccountRequest))
	})
	return _c
}

func (_c *MockRepository_CreateAccount_Call) Return(_a0 finance.Account, _a1 error) *MockRepository_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateAccount_Call) RunAndReturn(run func(context.Context, finance.CreateAccountRequest) (finance.Account, error)) *MockRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCategory provides a mock function with given fields: ctx, req
func (_m *MockRepository) CreateCategory(ctx context.Context, req finance.CreateCategoryRequest) (finance.Category, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 finance.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateCategoryRequest) (finance.Category, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateCategoryRequest) finance.Category); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.CreateCategoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.CreateCategoryRequest
func (_e *MockRepository_Expecter) CreateCategory(ctx interface{}, req interface{}) *MockRepository_CreateCategory_Call {
	return &MockRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, req)}
}

func (_c *MockRepository_CreateCategory_Call) Run(run func(ctx context.Context, req finance.CreateCategoryRequest)) *MockRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.CreateCategoryRequest))
	})
	return _c
}

func (_c *MockRepository_CreateCategory_Call) Return(_a0 finance.Category, _a1 error) *MockRepository_CreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateCategory_Call) RunAndReturn(run func(context.Context, finance.CreateCategoryRequest) (finance.Category, error)) *MockRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: ctx, req
func (_m *MockRepository) CreateTransaction(ctx context.Context, req finance.CreateTransactionRequest) (finance.Transaction, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 finance.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateTransactionRequest) (finance.Transaction, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.CreateTransactionRequest) finance.Transaction); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.CreateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockRepository_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.CreateTransactionRequest
func (_e *MockRepository_Expecter) CreateTransaction(ctx interface{}, req interface{}) *MockRepository_CreateTransaction_Call {
	return &MockRepository_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, req)}
}

func (_c *MockRepository_CreateTransaction_Call) Run(run func(ctx context.Context, req finance.CreateTransactionRequest)) *MockRepository_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.CreateTransactionRequest))
	})
	return _c
}

func (_c *MockRepository_CreateTransaction_Call) Return(_a0 finance.Transaction, _a1 error) *MockRepository_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateTransaction_Call) RunAndReturn(run func(context.Context, finance.CreateTransactionRequest) (finance.Transaction, error)) *MockRepository_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteAccount(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockRepository_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteAccount(ctx interface{}, id interface{}) *MockRepository_DeleteAccount_Call {
	return &MockRepository_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *MockRepository_DeleteAccount_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) Return(_a0 error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteCategory(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockRepository_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteCategory(ctx interface{}, id interface{}) *MockRepository_DeleteCategory_Call {
	return &MockRepository_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, id)}
}

func (_c *MockRepository_DeleteCategory_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteCategory_Call) Return(_a0 error) *MockRepository_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteCategory_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteTransaction(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type MockRepository_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteTransaction(ctx interface{}, id interface{}) *MockRepository_DeleteTransaction_Call {
	return &MockRepository_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, id)}
}

func (_c *MockRepository_DeleteTransaction_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteTransaction_Call) Return(_a0 error) *MockRepository_DeleteTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteTransaction_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetAccount(ctx context.Context, id int32) (finance.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 finance.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (finance.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) finance.Account); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(finance.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetAccount(ctx interface{}, id interface{}) *MockRepository_GetAccount_Call {
	return &MockRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *MockRepository_GetAccount_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetAccount_Call) Return(_a0 finance.Account, _a1 error) *MockRepository_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAccount_Call) RunAndReturn(run func(context.Context, int32) (finance.Account, error)) *MockRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsTotal provides a mock function with given fields: ctx
func (_m *MockRepository) GetAccountsTotal(ctx context.Context) (decimal.Decimal, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsTotal")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (decimal.Decimal, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) decimal.Decimal); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAccountsTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsTotal'
type MockRepository_GetAccountsTotal_Call struct {
	*mock.Call
}

// GetAccountsTotal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAccountsTotal(ctx interface{}) *MockRepository_GetAccountsTotal_Call {
	return &MockRepository_GetAccountsTotal_Call{Call: _e.mock.On("GetAccountsTotal", ctx)}
}

func (_c *MockRepository_GetAccountsTotal_Call) Run(run func(ctx context.Context)) *MockRepository_GetAccountsTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAccountsTotal_Call) Return(_a0 decimal.Decimal, _a1 error) *MockRepository_GetAccountsTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAccountsTotal_Call) RunAndReturn(run func(context.Context) (decimal.Decimal, error)) *MockRepository_GetAccountsTotal_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetCategory(ctx context.Context, id int32) (finance.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 finance.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (finance.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) finance.Category); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(finance.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockRepository_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetCategory(ctx interface{}, id interface{}) *MockRepository_GetCategory_Call {
	return &MockRepository_GetCategory_Call{Call: _e.mock.On("GetCategory", ctx, id)}
}

func (_c *MockRepository_GetCategory_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetCategory_Call) Return(_a0 finance.Category, _a1 error) *MockRepository_GetCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCategory_Call) RunAndReturn(run func(context.Context, int32) (finance.Category, error)) *MockRepository_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryStats provides a mock function with given fields: ctx, q
func (_m *MockRepository) GetCategoryStats(ctx context.Context, q finance.CategoryStatsQuery) ([]finance.CategoryStat, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryStats")
	}

	var r0 []finance.CategoryStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.CategoryStatsQuery) ([]finance.CategoryStat, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.CategoryStatsQuery) []finance.CategoryStat); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.CategoryStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.CategoryStatsQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCategoryStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryStats'
type MockRepository_GetCategoryStats_Call struct {
	*mock.Call
}

// GetCategoryStats is a helper method to define mock.On call
//   - ctx context.Context
//   - q finance.CategoryStatsQuery
func (_e *MockRepository_Expecter) GetCategoryStats(ctx interface{}, q interface{}) *MockRepository_GetCategoryStats_Call {
	return &MockRepository_GetCategoryStats_Call{Call: _e.mock.On("GetCategoryStats", ctx, q)}
}

func (_c *MockRepository_GetCategoryStats_Call) Run(run func(ctx context.Context, q finance.CategoryStatsQuery)) *MockRepository_GetCategoryStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.CategoryStatsQuery))
	})
	return _c
}

func (_c *MockRepository_GetCategoryStats_Call) Return(_a0 []finance.CategoryStat, _a1 error) *MockRepository_GetCategoryStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCategoryStats_Call) RunAndReturn(run func(context.Context, finance.CategoryStatsQuery) ([]finance.CategoryStat, error)) *MockRepository_GetCategoryStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryType provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetCategoryType(ctx context.Context, id int32) (txtype.Type, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryType")
	}

	var r0 txtype.Type
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (txtype.Type, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) txtype.Type); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(txtype.Type)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCategoryType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryType'
type MockRepository_GetCategoryType_Call struct {
	*mock.Call
}

// GetCategoryType is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetCategoryType(ctx interface{}, id interface{}) *MockRepository_GetCategoryType_Call {
	return &MockRepository_GetCategoryType_Call{Call: _e.mock.On("GetCategoryType", ctx, id)}
}

func (_c *MockRepository_GetCategoryType_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetCategoryType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetCategoryType_Call) Return(_a0 txtype.Type, _a1 error) *MockRepository_GetCategoryType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCategoryType_Call) RunAndReturn(run func(context.Context, int32) (txtype.Type, error)) *MockRepository_GetCategoryType_Call {
	_c.Call.Return(run)
	return _c
}

// GetEarliestTransactionDate provides a mock function with given fields: ctx
func (_m *MockRepository) GetEarliestTransactionDate(ctx context.Context) (time.Time, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEarliestTransactionDate")
	}

	var r0 time.Time
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Time, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetEarliestTransactionDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEarliestTransactionDate'
type MockRepository_GetEarliestTransactionDate_Call struct {
	*mock.Call
}

// GetEarliestTransactionDate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetEarliestTransactionDate(ctx interface{}) *MockRepository_GetEarliestTransactionDate_Call {
	return &MockRepository_GetEarliestTransactionDate_Call{Call: _e.mock.On("GetEarliestTransactionDate", ctx)}
}

func (_c *MockRepository_GetEarliestTransactionDate_Call) Run(run func(ctx context.Context)) *MockRepository_GetEarliestTransactionDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetEarliestTransactionDate_Call) Return(_a0 time.Time, _a1 bool, _a2 error) *MockRepository_GetEarliestTransactionDate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetEarliestTransactionDate_Call) RunAndReturn(run func(context.Context) (time.Time, bool, error)) *MockRepository_GetEarliestTransactionDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyStats provides a mock function with given fields: ctx, q
func (_m *MockRepository) GetMonthlyStats(ctx context.Context, q finance.MonthlyStatsQuery) ([]finance.MonthlyStat, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyStats")
	}

	var r0 []finance.MonthlyStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.MonthlyStatsQuery) ([]finance.MonthlyStat, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.MonthlyStatsQuery) []finance.MonthlyStat); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.MonthlyStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.MonthlyStatsQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMonthlyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyStats'
type MockRepository_GetMonthlyStats_Call struct {
	*mock.Call
}

// GetMonthlyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - q finance.MonthlyStatsQuery
func (_e *MockRepository_Expecter) GetMonthlyStats(ctx interface{}, q interface{}) *MockRepository_GetMonthlyStats_Call {
	return &MockRepository_GetMonthlyStats_Call{Call: _e.mock.On("GetMonthlyStats", ctx, q)}
}

func (_c *MockRepository_GetMonthlyStats_Call) Run(run func(ctx context.Context, q finance.MonthlyStatsQuery)) *MockRepository_GetMonthlyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.MonthlyStatsQuery))
	})
	return _c
}

func (_c *MockRepository_GetMonthlyStats_Call) Return(_a0 []finance.MonthlyStat, _a1 error) *MockRepository_GetMonthlyStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMonthlyStats_Call) RunAndReturn(run func(context.Context, finance.MonthlyStatsQuery) ([]finance.MonthlyStat, error)) *MockRepository_GetMonthlyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyTotals provides a mock function with given fields: ctx, since
func (_m *MockRepository) GetMonthlyTotals(ctx context.Context, since time.Time) (decimal.Decimal, decimal.Decimal, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyTotals")
	}

	var r0 decimal.Decimal
	var r1 decimal.Decimal
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (decimal.Decimal, decimal.Decimal, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) decimal.Decimal); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) decimal.Decimal); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Get(1).(decimal.Decimal)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time) error); ok {
		r2 = rf(ctx, since)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetMonthlyTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyTotals'
type MockRepository_GetMonthlyTotals_Call struct {
	*mock.Call
}

// GetMonthlyTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockRepository_Expecter) GetMonthlyTotals(ctx interface{}, since interface{}) *MockRepository_GetMonthlyTotals_Call {
	return &MockRepository_GetMonthlyTotals_Call{Call: _e.mock.On("GetMonthlyTotals", ctx, since)}
}

func (_c *MockRepository_GetMonthlyTotals_Call) Run(run func(ctx context.Context, since time.Time)) *MockRepository_GetMonthlyTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetMonthlyTotals_Call) Return(_a0 decimal.Decimal, _a1 decimal.Decimal, _a2 error) *MockRepository_GetMonthlyTotals_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetMonthlyTotals_Call) RunAndReturn(run func(context.Context, time.Time) (decimal.Decimal, decimal.Decimal, error)) *MockRepository_GetMonthlyTotals_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetWorthSeries provides a mock function with given fields: ctx, q
func (_m *MockRepository) GetNetWorthSeries(ctx context.Context, q finance.NetWorthQuery) ([]finance.NetWorthPoint, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetNetWorthSeries")
	}

	var r0 []finance.NetWorthPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.NetWorthQuery) ([]finance.NetWorthPoint, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.NetWorthQuery) []finance.NetWorthPoint); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.NetWorthPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.NetWorthQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetNetWorthSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetWorthSeries'
type MockRepository_GetNetWorthSeries_Call struct {
	*mock.Call
}

// GetNetWorthSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - q finance.NetWorthQuery
func (_e *MockRepository_Expecter) GetNetWorthSeries(ctx interface{}, q interface{}) *MockRepository_GetNetWorthSeries_Call {
	return &MockRepository_GetNetWorthSeries_Call{Call: _e.mock.On("GetNetWorthSeries", ctx, q)}
}

func (_c *MockRepository_GetNetWorthSeries_Call) Run(run func(ctx context.Context, q finance.NetWorthQuery)) *MockRepository_GetNetWorthSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.NetWorthQuery))
	})
	return _c
}

func (_c *MockRepository_GetNetWorthSeries_Call) Return(_a0 []finance.NetWorthPoint, _a1 error) *MockRepository_GetNetWorthSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetNetWorthSeries_Call) RunAndReturn(run func(context.Context, finance.NetWorthQuery) ([]finance.NetWorthPoint, error)) *MockRepository_GetNetWorthSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetTransaction(ctx context.Context, id int32) (finance.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 finance.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (finance.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) finance.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(finance.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockRepository_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetTransaction(ctx interface{}, id interface{}) *MockRepository_GetTransaction_Call {
	return &MockRepository_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, id)}
}

func (_c *MockRepository_GetTransaction_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetTransaction_Call) Return(_a0 finance.Transaction, _a1 error) *MockRepository_GetTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTransaction_Call) RunAndReturn(run func(context.Context, int32) (finance.Transaction, error)) *MockRepository_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx
func (_m *MockRepository) ListAccounts(ctx context.Context) ([]finance.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []finance.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]finance.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []finance.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockRepository_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListAccounts(ctx interface{}) *MockRepository_ListAccounts_Call {
	return &MockRepository_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx)}
}

func (_c *MockRepository_ListAccounts_Call) Run(run func(ctx context.Context)) *MockRepository_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListAccounts_Call) Return(_a0 []finance.Account, _a1 error) *MockRepository_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAccounts_Call) RunAndReturn(run func(context.Context) ([]finance.Account, error)) *MockRepository_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function with given fields: ctx
func (_m *MockRepository) ListCategories(ctx context.Context) ([]finance.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []finance.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]finance.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []finance.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListCategories(ctx interface{}) *MockRepository_ListCategories_Call {
	return &MockRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *MockRepository_ListCategories_Call) Run(run func(ctx context.Context)) *MockRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListCategories_Call) Return(_a0 []finance.Category, _a1 error) *MockRepository_ListCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCategories_Call) RunAndReturn(run func(context.Context) ([]finance.Category, error)) *MockRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentTransactions provides a mock function with given fields: ctx, since
func (_m *MockRepository) ListRecentTransactions(ctx context.Context, since time.Time) ([]finance.OverviewTransaction, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentTransactions")
	}

	var r0 []finance.OverviewTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]finance.OverviewTransaction, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []finance.OverviewTransaction); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.OverviewTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRecentTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentTransactions'
type MockRepository_ListRecentTransactions_Call struct {
	*mock.Call
}

// ListRecentTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockRepository_Expecter) ListRecentTransactions(ctx interface{}, since interface{}) *MockRepository_ListRecentTransactions_Call {
	return &MockRepository_ListRecentTransactions_Call{Call: _e.mock.On("ListRecentTransactions", ctx, since)}
}

func (_c *MockRepository_ListRecentTransactions_Call) Run(run func(ctx context.Context, since time.Time)) *MockRepository_ListRecentTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListRecentTransactions_Call) Return(_a0 []finance.OverviewTransaction, _a1 error) *MockRepository_ListRecentTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRecentTransactions_Call) RunAndReturn(run func(context.Context, time.Time) ([]finance.OverviewTransaction, error)) *MockRepository_ListRecentTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function with given fields: ctx, q
func (_m *MockRepository) ListTransactions(ctx context.Context, q finance.ListTransactionsQuery) ([]finance.Transaction, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []finance.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.ListTransactionsQuery) ([]finance.Transaction, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.ListTransactionsQuery) []finance.Transaction); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]finance.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.ListTransactionsQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockRepository_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - q finance.ListTransactionsQuery
func (_e *MockRepository_Expecter) ListTransactions(ctx interface{}, q interface{}) *MockRepository_ListTransactions_Call {
	return &MockRepository_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, q)}
}

func (_c *MockRepository_ListTransactions_Call) Run(run func(ctx context.Context, q finance.ListTransactionsQuery)) *MockRepository_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.ListTransactionsQuery))
	})
	return _c
}

func (_c *MockRepository_ListTransactions_Call) Return(_a0 []finance.Transaction, _a1 error) *MockRepository_ListTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListTransactions_Call) RunAndReturn(run func(context.Context, finance.ListTransactionsQuery) ([]finance.Transaction, error)) *MockRepository_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateAccount(ctx context.Context, req finance.UpdateAccountRequest) (finance.Account, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 finance.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateAccountRequest) (finance.Account, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateAccountRequest) finance.Account); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.UpdateAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockRepository_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.UpdateAccountRequest
func (_e *MockRepository_Expecter) UpdateAccount(ctx interface{}, req interface{}) *MockRepository_UpdateAccount_Call {
	return &MockRepository_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, req)}
}

func (_c *MockRepository_UpdateAccount_Call) Run(run func(ctx context.Context, req finance.UpdateAccountRequest)) *MockRepository_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.UpdateAccountRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) Return(_a0 finance.Account, _a1 error) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateAccount_Call) RunAndReturn(run func(context.Context, finance.UpdateAccountRequest) (finance.Account, error)) *MockRepository_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateCategory(ctx context.Context, req finance.UpdateCategoryRequest) (finance.Category, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 finance.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateCategoryRequest) (finance.Category, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateCategoryRequest) finance.Category); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.UpdateCategoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockRepository_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.UpdateCategoryRequest
func (_e *MockRepository_Expecter) UpdateCategory(ctx interface{}, req interface{}) *MockRepository_UpdateCategory_Call {
	return &MockRepository_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, req)}
}

func (_c *MockRepository_UpdateCategory_Call) Run(run func(ctx context.Context, req finance.UpdateCategoryRequest)) *MockRepository_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.UpdateCategoryRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateCategory_Call) Return(_a0 finance.Category, _a1 error) *MockRepository_UpdateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateCategory_Call) RunAndReturn(run func(context.Context, finance.UpdateCategoryRequest) (finance.Category, error)) *MockRepository_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateTransaction(ctx context.Context, req finance.UpdateTransactionRequest) (finance.Transaction, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 finance.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateTransactionRequest) (finance.Transaction, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finance.UpdateTransactionRequest) finance.Transaction); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(finance.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, finance.UpdateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type MockRepository_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req finance.UpdateTransactionRequest
func (_e *MockRepository_Expecter) UpdateTransaction(ctx interface{}, req interface{}) *MockRepository_UpdateTransaction_Call {
	return &MockRepository_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, req)}
}

func (_c *MockRepository_UpdateTransaction_Call) Run(run func(ctx context.Context, req finance.UpdateTransactionRequest)) *MockRepository_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finance.UpdateTransactionRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateTransaction_Call) Return(_a0 finance.Transaction, _a1 error) *MockRepository_UpdateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateTransaction_Call) RunAndReturn(run func(context.Context, finance.UpdateTransactionRequest) (finance.Transaction, error)) *MockRepository_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
