// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	calendar "gv-api/internal/calendar"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ClearAccountSyncTokens provides a mock function with given fields: ctx, accountID
func (_m *MockRepository) ClearAccountSyncTokens(ctx context.Context, accountID int32) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ClearAccountSyncTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ClearAccountSyncTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAccountSyncTokens'
type MockRepository_ClearAccountSyncTokens_Call struct {
	*mock.Call
}

// ClearAccountSyncTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int32
func (_e *MockRepository_Expecter) ClearAccountSyncTokens(ctx interface{}, accountID interface{}) *MockRepository_ClearAccountSyncTokens_Call {
	return &MockRepository_ClearAccountSyncTokens_Call{Call: _e.mock.On("ClearAccountSyncTokens", ctx, accountID)}
}

func (_c *MockRepository_ClearAccountSyncTokens_Call) Run(run func(ctx context.Context, accountID int32)) *MockRepository_ClearAccountSyncTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_ClearAccountSyncTokens_Call) Return(_a0 error) *MockRepository_ClearAccountSyncTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ClearAccountSyncTokens_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_ClearAccountSyncTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCalendarSyncToken provides a mock function with given fields: ctx, id
func (_m *MockRepository) ClearCalendarSyncToken(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearCalendarSyncToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ClearCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCalendarSyncToken'
type MockRepository_ClearCalendarSyncToken_Call struct {
	*mock.Call
}

// ClearCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) ClearCalendarSyncToken(ctx interface{}, id interface{}) *MockRepository_ClearCalendarSyncToken_Call {
	return &MockRepository_ClearCalendarSyncToken_Call{Call: _e.mock.On("ClearCalendarSyncToken", ctx, id)}
}

func (_c *MockRepository_ClearCalendarSyncToken_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_ClearCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_ClearCalendarSyncToken_Call) Return(_a0 error) *MockRepository_ClearCalendarSyncToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ClearCalendarSyncToken_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_ClearCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCalendarWatch provides a mock function with given fields: ctx, id
func (_m *MockRepository) ClearCalendarWatch(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearCalendarWatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ClearCalendarWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCalendarWatch'
type MockRepository_ClearCalendarWatch_Call struct {
	*mock.Call
}

// ClearCalendarWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) ClearCalendarWatch(ctx interface{}, id interface{}) *MockRepository_ClearCalendarWatch_Call {
	return &MockRepository_ClearCalendarWatch_Call{Call: _e.mock.On("ClearCalendarWatch", ctx, id)}
}

func (_c *MockRepository_ClearCalendarWatch_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_ClearCalendarWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_ClearCalendarWatch_Call) Return(_a0 error) *MockRepository_ClearCalendarWatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ClearCalendarWatch_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_ClearCalendarWatch_Call {
	_c.Call.Return(run)
	return _c
}

// CountEvents provides a mock function with given fields: ctx, calendarID
func (_m *MockRepository) CountEvents(ctx context.Context, calendarID int32) (int64, error) {
	ret := _m.Called(ctx, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for CountEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, calendarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, calendarID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, calendarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEvents'
type MockRepository_CountEvents_Call struct {
	*mock.Call
}

// CountEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
func (_e *MockRepository_Expecter) CountEvents(ctx interface{}, calendarID interface{}) *MockRepository_CountEvents_Call {
	return &MockRepository_CountEvents_Call{Call: _e.mock.On("CountEvents", ctx, calendarID)}
}

func (_c *MockRepository_CountEvents_Call) Run(run func(ctx context.Context, calendarID int32)) *MockRepository_CountEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_CountEvents_Call) Return(_a0 int64, _a1 error) *MockRepository_CountEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountEvents_Call) RunAndReturn(run func(context.Context, int32) (int64, error)) *MockRepository_CountEvents_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSyncRun provides a mock function with given fields: ctx, calendarID, trigger, kind
func (_m *MockRepository) CreateSyncRun(ctx context.Context, calendarID int32, trigger string, kind string) (int32, error) {
	ret := _m.Called(ctx, calendarID, trigger, kind)

	if len(ret) == 0 {
		panic("no return value specified for CreateSyncRun")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string) (int32, error)); ok {
		return rf(ctx, calendarID, trigger, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string) int32); ok {
		r0 = rf(ctx, calendarID, trigger, kind)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, string) error); ok {
		r1 = rf(ctx, calendarID, trigger, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateSyncRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSyncRun'
type MockRepository_CreateSyncRun_Call struct {
	*mock.Call
}

// CreateSyncRun is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
//   - trigger string
//   - kind string
func (_e *MockRepository_Expecter) CreateSyncRun(ctx interface{}, calendarID interface{}, trigger interface{}, kind interface{}) *MockRepository_CreateSyncRun_Call {
	return &MockRepository_CreateSyncRun_Call{Call: _e.mock.On("CreateSyncRun", ctx, calendarID, trigger, kind)}
}

func (_c *MockRepository_CreateSyncRun_Call) Run(run func(ctx context.Context, calendarID int32, trigger string, kind string)) *MockRepository_CreateSyncRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_CreateSyncRun_Call) Return(_a0 int32, _a1 error) *MockRepository_CreateSyncRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateSyncRun_Call) RunAndReturn(run func(context.Context, int32, string, string) (int32, error)) *MockRepository_CreateSyncRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteAccount(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockRepository_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteAccount(ctx interface{}, id interface{}) *MockRepository_DeleteAccount_Call {
	return &MockRepository_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *MockRepository_DeleteAccount_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) Return(_a0 error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAccount_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteEvent(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockRepository_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteEvent(ctx interface{}, id interface{}) *MockRepository_DeleteEvent_Call {
	return &MockRepository_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, id)}
}

func (_c *MockRepository_DeleteEvent_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteEvent_Call) Return(_a0 error) *MockRepository_DeleteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteEvent_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEventByGoogleID provides a mock function with given fields: ctx, calendarID, googleEventID
func (_m *MockRepository) DeleteEventByGoogleID(ctx context.Context, calendarID int32, googleEventID string) error {
	ret := _m.Called(ctx, calendarID, googleEventID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEventByGoogleID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, calendarID, googleEventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteEventByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEventByGoogleID'
type MockRepository_DeleteEventByGoogleID_Call struct {
	*mock.Call
}

// DeleteEventByGoogleID is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
//   - googleEventID string
func (_e *MockRepository_Expecter) DeleteEventByGoogleID(ctx interface{}, calendarID interface{}, googleEventID interface{}) *MockRepository_DeleteEventByGoogleID_Call {
	return &MockRepository_DeleteEventByGoogleID_Call{Call: _e.mock.On("DeleteEventByGoogleID", ctx, calendarID, googleEventID)}
}

func (_c *MockRepository_DeleteEventByGoogleID_Call) Run(run func(ctx context.Context, calendarID int32, googleEventID string)) *MockRepository_DeleteEventByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteEventByGoogleID_Call) Return(_a0 error) *MockRepository_DeleteEventByGoogleID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteEventByGoogleID_Call) RunAndReturn(run func(context.Context, int32, string) error) *MockRepository_DeleteEventByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEventsForCalendar provides a mock function with given fields: ctx, calendarID
func (_m *MockRepository) DeleteEventsForCalendar(ctx context.Context, calendarID int32) (int64, error) {
	ret := _m.Called(ctx, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEventsForCalendar")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, calendarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, calendarID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, calendarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DeleteEventsForCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEventsForCalendar'
type MockRepository_DeleteEventsForCalendar_Call struct {
	*mock.Call
}

// DeleteEventsForCalendar is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
func (_e *MockRepository_Expecter) DeleteEventsForCalendar(ctx interface{}, calendarID interface{}) *MockRepository_DeleteEventsForCalendar_Call {
	return &MockRepository_DeleteEventsForCalendar_Call{Call: _e.mock.On("DeleteEventsForCalendar", ctx, calendarID)}
}

func (_c *MockRepository_DeleteEventsForCalendar_Call) Run(run func(ctx context.Context, calendarID int32)) *MockRepository_DeleteEventsForCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteEventsForCalendar_Call) Return(_a0 int64, _a1 error) *MockRepository_DeleteEventsForCalendar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DeleteEventsForCalendar_Call) RunAndReturn(run func(context.Context, int32) (int64, error)) *MockRepository_DeleteEventsForCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// FinishSyncRun provides a mock function with given fields: ctx, id, pages, upserted, deleted, runError
func (_m *MockRepository) FinishSyncRun(ctx context.Context, id int32, pages int32, upserted int32, deleted int32, runError *string) error {
	ret := _m.Called(ctx, id, pages, upserted, deleted, runError)

	if len(ret) == 0 {
		panic("no return value specified for FinishSyncRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32, int32, *string) error); ok {
		r0 = rf(ctx, id, pages, upserted, deleted, runError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_FinishSyncRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishSyncRun'
type MockRepository_FinishSyncRun_Call struct {
	*mock.Call
}

// FinishSyncRun is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - pages int32
//   - upserted int32
//   - deleted int32
//   - runError *string
func (_e *MockRepository_Expecter) FinishSyncRun(ctx interface{}, id interface{}, pages interface{}, upserted interface{}, deleted interface{}, runError interface{}) *MockRepository_FinishSyncRun_Call {
	return &MockRepository_FinishSyncRun_Call{Call: _e.mock.On("FinishSyncRun", ctx, id, pages, upserted, deleted, runError)}
}

func (_c *MockRepository_FinishSyncRun_Call) Run(run func(ctx context.Context, id int32, pages int32, upserted int32, deleted int32, runError *string)) *MockRepository_FinishSyncRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(int32), args[4].(int32), args[5].(*string))
	})
	return _c
}

func (_c *MockRepository_FinishSyncRun_Call) Return(_a0 error) *MockRepository_FinishSyncRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_FinishSyncRun_Call) RunAndReturn(run func(context.Context, int32, int32, int32, int32, *string) error) *MockRepository_FinishSyncRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetAccount(ctx context.Context, id int32) (calendar.AccountRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 calendar.AccountRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (calendar.AccountRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) calendar.AccountRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(calendar.AccountRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetAccount(ctx interface{}, id interface{}) *MockRepository_GetAccount_Call {
	return &MockRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *MockRepository_GetAccount_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetAccount_Call) Return(_a0 calendar.AccountRecord, _a1 error) *MockRepository_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAccount_Call) RunAndReturn(run func(context.Context, int32) (calendar.AccountRecord, error)) *MockRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetCalendar provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetCalendar(ctx context.Context, id int32) (calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCalendar")
	}

	var r0 calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (calendar.CalendarRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) calendar.CalendarRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(calendar.CalendarRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCalendar'
type MockRepository_GetCalendar_Call struct {
	*mock.Call
}

// GetCalendar is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetCalendar(ctx interface{}, id interface{}) *MockRepository_GetCalendar_Call {
	return &MockRepository_GetCalendar_Call{Call: _e.mock.On("GetCalendar", ctx, id)}
}

func (_c *MockRepository_GetCalendar_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetCalendar_Call) Return(_a0 calendar.CalendarRecord, _a1 error) *MockRepository_GetCalendar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCalendar_Call) RunAndReturn(run func(context.Context, int32) (calendar.CalendarRecord, error)) *MockRepository_GetCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// GetCalendarByChannel provides a mock function with given fields: ctx, channelID
func (_m *MockRepository) GetCalendarByChannel(ctx context.Context, channelID string) (calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetCalendarByChannel")
	}

	var r0 calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (calendar.CalendarRecord, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) calendar.CalendarRecord); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Get(0).(calendar.CalendarRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCalendarByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCalendarByChannel'
type MockRepository_GetCalendarByChannel_Call struct {
	*mock.Call
}

// GetCalendarByChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
func (_e *MockRepository_Expecter) GetCalendarByChannel(ctx interface{}, channelID interface{}) *MockRepository_GetCalendarByChannel_Call {
	return &MockRepository_GetCalendarByChannel_Call{Call: _e.mock.On("GetCalendarByChannel", ctx, channelID)}
}

func (_c *MockRepository_GetCalendarByChannel_Call) Run(run func(ctx context.Context, channelID string)) *MockRepository_GetCalendarByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetCalendarByChannel_Call) Return(_a0 calendar.CalendarRecord, _a1 error) *MockRepository_GetCalendarByChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCalendarByChannel_Call) RunAndReturn(run func(context.Context, string) (calendar.CalendarRecord, error)) *MockRepository_GetCalendarByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetEvent(ctx context.Context, id int32) (calendar.EventRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (calendar.EventRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) calendar.EventRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(calendar.EventRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockRepository_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetEvent(ctx interface{}, id interface{}) *MockRepository_GetEvent_Call {
	return &MockRepository_GetEvent_Call{Call: _e.mock.On("GetEvent", ctx, id)}
}

func (_c *MockRepository_GetEvent_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetEvent_Call) Return(_a0 calendar.EventRecord, _a1 error) *MockRepository_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetEvent_Call) RunAndReturn(run func(context.Context, int32) (calendar.EventRecord, error)) *MockRepository_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventByGoogleID provides a mock function with given fields: ctx, calendarID, googleEventID
func (_m *MockRepository) GetEventByGoogleID(ctx context.Context, calendarID int32, googleEventID string) (calendar.EventRecord, error) {
	ret := _m.Called(ctx, calendarID, googleEventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByGoogleID")
	}

	var r0 calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) (calendar.EventRecord, error)); ok {
		return rf(ctx, calendarID, googleEventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) calendar.EventRecord); ok {
		r0 = rf(ctx, calendarID, googleEventID)
	} else {
		r0 = ret.Get(0).(calendar.EventRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = rf(ctx, calendarID, googleEventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetEventByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventByGoogleID'
type MockRepository_GetEventByGoogleID_Call struct {
	*mock.Call
}

// GetEventByGoogleID is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
//   - googleEventID string
func (_e *MockRepository_Expecter) GetEventByGoogleID(ctx interface{}, calendarID interface{}, googleEventID interface{}) *MockRepository_GetEventByGoogleID_Call {
	return &MockRepository_GetEventByGoogleID_Call{Call: _e.mock.On("GetEventByGoogleID", ctx, calendarID, googleEventID)}
}

func (_c *MockRepository_GetEventByGoogleID_Call) Run(run func(ctx context.Context, calendarID int32, googleEventID string)) *MockRepository_GetEventByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetEventByGoogleID_Call) Return(_a0 calendar.EventRecord, _a1 error) *MockRepository_GetEventByGoogleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetEventByGoogleID_Call) RunAndReturn(run func(context.Context, int32, string) (calendar.EventRecord, error)) *MockRepository_GetEventByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// LinkEventMasters provides a mock function with given fields: ctx, calendarID
func (_m *MockRepository) LinkEventMasters(ctx context.Context, calendarID int32) error {
	ret := _m.Called(ctx, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for LinkEventMasters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, calendarID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_LinkEventMasters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkEventMasters'
type MockRepository_LinkEventMasters_Call struct {
	*mock.Call
}

// LinkEventMasters is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarID int32
func (_e *MockRepository_Expecter) LinkEventMasters(ctx interface{}, calendarID interface{}) *MockRepository_LinkEventMasters_Call {
	return &MockRepository_LinkEventMasters_Call{Call: _e.mock.On("LinkEventMasters", ctx, calendarID)}
}

func (_c *MockRepository_LinkEventMasters_Call) Run(run func(ctx context.Context, calendarID int32)) *MockRepository_LinkEventMasters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_LinkEventMasters_Call) Return(_a0 error) *MockRepository_LinkEventMasters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_LinkEventMasters_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_LinkEventMasters_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx
func (_m *MockRepository) ListAccounts(ctx context.Context) ([]calendar.AccountRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []calendar.AccountRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]calendar.AccountRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []calendar.AccountRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.AccountRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockRepository_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListAccounts(ctx interface{}) *MockRepository_ListAccounts_Call {
	return &MockRepository_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx)}
}

func (_c *MockRepository_ListAccounts_Call) Run(run func(ctx context.Context)) *MockRepository_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListAccounts_Call) Return(_a0 []calendar.AccountRecord, _a1 error) *MockRepository_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListAccounts_Call) RunAndReturn(run func(context.Context) ([]calendar.AccountRecord, error)) *MockRepository_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListCalendars provides a mock function with given fields: ctx
func (_m *MockRepository) ListCalendars(ctx context.Context) ([]calendar.CalendarView, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCalendars")
	}

	var r0 []calendar.CalendarView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]calendar.CalendarView, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []calendar.CalendarView); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.CalendarView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCalendars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCalendars'
type MockRepository_ListCalendars_Call struct {
	*mock.Call
}

// ListCalendars is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListCalendars(ctx interface{}) *MockRepository_ListCalendars_Call {
	return &MockRepository_ListCalendars_Call{Call: _e.mock.On("ListCalendars", ctx)}
}

func (_c *MockRepository_ListCalendars_Call) Run(run func(ctx context.Context)) *MockRepository_ListCalendars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListCalendars_Call) Return(_a0 []calendar.CalendarView, _a1 error) *MockRepository_ListCalendars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCalendars_Call) RunAndReturn(run func(context.Context) ([]calendar.CalendarView, error)) *MockRepository_ListCalendars_Call {
	_c.Call.Return(run)
	return _c
}

// ListCalendarsByAccount provides a mock function with given fields: ctx, accountID
func (_m *MockRepository) ListCalendarsByAccount(ctx context.Context, accountID int32) ([]calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ListCalendarsByAccount")
	}

	var r0 []calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]calendar.CalendarRecord, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []calendar.CalendarRecord); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.CalendarRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCalendarsByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCalendarsByAccount'
type MockRepository_ListCalendarsByAccount_Call struct {
	*mock.Call
}

// ListCalendarsByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int32
func (_e *MockRepository_Expecter) ListCalendarsByAccount(ctx interface{}, accountID interface{}) *MockRepository_ListCalendarsByAccount_Call {
	return &MockRepository_ListCalendarsByAccount_Call{Call: _e.mock.On("ListCalendarsByAccount", ctx, accountID)}
}

func (_c *MockRepository_ListCalendarsByAccount_Call) Run(run func(ctx context.Context, accountID int32)) *MockRepository_ListCalendarsByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_ListCalendarsByAccount_Call) Return(_a0 []calendar.CalendarRecord, _a1 error) *MockRepository_ListCalendarsByAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCalendarsByAccount_Call) RunAndReturn(run func(context.Context, int32) ([]calendar.CalendarRecord, error)) *MockRepository_ListCalendarsByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListCalendarsNeedingWatch provides a mock function with given fields: ctx, renewBefore
func (_m *MockRepository) ListCalendarsNeedingWatch(ctx context.Context, renewBefore time.Time) ([]calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, renewBefore)

	if len(ret) == 0 {
		panic("no return value specified for ListCalendarsNeedingWatch")
	}

	var r0 []calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]calendar.CalendarRecord, error)); ok {
		return rf(ctx, renewBefore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []calendar.CalendarRecord); ok {
		r0 = rf(ctx, renewBefore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.CalendarRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, renewBefore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListCalendarsNeedingWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCalendarsNeedingWatch'
type MockRepository_ListCalendarsNeedingWatch_Call struct {
	*mock.Call
}

// ListCalendarsNeedingWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - renewBefore time.Time
func (_e *MockRepository_Expecter) ListCalendarsNeedingWatch(ctx interface{}, renewBefore interface{}) *MockRepository_ListCalendarsNeedingWatch_Call {
	return &MockRepository_ListCalendarsNeedingWatch_Call{Call: _e.mock.On("ListCalendarsNeedingWatch", ctx, renewBefore)}
}

func (_c *MockRepository_ListCalendarsNeedingWatch_Call) Run(run func(ctx context.Context, renewBefore time.Time)) *MockRepository_ListCalendarsNeedingWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListCalendarsNeedingWatch_Call) Return(_a0 []calendar.CalendarRecord, _a1 error) *MockRepository_ListCalendarsNeedingWatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListCalendarsNeedingWatch_Call) RunAndReturn(run func(context.Context, time.Time) ([]calendar.CalendarRecord, error)) *MockRepository_ListCalendarsNeedingWatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListEventExceptions provides a mock function with given fields: ctx, masterIDs
func (_m *MockRepository) ListEventExceptions(ctx context.Context, masterIDs []int32) ([]calendar.EventRecord, error) {
	ret := _m.Called(ctx, masterIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListEventExceptions")
	}

	var r0 []calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int32) ([]calendar.EventRecord, error)); ok {
		return rf(ctx, masterIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int32) []calendar.EventRecord); ok {
		r0 = rf(ctx, masterIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.EventRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int32) error); ok {
		r1 = rf(ctx, masterIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListEventExceptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEventExceptions'
type MockRepository_ListEventExceptions_Call struct {
	*mock.Call
}

// ListEventExceptions is a helper method to define mock.On call
//   - ctx context.Context
//   - masterIDs []int32
func (_e *MockRepository_Expecter) ListEventExceptions(ctx interface{}, masterIDs interface{}) *MockRepository_ListEventExceptions_Call {
	return &MockRepository_ListEventExceptions_Call{Call: _e.mock.On("ListEventExceptions", ctx, masterIDs)}
}

func (_c *MockRepository_ListEventExceptions_Call) Run(run func(ctx context.Context, masterIDs []int32)) *MockRepository_ListEventExceptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int32))
	})
	return _c
}

func (_c *MockRepository_ListEventExceptions_Call) Return(_a0 []calendar.EventRecord, _a1 error) *MockRepository_ListEventExceptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListEventExceptions_Call) RunAndReturn(run func(context.Context, []int32) ([]calendar.EventRecord, error)) *MockRepository_ListEventExceptions_Call {
	_c.Call.Return(run)
	return _c
}

// ListEventsInRange provides a mock function with given fields: ctx, calendarIDs, from, to
func (_m *MockRepository) ListEventsInRange(ctx context.Context, calendarIDs []int32, from time.Time, to time.Time) ([]calendar.EventRecord, error) {
	ret := _m.Called(ctx, calendarIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListEventsInRange")
	}

	var r0 []calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time, time.Time) ([]calendar.EventRecord, error)); ok {
		return rf(ctx, calendarIDs, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time, time.Time) []calendar.EventRecord); ok {
		r0 = rf(ctx, calendarIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.EventRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int32, time.Time, time.Time) error); ok {
		r1 = rf(ctx, calendarIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListEventsInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEventsInRange'
type MockRepository_ListEventsInRange_Call struct {
	*mock.Call
}

// ListEventsInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarIDs []int32
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ListEventsInRange(ctx interface{}, calendarIDs interface{}, from interface{}, to interface{}) *MockRepository_ListEventsInRange_Call {
	return &MockRepository_ListEventsInRange_Call{Call: _e.mock.On("ListEventsInRange", ctx, calendarIDs, from, to)}
}

func (_c *MockRepository_ListEventsInRange_Call) Run(run func(ctx context.Context, calendarIDs []int32, from time.Time, to time.Time)) *MockRepository_ListEventsInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int32), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListEventsInRange_Call) Return(_a0 []calendar.EventRecord, _a1 error) *MockRepository_ListEventsInRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListEventsInRange_Call) RunAndReturn(run func(context.Context, []int32, time.Time, time.Time) ([]calendar.EventRecord, error)) *MockRepository_ListEventsInRange_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrphanOverridesInRange provides a mock function with given fields: ctx, calendarIDs, from, to
func (_m *MockRepository) ListOrphanOverridesInRange(ctx context.Context, calendarIDs []int32, from time.Time, to time.Time) ([]calendar.EventRecord, error) {
	ret := _m.Called(ctx, calendarIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListOrphanOverridesInRange")
	}

	var r0 []calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time, time.Time) ([]calendar.EventRecord, error)); ok {
		return rf(ctx, calendarIDs, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time, time.Time) []calendar.EventRecord); ok {
		r0 = rf(ctx, calendarIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.EventRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int32, time.Time, time.Time) error); ok {
		r1 = rf(ctx, calendarIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListOrphanOverridesInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrphanOverridesInRange'
type MockRepository_ListOrphanOverridesInRange_Call struct {
	*mock.Call
}

// ListOrphanOverridesInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarIDs []int32
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ListOrphanOverridesInRange(ctx interface{}, calendarIDs interface{}, from interface{}, to interface{}) *MockRepository_ListOrphanOverridesInRange_Call {
	return &MockRepository_ListOrphanOverridesInRange_Call{Call: _e.mock.On("ListOrphanOverridesInRange", ctx, calendarIDs, from, to)}
}

func (_c *MockRepository_ListOrphanOverridesInRange_Call) Run(run func(ctx context.Context, calendarIDs []int32, from time.Time, to time.Time)) *MockRepository_ListOrphanOverridesInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int32), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListOrphanOverridesInRange_Call) Return(_a0 []calendar.EventRecord, _a1 error) *MockRepository_ListOrphanOverridesInRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListOrphanOverridesInRange_Call) RunAndReturn(run func(context.Context, []int32, time.Time, time.Time) ([]calendar.EventRecord, error)) *MockRepository_ListOrphanOverridesInRange_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentSyncRuns provides a mock function with given fields: ctx, limit
func (_m *MockRepository) ListRecentSyncRuns(ctx context.Context, limit int32) ([]calendar.SyncRun, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentSyncRuns")
	}

	var r0 []calendar.SyncRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]calendar.SyncRun, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []calendar.SyncRun); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.SyncRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRecentSyncRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentSyncRuns'
type MockRepository_ListRecentSyncRuns_Call struct {
	*mock.Call
}

// ListRecentSyncRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
func (_e *MockRepository_Expecter) ListRecentSyncRuns(ctx interface{}, limit interface{}) *MockRepository_ListRecentSyncRuns_Call {
	return &MockRepository_ListRecentSyncRuns_Call{Call: _e.mock.On("ListRecentSyncRuns", ctx, limit)}
}

func (_c *MockRepository_ListRecentSyncRuns_Call) Run(run func(ctx context.Context, limit int32)) *MockRepository_ListRecentSyncRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_ListRecentSyncRuns_Call) Return(_a0 []calendar.SyncRun, _a1 error) *MockRepository_ListRecentSyncRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRecentSyncRuns_Call) RunAndReturn(run func(context.Context, int32) ([]calendar.SyncRun, error)) *MockRepository_ListRecentSyncRuns_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecurringMasters provides a mock function with given fields: ctx, calendarIDs, to
func (_m *MockRepository) ListRecurringMasters(ctx context.Context, calendarIDs []int32, to time.Time) ([]calendar.EventRecord, error) {
	ret := _m.Called(ctx, calendarIDs, to)

	if len(ret) == 0 {
		panic("no return value specified for ListRecurringMasters")
	}

	var r0 []calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time) ([]calendar.EventRecord, error)); ok {
		return rf(ctx, calendarIDs, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int32, time.Time) []calendar.EventRecord); ok {
		r0 = rf(ctx, calendarIDs, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.EventRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int32, time.Time) error); ok {
		r1 = rf(ctx, calendarIDs, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRecurringMasters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecurringMasters'
type MockRepository_ListRecurringMasters_Call struct {
	*mock.Call
}

// ListRecurringMasters is a helper method to define mock.On call
//   - ctx context.Context
//   - calendarIDs []int32
//   - to time.Time
func (_e *MockRepository_Expecter) ListRecurringMasters(ctx interface{}, calendarIDs interface{}, to interface{}) *MockRepository_ListRecurringMasters_Call {
	return &MockRepository_ListRecurringMasters_Call{Call: _e.mock.On("ListRecurringMasters", ctx, calendarIDs, to)}
}

func (_c *MockRepository_ListRecurringMasters_Call) Run(run func(ctx context.Context, calendarIDs []int32, to time.Time)) *MockRepository_ListRecurringMasters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int32), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_ListRecurringMasters_Call) Return(_a0 []calendar.EventRecord, _a1 error) *MockRepository_ListRecurringMasters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRecurringMasters_Call) RunAndReturn(run func(context.Context, []int32, time.Time) ([]calendar.EventRecord, error)) *MockRepository_ListRecurringMasters_Call {
	_c.Call.Return(run)
	return _c
}

// ListSyncableCalendars provides a mock function with given fields: ctx
func (_m *MockRepository) ListSyncableCalendars(ctx context.Context) ([]calendar.CalendarRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSyncableCalendars")
	}

	var r0 []calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]calendar.CalendarRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []calendar.CalendarRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.CalendarRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListSyncableCalendars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSyncableCalendars'
type MockRepository_ListSyncableCalendars_Call struct {
	*mock.Call
}

// ListSyncableCalendars is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListSyncableCalendars(ctx interface{}) *MockRepository_ListSyncableCalendars_Call {
	return &MockRepository_ListSyncableCalendars_Call{Call: _e.mock.On("ListSyncableCalendars", ctx)}
}

func (_c *MockRepository_ListSyncableCalendars_Call) Run(run func(ctx context.Context)) *MockRepository_ListSyncableCalendars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListSyncableCalendars_Call) Return(_a0 []calendar.CalendarRecord, _a1 error) *MockRepository_ListSyncableCalendars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListSyncableCalendars_Call) RunAndReturn(run func(context.Context) ([]calendar.CalendarRecord, error)) *MockRepository_ListSyncableCalendars_Call {
	_c.Call.Return(run)
	return _c
}

// ListWatchedCalendars provides a mock function with given fields: ctx
func (_m *MockRepository) ListWatchedCalendars(ctx context.Context) ([]calendar.CalendarRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWatchedCalendars")
	}

	var r0 []calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]calendar.CalendarRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []calendar.CalendarRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.CalendarRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListWatchedCalendars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWatchedCalendars'
type MockRepository_ListWatchedCalendars_Call struct {
	*mock.Call
}

// ListWatchedCalendars is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListWatchedCalendars(ctx interface{}) *MockRepository_ListWatchedCalendars_Call {
	return &MockRepository_ListWatchedCalendars_Call{Call: _e.mock.On("ListWatchedCalendars", ctx)}
}

func (_c *MockRepository_ListWatchedCalendars_Call) Run(run func(ctx context.Context)) *MockRepository_ListWatchedCalendars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListWatchedCalendars_Call) Return(_a0 []calendar.CalendarRecord, _a1 error) *MockRepository_ListWatchedCalendars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListWatchedCalendars_Call) RunAndReturn(run func(context.Context) ([]calendar.CalendarRecord, error)) *MockRepository_ListWatchedCalendars_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCalendarsDeleted provides a mock function with given fields: ctx, accountID, seenIDs
func (_m *MockRepository) MarkCalendarsDeleted(ctx context.Context, accountID int32, seenIDs []string) error {
	ret := _m.Called(ctx, accountID, seenIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkCalendarsDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []string) error); ok {
		r0 = rf(ctx, accountID, seenIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkCalendarsDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCalendarsDeleted'
type MockRepository_MarkCalendarsDeleted_Call struct {
	*mock.Call
}

// MarkCalendarsDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int32
//   - seenIDs []string
func (_e *MockRepository_Expecter) MarkCalendarsDeleted(ctx interface{}, accountID interface{}, seenIDs interface{}) *MockRepository_MarkCalendarsDeleted_Call {
	return &MockRepository_MarkCalendarsDeleted_Call{Call: _e.mock.On("MarkCalendarsDeleted", ctx, accountID, seenIDs)}
}

func (_c *MockRepository_MarkCalendarsDeleted_Call) Run(run func(ctx context.Context, accountID int32, seenIDs []string)) *MockRepository_MarkCalendarsDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].([]string))
	})
	return _c
}

func (_c *MockRepository_MarkCalendarsDeleted_Call) Return(_a0 error) *MockRepository_MarkCalendarsDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkCalendarsDeleted_Call) RunAndReturn(run func(context.Context, int32, []string) error) *MockRepository_MarkCalendarsDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeCancelledEvents provides a mock function with given fields: ctx, olderThan
func (_m *MockRepository) PurgeCancelledEvents(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeCancelledEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_PurgeCancelledEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeCancelledEvents'
type MockRepository_PurgeCancelledEvents_Call struct {
	*mock.Call
}

// PurgeCancelledEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *MockRepository_Expecter) PurgeCancelledEvents(ctx interface{}, olderThan interface{}) *MockRepository_PurgeCancelledEvents_Call {
	return &MockRepository_PurgeCancelledEvents_Call{Call: _e.mock.On("PurgeCancelledEvents", ctx, olderThan)}
}

func (_c *MockRepository_PurgeCancelledEvents_Call) Run(run func(ctx context.Context, olderThan time.Time)) *MockRepository_PurgeCancelledEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRepository_PurgeCancelledEvents_Call) Return(_a0 int64, _a1 error) *MockRepository_PurgeCancelledEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_PurgeCancelledEvents_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockRepository_PurgeCancelledEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SetCalendarSyncError provides a mock function with given fields: ctx, id, syncError
func (_m *MockRepository) SetCalendarSyncError(ctx context.Context, id int32, syncError string) error {
	ret := _m.Called(ctx, id, syncError)

	if len(ret) == 0 {
		panic("no return value specified for SetCalendarSyncError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, id, syncError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetCalendarSyncError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCalendarSyncError'
type MockRepository_SetCalendarSyncError_Call struct {
	*mock.Call
}

// SetCalendarSyncError is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - syncError string
func (_e *MockRepository_Expecter) SetCalendarSyncError(ctx interface{}, id interface{}, syncError interface{}) *MockRepository_SetCalendarSyncError_Call {
	return &MockRepository_SetCalendarSyncError_Call{Call: _e.mock.On("SetCalendarSyncError", ctx, id, syncError)}
}

func (_c *MockRepository_SetCalendarSyncError_Call) Run(run func(ctx context.Context, id int32, syncError string)) *MockRepository_SetCalendarSyncError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetCalendarSyncError_Call) Return(_a0 error) *MockRepository_SetCalendarSyncError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetCalendarSyncError_Call) RunAndReturn(run func(context.Context, int32, string) error) *MockRepository_SetCalendarSyncError_Call {
	_c.Call.Return(run)
	return _c
}

// SetCalendarSyncToken provides a mock function with given fields: ctx, id, token, wasFull
func (_m *MockRepository) SetCalendarSyncToken(ctx context.Context, id int32, token string, wasFull bool) error {
	ret := _m.Called(ctx, id, token, wasFull)

	if len(ret) == 0 {
		panic("no return value specified for SetCalendarSyncToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, bool) error); ok {
		r0 = rf(ctx, id, token, wasFull)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCalendarSyncToken'
type MockRepository_SetCalendarSyncToken_Call struct {
	*mock.Call
}

// SetCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - token string
//   - wasFull bool
func (_e *MockRepository_Expecter) SetCalendarSyncToken(ctx interface{}, id interface{}, token interface{}, wasFull interface{}) *MockRepository_SetCalendarSyncToken_Call {
	return &MockRepository_SetCalendarSyncToken_Call{Call: _e.mock.On("SetCalendarSyncToken", ctx, id, token, wasFull)}
}

func (_c *MockRepository_SetCalendarSyncToken_Call) Run(run func(ctx context.Context, id int32, token string, wasFull bool)) *MockRepository_SetCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockRepository_SetCalendarSyncToken_Call) Return(_a0 error) *MockRepository_SetCalendarSyncToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetCalendarSyncToken_Call) RunAndReturn(run func(context.Context, int32, string, bool) error) *MockRepository_SetCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetCalendarWatch provides a mock function with given fields: ctx, id, w
func (_m *MockRepository) SetCalendarWatch(ctx context.Context, id int32, w calendar.WatchInfo) error {
	ret := _m.Called(ctx, id, w)

	if len(ret) == 0 {
		panic("no return value specified for SetCalendarWatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, calendar.WatchInfo) error); ok {
		r0 = rf(ctx, id, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetCalendarWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCalendarWatch'
type MockRepository_SetCalendarWatch_Call struct {
	*mock.Call
}

// SetCalendarWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - w calendar.WatchInfo
func (_e *MockRepository_Expecter) SetCalendarWatch(ctx interface{}, id interface{}, w interface{}) *MockRepository_SetCalendarWatch_Call {
	return &MockRepository_SetCalendarWatch_Call{Call: _e.mock.On("SetCalendarWatch", ctx, id, w)}
}

func (_c *MockRepository_SetCalendarWatch_Call) Run(run func(ctx context.Context, id int32, w calendar.WatchInfo)) *MockRepository_SetCalendarWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(calendar.WatchInfo))
	})
	return _c
}

func (_c *MockRepository_SetCalendarWatch_Call) Return(_a0 error) *MockRepository_SetCalendarWatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetCalendarWatch_Call) RunAndReturn(run func(context.Context, int32, calendar.WatchInfo) error) *MockRepository_SetCalendarWatch_Call {
	_c.Call.Return(run)
	return _c
}

// TouchAccountSync provides a mock function with given fields: ctx, id, syncError
func (_m *MockRepository) TouchAccountSync(ctx context.Context, id int32, syncError *string) error {
	ret := _m.Called(ctx, id, syncError)

	if len(ret) == 0 {
		panic("no return value specified for TouchAccountSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string) error); ok {
		r0 = rf(ctx, id, syncError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_TouchAccountSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchAccountSync'
type MockRepository_TouchAccountSync_Call struct {
	*mock.Call
}

// TouchAccountSync is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - syncError *string
func (_e *MockRepository_Expecter) TouchAccountSync(ctx interface{}, id interface{}, syncError interface{}) *MockRepository_TouchAccountSync_Call {
	return &MockRepository_TouchAccountSync_Call{Call: _e.mock.On("TouchAccountSync", ctx, id, syncError)}
}

func (_c *MockRepository_TouchAccountSync_Call) Run(run func(ctx context.Context, id int32, syncError *string)) *MockRepository_TouchAccountSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*string))
	})
	return _c
}

func (_c *MockRepository_TouchAccountSync_Call) Return(_a0 error) *MockRepository_TouchAccountSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_TouchAccountSync_Call) RunAndReturn(run func(context.Context, int32, *string) error) *MockRepository_TouchAccountSync_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountAccessToken provides a mock function with given fields: ctx, id, sealed, expiresAt
func (_m *MockRepository) UpdateAccountAccessToken(ctx context.Context, id int32, sealed []byte, expiresAt time.Time) error {
	ret := _m.Called(ctx, id, sealed, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []byte, time.Time) error); ok {
		r0 = rf(ctx, id, sealed, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateAccountAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountAccessToken'
type MockRepository_UpdateAccountAccessToken_Call struct {
	*mock.Call
}

// UpdateAccountAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - sealed []byte
//   - expiresAt time.Time
func (_e *MockRepository_Expecter) UpdateAccountAccessToken(ctx interface{}, id interface{}, sealed interface{}, expiresAt interface{}) *MockRepository_UpdateAccountAccessToken_Call {
	return &MockRepository_UpdateAccountAccessToken_Call{Call: _e.mock.On("UpdateAccountAccessToken", ctx, id, sealed, expiresAt)}
}

func (_c *MockRepository_UpdateAccountAccessToken_Call) Run(run func(ctx context.Context, id int32, sealed []byte, expiresAt time.Time)) *MockRepository_UpdateAccountAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].([]byte), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRepository_UpdateAccountAccessToken_Call) Return(_a0 error) *MockRepository_UpdateAccountAccessToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateAccountAccessToken_Call) RunAndReturn(run func(context.Context, int32, []byte, time.Time) error) *MockRepository_UpdateAccountAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountMeta provides a mock function with given fields: ctx, id, label, color
func (_m *MockRepository) UpdateAccountMeta(ctx context.Context, id int32, label *string, color *string) (calendar.AccountRecord, error) {
	ret := _m.Called(ctx, id, label, color)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountMeta")
	}

	var r0 calendar.AccountRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *string) (calendar.AccountRecord, error)); ok {
		return rf(ctx, id, label, color)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *string) calendar.AccountRecord); ok {
		r0 = rf(ctx, id, label, color)
	} else {
		r0 = ret.Get(0).(calendar.AccountRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *string, *string) error); ok {
		r1 = rf(ctx, id, label, color)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateAccountMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountMeta'
type MockRepository_UpdateAccountMeta_Call struct {
	*mock.Call
}

// UpdateAccountMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - label *string
//   - color *string
func (_e *MockRepository_Expecter) UpdateAccountMeta(ctx interface{}, id interface{}, label interface{}, color interface{}) *MockRepository_UpdateAccountMeta_Call {
	return &MockRepository_UpdateAccountMeta_Call{Call: _e.mock.On("UpdateAccountMeta", ctx, id, label, color)}
}

func (_c *MockRepository_UpdateAccountMeta_Call) Run(run func(ctx context.Context, id int32, label *string, color *string)) *MockRepository_UpdateAccountMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockRepository_UpdateAccountMeta_Call) Return(_a0 calendar.AccountRecord, _a1 error) *MockRepository_UpdateAccountMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateAccountMeta_Call) RunAndReturn(run func(context.Context, int32, *string, *string) (calendar.AccountRecord, error)) *MockRepository_UpdateAccountMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountStatus provides a mock function with given fields: ctx, id, status, syncError
func (_m *MockRepository) UpdateAccountStatus(ctx context.Context, id int32, status string, syncError *string) error {
	ret := _m.Called(ctx, id, status, syncError)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, *string) error); ok {
		r0 = rf(ctx, id, status, syncError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateAccountStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountStatus'
type MockRepository_UpdateAccountStatus_Call struct {
	*mock.Call
}

// UpdateAccountStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - status string
//   - syncError *string
func (_e *MockRepository_Expecter) UpdateAccountStatus(ctx interface{}, id interface{}, status interface{}, syncError interface{}) *MockRepository_UpdateAccountStatus_Call {
	return &MockRepository_UpdateAccountStatus_Call{Call: _e.mock.On("UpdateAccountStatus", ctx, id, status, syncError)}
}

func (_c *MockRepository_UpdateAccountStatus_Call) Run(run func(ctx context.Context, id int32, status string, syncError *string)) *MockRepository_UpdateAccountStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockRepository_UpdateAccountStatus_Call) Return(_a0 error) *MockRepository_UpdateAccountStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateAccountStatus_Call) RunAndReturn(run func(context.Context, int32, string, *string) error) *MockRepository_UpdateAccountStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCalendarPrefs provides a mock function with given fields: ctx, id, p
func (_m *MockRepository) UpdateCalendarPrefs(ctx context.Context, id int32, p calendar.CalendarPrefs) (calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, id, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCalendarPrefs")
	}

	var r0 calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, calendar.CalendarPrefs) (calendar.CalendarRecord, error)); ok {
		return rf(ctx, id, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, calendar.CalendarPrefs) calendar.CalendarRecord); ok {
		r0 = rf(ctx, id, p)
	} else {
		r0 = ret.Get(0).(calendar.CalendarRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, calendar.CalendarPrefs) error); ok {
		r1 = rf(ctx, id, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateCalendarPrefs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCalendarPrefs'
type MockRepository_UpdateCalendarPrefs_Call struct {
	*mock.Call
}

// UpdateCalendarPrefs is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - p calendar.CalendarPrefs
func (_e *MockRepository_Expecter) UpdateCalendarPrefs(ctx interface{}, id interface{}, p interface{}) *MockRepository_UpdateCalendarPrefs_Call {
	return &MockRepository_UpdateCalendarPrefs_Call{Call: _e.mock.On("UpdateCalendarPrefs", ctx, id, p)}
}

func (_c *MockRepository_UpdateCalendarPrefs_Call) Run(run func(ctx context.Context, id int32, p calendar.CalendarPrefs)) *MockRepository_UpdateCalendarPrefs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(calendar.CalendarPrefs))
	})
	return _c
}

func (_c *MockRepository_UpdateCalendarPrefs_Call) Return(_a0 calendar.CalendarRecord, _a1 error) *MockRepository_UpdateCalendarPrefs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateCalendarPrefs_Call) RunAndReturn(run func(context.Context, int32, calendar.CalendarPrefs) (calendar.CalendarRecord, error)) *MockRepository_UpdateCalendarPrefs_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAccount provides a mock function with given fields: ctx, p
func (_m *MockRepository) UpsertAccount(ctx context.Context, p calendar.UpsertAccountParams) (calendar.AccountRecord, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAccount")
	}

	var r0 calendar.AccountRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertAccountParams) (calendar.AccountRecord, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertAccountParams) calendar.AccountRecord); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(calendar.AccountRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, calendar.UpsertAccountParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpsertAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAccount'
type MockRepository_UpsertAccount_Call struct {
	*mock.Call
}

// UpsertAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - p calendar.UpsertAccountParams
func (_e *MockRepository_Expecter) UpsertAccount(ctx interface{}, p interface{}) *MockRepository_UpsertAccount_Call {
	return &MockRepository_UpsertAccount_Call{Call: _e.mock.On("UpsertAccount", ctx, p)}
}

func (_c *MockRepository_UpsertAccount_Call) Run(run func(ctx context.Context, p calendar.UpsertAccountParams)) *MockRepository_UpsertAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(calendar.UpsertAccountParams))
	})
	return _c
}

func (_c *MockRepository_UpsertAccount_Call) Return(_a0 calendar.AccountRecord, _a1 error) *MockRepository_UpsertAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpsertAccount_Call) RunAndReturn(run func(context.Context, calendar.UpsertAccountParams) (calendar.AccountRecord, error)) *MockRepository_UpsertAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertCalendar provides a mock function with given fields: ctx, p
func (_m *MockRepository) UpsertCalendar(ctx context.Context, p calendar.UpsertCalendarParams) (calendar.CalendarRecord, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCalendar")
	}

	var r0 calendar.CalendarRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertCalendarParams) (calendar.CalendarRecord, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertCalendarParams) calendar.CalendarRecord); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(calendar.CalendarRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, calendar.UpsertCalendarParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpsertCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertCalendar'
type MockRepository_UpsertCalendar_Call struct {
	*mock.Call
}

// UpsertCalendar is a helper method to define mock.On call
//   - ctx context.Context
//   - p calendar.UpsertCalendarParams
func (_e *MockRepository_Expecter) UpsertCalendar(ctx interface{}, p interface{}) *MockRepository_UpsertCalendar_Call {
	return &MockRepository_UpsertCalendar_Call{Call: _e.mock.On("UpsertCalendar", ctx, p)}
}

func (_c *MockRepository_UpsertCalendar_Call) Run(run func(ctx context.Context, p calendar.UpsertCalendarParams)) *MockRepository_UpsertCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(calendar.UpsertCalendarParams))
	})
	return _c
}

func (_c *MockRepository_UpsertCalendar_Call) Return(_a0 calendar.CalendarRecord, _a1 error) *MockRepository_UpsertCalendar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpsertCalendar_Call) RunAndReturn(run func(context.Context, calendar.UpsertCalendarParams) (calendar.CalendarRecord, error)) *MockRepository_UpsertCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEvent provides a mock function with given fields: ctx, p
func (_m *MockRepository) UpsertEvent(ctx context.Context, p calendar.UpsertEventParams) (calendar.EventRecord, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEvent")
	}

	var r0 calendar.EventRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertEventParams) (calendar.EventRecord, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, calendar.UpsertEventParams) calendar.EventRecord); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(calendar.EventRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, calendar.UpsertEventParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEvent'
type MockRepository_UpsertEvent_Call struct {
	*mock.Call
}

// UpsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - p calendar.UpsertEventParams
func (_e *MockRepository_Expecter) UpsertEvent(ctx interface{}, p interface{}) *MockRepository_UpsertEvent_Call {
	return &MockRepository_UpsertEvent_Call{Call: _e.mock.On("UpsertEvent", ctx, p)}
}

func (_c *MockRepository_UpsertEvent_Call) Run(run func(ctx context.Context, p calendar.UpsertEventParams)) *MockRepository_UpsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(calendar.UpsertEventParams))
	})
	return _c
}

func (_c *MockRepository_UpsertEvent_Call) Return(_a0 calendar.EventRecord, _a1 error) *MockRepository_UpsertEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpsertEvent_Call) RunAndReturn(run func(context.Context, calendar.UpsertEventParams) (calendar.EventRecord, error)) *MockRepository_UpsertEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
