// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	history "gv-api/internal/history"

	mock "github.com/stretchr/testify/mock"

	tasks "gv-api/internal/tasks"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, name, description, dueAt, parentID
func (_m *MockRepository) CreateProject(ctx context.Context, name string, description *string, dueAt *time.Time, parentID *int32) (tasks.ProjectResponse, error) {
	ret := _m.Called(ctx, name, description, dueAt, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 tasks.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *time.Time, *int32) (tasks.ProjectResponse, error)); ok {
		return rf(ctx, name, description, dueAt, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *time.Time, *int32) tasks.ProjectResponse); ok {
		r0 = rf(ctx, name, description, dueAt, parentID)
	} else {
		r0 = ret.Get(0).(tasks.ProjectResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *time.Time, *int32) error); ok {
		r1 = rf(ctx, name, description, dueAt, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockRepository_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - dueAt *time.Time
//   - parentID *int32
func (_e *MockRepository_Expecter) CreateProject(ctx interface{}, name interface{}, description interface{}, dueAt interface{}, parentID interface{}) *MockRepository_CreateProject_Call {
	return &MockRepository_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, name, description, dueAt, parentID)}
}

func (_c *MockRepository_CreateProject_Call) Run(run func(ctx context.Context, name string, description *string, dueAt *time.Time, parentID *int32)) *MockRepository_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*time.Time), args[4].(*int32))
	})
	return _c
}

func (_c *MockRepository_CreateProject_Call) Return(_a0 tasks.ProjectResponse, _a1 error) *MockRepository_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateProject_Call) RunAndReturn(run func(context.Context, string, *string, *time.Time, *int32) (tasks.ProjectResponse, error)) *MockRepository_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, projectID, name, description, dueAt, taskType, recurrence, priority
func (_m *MockRepository) CreateTask(ctx context.Context, projectID *int32, name string, description *string, dueAt *time.Time, taskType string, recurrence *int32, priority int32) (tasks.TaskResponse, error) {
	ret := _m.Called(ctx, projectID, name, description, dueAt, taskType, recurrence, priority)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 tasks.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int32, string, *string, *time.Time, string, *int32, int32) (tasks.TaskResponse, error)); ok {
		return rf(ctx, projectID, name, description, dueAt, taskType, recurrence, priority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int32, string, *string, *time.Time, string, *int32, int32) tasks.TaskResponse); ok {
		r0 = rf(ctx, projectID, name, description, dueAt, taskType, recurrence, priority)
	} else {
		r0 = ret.Get(0).(tasks.TaskResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int32, string, *string, *time.Time, string, *int32, int32) error); ok {
		r1 = rf(ctx, projectID, name, description, dueAt, taskType, recurrence, priority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID *int32
//   - name string
//   - description *string
//   - dueAt *time.Time
//   - taskType string
//   - recurrence *int32
//   - priority int32
func (_e *MockRepository_Expecter) CreateTask(ctx interface{}, projectID interface{}, name interface{}, description interface{}, dueAt interface{}, taskType interface{}, recurrence interface{}, priority interface{}) *MockRepository_CreateTask_Call {
	return &MockRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, projectID, name, description, dueAt, taskType, recurrence, priority)}
}

func (_c *MockRepository_CreateTask_Call) Run(run func(ctx context.Context, projectID *int32, name string, description *string, dueAt *time.Time, taskType string, recurrence *int32, priority int32)) *MockRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int32), args[2].(string), args[3].(*string), args[4].(*time.Time), args[5].(string), args[6].(*int32), args[7].(int32))
	})
	return _c
}

func (_c *MockRepository_CreateTask_Call) Return(_a0 tasks.TaskResponse, _a1 error) *MockRepository_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateTask_Call) RunAndReturn(run func(context.Context, *int32, string, *string, *time.Time, string, *int32, int32) (tasks.TaskResponse, error)) *MockRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTimeEntry provides a mock function with given fields: ctx, taskID, startedAt, finishedAt, comment
func (_m *MockRepository) CreateTimeEntry(ctx context.Context, taskID int32, startedAt time.Time, finishedAt *time.Time, comment *string) (tasks.TimeEntryResponse, error) {
	ret := _m.Called(ctx, taskID, startedAt, finishedAt, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateTimeEntry")
	}

	var r0 tasks.TimeEntryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, time.Time, *time.Time, *string) (tasks.TimeEntryResponse, error)); ok {
		return rf(ctx, taskID, startedAt, finishedAt, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, time.Time, *time.Time, *string) tasks.TimeEntryResponse); ok {
		r0 = rf(ctx, taskID, startedAt, finishedAt, comment)
	} else {
		r0 = ret.Get(0).(tasks.TimeEntryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, time.Time, *time.Time, *string) error); ok {
		r1 = rf(ctx, taskID, startedAt, finishedAt, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateTimeEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTimeEntry'
type MockRepository_CreateTimeEntry_Call struct {
	*mock.Call
}

// CreateTimeEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
//   - startedAt time.Time
//   - finishedAt *time.Time
//   - comment *string
func (_e *MockRepository_Expecter) CreateTimeEntry(ctx interface{}, taskID interface{}, startedAt interface{}, finishedAt interface{}, comment interface{}) *MockRepository_CreateTimeEntry_Call {
	return &MockRepository_CreateTimeEntry_Call{Call: _e.mock.On("CreateTimeEntry", ctx, taskID, startedAt, finishedAt, comment)}
}

func (_c *MockRepository_CreateTimeEntry_Call) Run(run func(ctx context.Context, taskID int32, startedAt time.Time, finishedAt *time.Time, comment *string)) *MockRepository_CreateTimeEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(time.Time), args[3].(*time.Time), args[4].(*string))
	})
	return _c
}

func (_c *MockRepository_CreateTimeEntry_Call) Return(_a0 tasks.TimeEntryResponse, _a1 error) *MockRepository_CreateTimeEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateTimeEntry_Call) RunAndReturn(run func(context.Context, int32, time.Time, *time.Time, *string) (tasks.TimeEntryResponse, error)) *MockRepository_CreateTimeEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodo provides a mock function with given fields: ctx, taskID, name
func (_m *MockRepository) CreateTodo(ctx context.Context, taskID int32, name string) (tasks.TodoResponse, error) {
	ret := _m.Called(ctx, taskID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 tasks.TodoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) (tasks.TodoResponse, error)); ok {
		return rf(ctx, taskID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) tasks.TodoResponse); ok {
		r0 = rf(ctx, taskID, name)
	} else {
		r0 = ret.Get(0).(tasks.TodoResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = rf(ctx, taskID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockRepository_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
//   - name string
func (_e *MockRepository_Expecter) CreateTodo(ctx interface{}, taskID interface{}, name interface{}) *MockRepository_CreateTodo_Call {
	return &MockRepository_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, taskID, name)}
}

func (_c *MockRepository_CreateTodo_Call) Run(run func(ctx context.Context, taskID int32, name string)) *MockRepository_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_CreateTodo_Call) Return(_a0 tasks.TodoResponse, _a1 error) *MockRepository_CreateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateTodo_Call) RunAndReturn(run func(context.Context, int32, string) (tasks.TodoResponse, error)) *MockRepository_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteProject(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockRepository_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockRepository_DeleteProject_Call {
	return &MockRepository_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockRepository_DeleteProject_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteProject_Call) Return(_a0 error) *MockRepository_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteProject_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteTask(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockRepository_DeleteTask_Call {
	return &MockRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockRepository_DeleteTask_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteTask_Call) Return(_a0 error) *MockRepository_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteTask_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTimeEntry provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteTimeEntry(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTimeEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteTimeEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTimeEntry'
type MockRepository_DeleteTimeEntry_Call struct {
	*mock.Call
}

// DeleteTimeEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteTimeEntry(ctx interface{}, id interface{}) *MockRepository_DeleteTimeEntry_Call {
	return &MockRepository_DeleteTimeEntry_Call{Call: _e.mock.On("DeleteTimeEntry", ctx, id)}
}

func (_c *MockRepository_DeleteTimeEntry_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteTimeEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteTimeEntry_Call) Return(_a0 error) *MockRepository_DeleteTimeEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteTimeEntry_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteTimeEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteTodo(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockRepository_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) DeleteTodo(ctx interface{}, id interface{}) *MockRepository_DeleteTodo_Call {
	return &MockRepository_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *MockRepository_DeleteTodo_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_DeleteTodo_Call) Return(_a0 error) *MockRepository_DeleteTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteTodo_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// FinishDescendantProjects provides a mock function with given fields: ctx, projectID
func (_m *MockRepository) FinishDescendantProjects(ctx context.Context, projectID int32) error {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for FinishDescendantProjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_FinishDescendantProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishDescendantProjects'
type MockRepository_FinishDescendantProjects_Call struct {
	*mock.Call
}

// FinishDescendantProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int32
func (_e *MockRepository_Expecter) FinishDescendantProjects(ctx interface{}, projectID interface{}) *MockRepository_FinishDescendantProjects_Call {
	return &MockRepository_FinishDescendantProjects_Call{Call: _e.mock.On("FinishDescendantProjects", ctx, projectID)}
}

func (_c *MockRepository_FinishDescendantProjects_Call) Run(run func(ctx context.Context, projectID int32)) *MockRepository_FinishDescendantProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_FinishDescendantProjects_Call) Return(_a0 error) *MockRepository_FinishDescendantProjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_FinishDescendantProjects_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_FinishDescendantProjects_Call {
	_c.Call.Return(run)
	return _c
}

// FinishTasksByProjectTree provides a mock function with given fields: ctx, projectID
func (_m *MockRepository) FinishTasksByProjectTree(ctx context.Context, projectID int32) error {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for FinishTasksByProjectTree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_FinishTasksByProjectTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishTasksByProjectTree'
type MockRepository_FinishTasksByProjectTree_Call struct {
	*mock.Call
}

// FinishTasksByProjectTree is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int32
func (_e *MockRepository_Expecter) FinishTasksByProjectTree(ctx interface{}, projectID interface{}) *MockRepository_FinishTasksByProjectTree_Call {
	return &MockRepository_FinishTasksByProjectTree_Call{Call: _e.mock.On("FinishTasksByProjectTree", ctx, projectID)}
}

func (_c *MockRepository_FinishTasksByProjectTree_Call) Run(run func(ctx context.Context, projectID int32)) *MockRepository_FinishTasksByProjectTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_FinishTasksByProjectTree_Call) Return(_a0 error) *MockRepository_FinishTasksByProjectTree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_FinishTasksByProjectTree_Call) RunAndReturn(run func(context.Context, int32) error) *MockRepository_FinishTasksByProjectTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveProjects provides a mock function with given fields: ctx
func (_m *MockRepository) GetActiveProjects(ctx context.Context) ([]tasks.ActiveProject, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveProjects")
	}

	var r0 []tasks.ActiveProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]tasks.ActiveProject, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tasks.ActiveProject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.ActiveProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetActiveProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveProjects'
type MockRepository_GetActiveProjects_Call struct {
	*mock.Call
}

// GetActiveProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetActiveProjects(ctx interface{}) *MockRepository_GetActiveProjects_Call {
	return &MockRepository_GetActiveProjects_Call{Call: _e.mock.On("GetActiveProjects", ctx)}
}

func (_c *MockRepository_GetActiveProjects_Call) Run(run func(ctx context.Context)) *MockRepository_GetActiveProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetActiveProjects_Call) Return(_a0 []tasks.ActiveProject, _a1 error) *MockRepository_GetActiveProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetActiveProjects_Call) RunAndReturn(run func(context.Context) ([]tasks.ActiveProject, error)) *MockRepository_GetActiveProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveTimeEntry provides a mock function with given fields: ctx
func (_m *MockRepository) GetActiveTimeEntry(ctx context.Context) (tasks.ActiveTimeEntryResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTimeEntry")
	}

	var r0 tasks.ActiveTimeEntryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tasks.ActiveTimeEntryResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tasks.ActiveTimeEntryResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(tasks.ActiveTimeEntryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetActiveTimeEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTimeEntry'
type MockRepository_GetActiveTimeEntry_Call struct {
	*mock.Call
}

// GetActiveTimeEntry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetActiveTimeEntry(ctx interface{}) *MockRepository_GetActiveTimeEntry_Call {
	return &MockRepository_GetActiveTimeEntry_Call{Call: _e.mock.On("GetActiveTimeEntry", ctx)}
}

func (_c *MockRepository_GetActiveTimeEntry_Call) Run(run func(ctx context.Context)) *MockRepository_GetActiveTimeEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetActiveTimeEntry_Call) Return(_a0 tasks.ActiveTimeEntryResponse, _a1 error) *MockRepository_GetActiveTimeEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetActiveTimeEntry_Call) RunAndReturn(run func(context.Context) (tasks.ActiveTimeEntryResponse, error)) *MockRepository_GetActiveTimeEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetProject(ctx context.Context, id int32) (tasks.ProjectDetailResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 tasks.ProjectDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (tasks.ProjectDetailResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) tasks.ProjectDetailResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tasks.ProjectDetailResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockRepository_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetProject(ctx interface{}, id interface{}) *MockRepository_GetProject_Call {
	return &MockRepository_GetProject_Call{Call: _e.mock.On("GetProject", ctx, id)}
}

func (_c *MockRepository_GetProject_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetProject_Call) Return(_a0 tasks.ProjectDetailResponse, _a1 error) *MockRepository_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetProject_Call) RunAndReturn(run func(context.Context, int32) (tasks.ProjectDetailResponse, error)) *MockRepository_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectChildren provides a mock function with given fields: ctx, projectID
func (_m *MockRepository) GetProjectChildren(ctx context.Context, projectID int32) (tasks.ProjectChildrenResponse, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectChildren")
	}

	var r0 tasks.ProjectChildrenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (tasks.ProjectChildrenResponse, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) tasks.ProjectChildrenResponse); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(tasks.ProjectChildrenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetProjectChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectChildren'
type MockRepository_GetProjectChildren_Call struct {
	*mock.Call
}

// GetProjectChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int32
func (_e *MockRepository_Expecter) GetProjectChildren(ctx interface{}, projectID interface{}) *MockRepository_GetProjectChildren_Call {
	return &MockRepository_GetProjectChildren_Call{Call: _e.mock.On("GetProjectChildren", ctx, projectID)}
}

func (_c *MockRepository_GetProjectChildren_Call) Run(run func(ctx context.Context, projectID int32)) *MockRepository_GetProjectChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetProjectChildren_Call) Return(_a0 tasks.ProjectChildrenResponse, _a1 error) *MockRepository_GetProjectChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetProjectChildren_Call) RunAndReturn(run func(context.Context, int32) (tasks.ProjectChildrenResponse, error)) *MockRepository_GetProjectChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootProjects provides a mock function with given fields: ctx
func (_m *MockRepository) GetRootProjects(ctx context.Context) ([]tasks.ProjectResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRootProjects")
	}

	var r0 []tasks.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]tasks.ProjectResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tasks.ProjectResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRootProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootProjects'
type MockRepository_GetRootProjects_Call struct {
	*mock.Call
}

// GetRootProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetRootProjects(ctx interface{}) *MockRepository_GetRootProjects_Call {
	return &MockRepository_GetRootProjects_Call{Call: _e.mock.On("GetRootProjects", ctx)}
}

func (_c *MockRepository_GetRootProjects_Call) Run(run func(ctx context.Context)) *MockRepository_GetRootProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetRootProjects_Call) Return(_a0 []tasks.ProjectResponse, _a1 error) *MockRepository_GetRootProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRootProjects_Call) RunAndReturn(run func(context.Context) ([]tasks.ProjectResponse, error)) *MockRepository_GetRootProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetTask(ctx context.Context, id int32) (tasks.TaskFullResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 tasks.TaskFullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (tasks.TaskFullResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) tasks.TaskFullResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tasks.TaskFullResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) GetTask(ctx interface{}, id interface{}) *MockRepository_GetTask_Call {
	return &MockRepository_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockRepository_GetTask_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetTask_Call) Return(_a0 tasks.TaskFullResponse, _a1 error) *MockRepository_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTask_Call) RunAndReturn(run func(context.Context, int32) (tasks.TaskFullResponse, error)) *MockRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskDependencies provides a mock function with given fields: ctx, taskID
func (_m *MockRepository) GetTaskDependencies(ctx context.Context, taskID int32) ([]tasks.TaskDepRef, []tasks.TaskDepRef, bool, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDependencies")
	}

	var r0 []tasks.TaskDepRef
	var r1 []tasks.TaskDepRef
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]tasks.TaskDepRef, []tasks.TaskDepRef, bool, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []tasks.TaskDepRef); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.TaskDepRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) []tasks.TaskDepRef); ok {
		r1 = rf(ctx, taskID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]tasks.TaskDepRef)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32) bool); ok {
		r2 = rf(ctx, taskID)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int32) error); ok {
		r3 = rf(ctx, taskID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockRepository_GetTaskDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskDependencies'
type MockRepository_GetTaskDependencies_Call struct {
	*mock.Call
}

// GetTaskDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
func (_e *MockRepository_Expecter) GetTaskDependencies(ctx interface{}, taskID interface{}) *MockRepository_GetTaskDependencies_Call {
	return &MockRepository_GetTaskDependencies_Call{Call: _e.mock.On("GetTaskDependencies", ctx, taskID)}
}

func (_c *MockRepository_GetTaskDependencies_Call) Run(run func(ctx context.Context, taskID int32)) *MockRepository_GetTaskDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetTaskDependencies_Call) Return(_a0 []tasks.TaskDepRef, _a1 []tasks.TaskDepRef, _a2 bool, _a3 error) *MockRepository_GetTaskDependencies_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockRepository_GetTaskDependencies_Call) RunAndReturn(run func(context.Context, int32) ([]tasks.TaskDepRef, []tasks.TaskDepRef, bool, error)) *MockRepository_GetTaskDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskTimeEntries provides a mock function with given fields: ctx, taskID
func (_m *MockRepository) GetTaskTimeEntries(ctx context.Context, taskID int32) (tasks.TaskTimeEntriesResponse, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskTimeEntries")
	}

	var r0 tasks.TaskTimeEntriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (tasks.TaskTimeEntriesResponse, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) tasks.TaskTimeEntriesResponse); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Get(0).(tasks.TaskTimeEntriesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTaskTimeEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskTimeEntries'
type MockRepository_GetTaskTimeEntries_Call struct {
	*mock.Call
}

// GetTaskTimeEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
func (_e *MockRepository_Expecter) GetTaskTimeEntries(ctx interface{}, taskID interface{}) *MockRepository_GetTaskTimeEntries_Call {
	return &MockRepository_GetTaskTimeEntries_Call{Call: _e.mock.On("GetTaskTimeEntries", ctx, taskID)}
}

func (_c *MockRepository_GetTaskTimeEntries_Call) Run(run func(ctx context.Context, taskID int32)) *MockRepository_GetTaskTimeEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockRepository_GetTaskTimeEntries_Call) Return(_a0 tasks.TaskTimeEntriesResponse, _a1 error) *MockRepository_GetTaskTimeEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTaskTimeEntries_Call) RunAndReturn(run func(context.Context, int32) (tasks.TaskTimeEntriesResponse, error)) *MockRepository_GetTaskTimeEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByDueDate provides a mock function with given fields: ctx, minPriority
func (_m *MockRepository) GetTasksByDueDate(ctx context.Context, minPriority *int32) ([]tasks.TaskByDueDateResponse, error) {
	ret := _m.Called(ctx, minPriority)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByDueDate")
	}

	var r0 []tasks.TaskByDueDateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int32) ([]tasks.TaskByDueDateResponse, error)); ok {
		return rf(ctx, minPriority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int32) []tasks.TaskByDueDateResponse); ok {
		r0 = rf(ctx, minPriority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.TaskByDueDateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int32) error); ok {
		r1 = rf(ctx, minPriority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTasksByDueDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByDueDate'
type MockRepository_GetTasksByDueDate_Call struct {
	*mock.Call
}

// GetTasksByDueDate is a helper method to define mock.On call
//   - ctx context.Context
//   - minPriority *int32
func (_e *MockRepository_Expecter) GetTasksByDueDate(ctx interface{}, minPriority interface{}) *MockRepository_GetTasksByDueDate_Call {
	return &MockRepository_GetTasksByDueDate_Call{Call: _e.mock.On("GetTasksByDueDate", ctx, minPriority)}
}

func (_c *MockRepository_GetTasksByDueDate_Call) Run(run func(ctx context.Context, minPriority *int32)) *MockRepository_GetTasksByDueDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int32))
	})
	return _c
}

func (_c *MockRepository_GetTasksByDueDate_Call) Return(_a0 []tasks.TaskByDueDateResponse, _a1 error) *MockRepository_GetTasksByDueDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTasksByDueDate_Call) RunAndReturn(run func(context.Context, *int32) ([]tasks.TaskByDueDateResponse, error)) *MockRepository_GetTasksByDueDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeEntriesByDateRange provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockRepository) GetTimeEntriesByDateRange(ctx context.Context, startTime time.Time, endTime time.Time) ([]tasks.TimeEntryWithTaskResponse, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeEntriesByDateRange")
	}

	var r0 []tasks.TimeEntryWithTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]tasks.TimeEntryWithTaskResponse, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []tasks.TimeEntryWithTaskResponse); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.TimeEntryWithTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTimeEntriesByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeEntriesByDateRange'
type MockRepository_GetTimeEntriesByDateRange_Call struct {
	*mock.Call
}

// GetTimeEntriesByDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockRepository_Expecter) GetTimeEntriesByDateRange(ctx interface{}, startTime interface{}, endTime interface{}) *MockRepository_GetTimeEntriesByDateRange_Call {
	return &MockRepository_GetTimeEntriesByDateRange_Call{Call: _e.mock.On("GetTimeEntriesByDateRange", ctx, startTime, endTime)}
}

func (_c *MockRepository_GetTimeEntriesByDateRange_Call) Run(run func(ctx context.Context, startTime time.Time, endTime time.Time)) *MockRepository_GetTimeEntriesByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetTimeEntriesByDateRange_Call) Return(_a0 []tasks.TimeEntryWithTaskResponse, _a1 error) *MockRepository_GetTimeEntriesByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTimeEntriesByDateRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]tasks.TimeEntryWithTaskResponse, error)) *MockRepository_GetTimeEntriesByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeEntryHistory provides a mock function with given fields: ctx, frequency, timezone, startAt, endAt
func (_m *MockRepository) GetTimeEntryHistory(ctx context.Context, frequency string, timezone string, startAt time.Time, endAt time.Time) ([]history.Point, error) {
	ret := _m.Called(ctx, frequency, timezone, startAt, endAt)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeEntryHistory")
	}

	var r0 []history.Point
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]history.Point, error)); ok {
		return rf(ctx, frequency, timezone, startAt, endAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []history.Point); ok {
		r0 = rf(ctx, frequency, timezone, startAt, endAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]history.Point)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, frequency, timezone, startAt, endAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTimeEntryHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeEntryHistory'
type MockRepository_GetTimeEntryHistory_Call struct {
	*mock.Call
}

// GetTimeEntryHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - frequency string
//   - timezone string
//   - startAt time.Time
//   - endAt time.Time
func (_e *MockRepository_Expecter) GetTimeEntryHistory(ctx interface{}, frequency interface{}, timezone interface{}, startAt interface{}, endAt interface{}) *MockRepository_GetTimeEntryHistory_Call {
	return &MockRepository_GetTimeEntryHistory_Call{Call: _e.mock.On("GetTimeEntryHistory", ctx, frequency, timezone, startAt, endAt)}
}

func (_c *MockRepository_GetTimeEntryHistory_Call) Run(run func(ctx context.Context, frequency string, timezone string, startAt time.Time, endAt time.Time)) *MockRepository_GetTimeEntryHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetTimeEntryHistory_Call) Return(_a0 []history.Point, _a1 error) *MockRepository_GetTimeEntryHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTimeEntryHistory_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]history.Point, error)) *MockRepository_GetTimeEntryHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeEntrySummary provides a mock function with given fields: ctx, todayStart, weekStart
func (_m *MockRepository) GetTimeEntrySummary(ctx context.Context, todayStart time.Time, weekStart time.Time) (tasks.TimeEntrySummaryResponse, error) {
	ret := _m.Called(ctx, todayStart, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeEntrySummary")
	}

	var r0 tasks.TimeEntrySummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (tasks.TimeEntrySummaryResponse, error)); ok {
		return rf(ctx, todayStart, weekStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) tasks.TimeEntrySummaryResponse); ok {
		r0 = rf(ctx, todayStart, weekStart)
	} else {
		r0 = ret.Get(0).(tasks.TimeEntrySummaryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, todayStart, weekStart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTimeEntrySummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeEntrySummary'
type MockRepository_GetTimeEntrySummary_Call struct {
	*mock.Call
}

// GetTimeEntrySummary is a helper method to define mock.On call
//   - ctx context.Context
//   - todayStart time.Time
//   - weekStart time.Time
func (_e *MockRepository_Expecter) GetTimeEntrySummary(ctx interface{}, todayStart interface{}, weekStart interface{}) *MockRepository_GetTimeEntrySummary_Call {
	return &MockRepository_GetTimeEntrySummary_Call{Call: _e.mock.On("GetTimeEntrySummary", ctx, todayStart, weekStart)}
}

func (_c *MockRepository_GetTimeEntrySummary_Call) Run(run func(ctx context.Context, todayStart time.Time, weekStart time.Time)) *MockRepository_GetTimeEntrySummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_GetTimeEntrySummary_Call) Return(_a0 tasks.TimeEntrySummaryResponse, _a1 error) *MockRepository_GetTimeEntrySummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTimeEntrySummary_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (tasks.TimeEntrySummaryResponse, error)) *MockRepository_GetTimeEntrySummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnfinishedTasks provides a mock function with given fields: ctx, minPriority
func (_m *MockRepository) GetUnfinishedTasks(ctx context.Context, minPriority *int32) ([]tasks.UnfinishedTask, error) {
	ret := _m.Called(ctx, minPriority)

	if len(ret) == 0 {
		panic("no return value specified for GetUnfinishedTasks")
	}

	var r0 []tasks.UnfinishedTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int32) ([]tasks.UnfinishedTask, error)); ok {
		return rf(ctx, minPriority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int32) []tasks.UnfinishedTask); ok {
		r0 = rf(ctx, minPriority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.UnfinishedTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int32) error); ok {
		r1 = rf(ctx, minPriority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUnfinishedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnfinishedTasks'
type MockRepository_GetUnfinishedTasks_Call struct {
	*mock.Call
}

// GetUnfinishedTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - minPriority *int32
func (_e *MockRepository_Expecter) GetUnfinishedTasks(ctx interface{}, minPriority interface{}) *MockRepository_GetUnfinishedTasks_Call {
	return &MockRepository_GetUnfinishedTasks_Call{Call: _e.mock.On("GetUnfinishedTasks", ctx, minPriority)}
}

func (_c *MockRepository_GetUnfinishedTasks_Call) Run(run func(ctx context.Context, minPriority *int32)) *MockRepository_GetUnfinishedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int32))
	})
	return _c
}

func (_c *MockRepository_GetUnfinishedTasks_Call) Return(_a0 []tasks.UnfinishedTask, _a1 error) *MockRepository_GetUnfinishedTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUnfinishedTasks_Call) RunAndReturn(run func(context.Context, *int32) ([]tasks.UnfinishedTask, error)) *MockRepository_GetUnfinishedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectsFast provides a mock function with given fields: ctx
func (_m *MockRepository) ListProjectsFast(ctx context.Context) ([]tasks.ProjectFastResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectsFast")
	}

	var r0 []tasks.ProjectFastResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]tasks.ProjectFastResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tasks.ProjectFastResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.ProjectFastResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListProjectsFast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectsFast'
type MockRepository_ListProjectsFast_Call struct {
	*mock.Call
}

// ListProjectsFast is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListProjectsFast(ctx interface{}) *MockRepository_ListProjectsFast_Call {
	return &MockRepository_ListProjectsFast_Call{Call: _e.mock.On("ListProjectsFast", ctx)}
}

func (_c *MockRepository_ListProjectsFast_Call) Run(run func(ctx context.Context)) *MockRepository_ListProjectsFast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListProjectsFast_Call) Return(_a0 []tasks.ProjectFastResponse, _a1 error) *MockRepository_ListProjectsFast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListProjectsFast_Call) RunAndReturn(run func(context.Context) ([]tasks.ProjectFastResponse, error)) *MockRepository_ListProjectsFast_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasksFast provides a mock function with given fields: ctx
func (_m *MockRepository) ListTasksFast(ctx context.Context) ([]tasks.TaskFastResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksFast")
	}

	var r0 []tasks.TaskFastResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]tasks.TaskFastResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tasks.TaskFastResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.TaskFastResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListTasksFast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasksFast'
type MockRepository_ListTasksFast_Call struct {
	*mock.Call
}

// ListTasksFast is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListTasksFast(ctx interface{}) *MockRepository_ListTasksFast_Call {
	return &MockRepository_ListTasksFast_Call{Call: _e.mock.On("ListTasksFast", ctx)}
}

func (_c *MockRepository_ListTasksFast_Call) Run(run func(ctx context.Context)) *MockRepository_ListTasksFast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListTasksFast_Call) Return(_a0 []tasks.TaskFastResponse, _a1 error) *MockRepository_ListTasksFast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListTasksFast_Call) RunAndReturn(run func(context.Context) ([]tasks.TaskFastResponse, error)) *MockRepository_ListTasksFast_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceTaskDependencies provides a mock function with given fields: ctx, taskID, dependsOn
func (_m *MockRepository) ReplaceTaskDependencies(ctx context.Context, taskID int32, dependsOn []int32) error {
	ret := _m.Called(ctx, taskID, dependsOn)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceTaskDependencies")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []int32) error); ok {
		r0 = rf(ctx, taskID, dependsOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ReplaceTaskDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceTaskDependencies'
type MockRepository_ReplaceTaskDependencies_Call struct {
	*mock.Call
}

// ReplaceTaskDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
//   - dependsOn []int32
func (_e *MockRepository_Expecter) ReplaceTaskDependencies(ctx interface{}, taskID interface{}, dependsOn interface{}) *MockRepository_ReplaceTaskDependencies_Call {
	return &MockRepository_ReplaceTaskDependencies_Call{Call: _e.mock.On("ReplaceTaskDependencies", ctx, taskID, dependsOn)}
}

func (_c *MockRepository_ReplaceTaskDependencies_Call) Run(run func(ctx context.Context, taskID int32, dependsOn []int32)) *MockRepository_ReplaceTaskDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].([]int32))
	})
	return _c
}

func (_c *MockRepository_ReplaceTaskDependencies_Call) Return(_a0 error) *MockRepository_ReplaceTaskDependencies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ReplaceTaskDependencies_Call) RunAndReturn(run func(context.Context, int32, []int32) error) *MockRepository_ReplaceTaskDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceTaskBlocks provides a mock function with given fields: ctx, taskID, blocks
func (_m *MockRepository) ReplaceTaskBlocks(ctx context.Context, taskID int32, blocks []int32) error {
	ret := _m.Called(ctx, taskID, blocks)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceTaskBlocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []int32) error); ok {
		r0 = rf(ctx, taskID, blocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ReplaceTaskBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceTaskBlocks'
type MockRepository_ReplaceTaskBlocks_Call struct {
	*mock.Call
}

// ReplaceTaskBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int32
//   - blocks []int32
func (_e *MockRepository_Expecter) ReplaceTaskBlocks(ctx interface{}, taskID interface{}, blocks interface{}) *MockRepository_ReplaceTaskBlocks_Call {
	return &MockRepository_ReplaceTaskBlocks_Call{Call: _e.mock.On("ReplaceTaskBlocks", ctx, taskID, blocks)}
}

func (_c *MockRepository_ReplaceTaskBlocks_Call) Run(run func(ctx context.Context, taskID int32, blocks []int32)) *MockRepository_ReplaceTaskBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].([]int32))
	})
	return _c
}

func (_c *MockRepository_ReplaceTaskBlocks_Call) Return(_a0 error) *MockRepository_ReplaceTaskBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ReplaceTaskBlocks_Call) RunAndReturn(run func(context.Context, int32, []int32) error) *MockRepository_ReplaceTaskBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateProject(ctx context.Context, req tasks.UpdateProjectRequest) (tasks.ProjectResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 tasks.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateProjectRequest) (tasks.ProjectResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateProjectRequest) tasks.ProjectResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(tasks.ProjectResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, tasks.UpdateProjectRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockRepository_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - req tasks.UpdateProjectRequest
func (_e *MockRepository_Expecter) UpdateProject(ctx interface{}, req interface{}) *MockRepository_UpdateProject_Call {
	return &MockRepository_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, req)}
}

func (_c *MockRepository_UpdateProject_Call) Run(run func(ctx context.Context, req tasks.UpdateProjectRequest)) *MockRepository_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tasks.UpdateProjectRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateProject_Call) Return(_a0 tasks.ProjectResponse, _a1 error) *MockRepository_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateProject_Call) RunAndReturn(run func(context.Context, tasks.UpdateProjectRequest) (tasks.ProjectResponse, error)) *MockRepository_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateTask(ctx context.Context, req tasks.UpdateTaskRequest) (tasks.TaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 tasks.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTaskRequest) (tasks.TaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTaskRequest) tasks.TaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(tasks.TaskResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, tasks.UpdateTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req tasks.UpdateTaskRequest
func (_e *MockRepository_Expecter) UpdateTask(ctx interface{}, req interface{}) *MockRepository_UpdateTask_Call {
	return &MockRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, req)}
}

func (_c *MockRepository_UpdateTask_Call) Run(run func(ctx context.Context, req tasks.UpdateTaskRequest)) *MockRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tasks.UpdateTaskRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateTask_Call) Return(_a0 tasks.TaskResponse, _a1 error) *MockRepository_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateTask_Call) RunAndReturn(run func(context.Context, tasks.UpdateTaskRequest) (tasks.TaskResponse, error)) *MockRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTimeEntry provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateTimeEntry(ctx context.Context, req tasks.UpdateTimeEntryRequest) (tasks.TimeEntryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimeEntry")
	}

	var r0 tasks.TimeEntryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTimeEntryRequest) (tasks.TimeEntryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTimeEntryRequest) tasks.TimeEntryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(tasks.TimeEntryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, tasks.UpdateTimeEntryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateTimeEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTimeEntry'
type MockRepository_UpdateTimeEntry_Call struct {
	*mock.Call
}

// UpdateTimeEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - req tasks.UpdateTimeEntryRequest
func (_e *MockRepository_Expecter) UpdateTimeEntry(ctx interface{}, req interface{}) *MockRepository_UpdateTimeEntry_Call {
	return &MockRepository_UpdateTimeEntry_Call{Call: _e.mock.On("UpdateTimeEntry", ctx, req)}
}

func (_c *MockRepository_UpdateTimeEntry_Call) Run(run func(ctx context.Context, req tasks.UpdateTimeEntryRequest)) *MockRepository_UpdateTimeEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tasks.UpdateTimeEntryRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateTimeEntry_Call) Return(_a0 tasks.TimeEntryResponse, _a1 error) *MockRepository_UpdateTimeEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateTimeEntry_Call) RunAndReturn(run func(context.Context, tasks.UpdateTimeEntryRequest) (tasks.TimeEntryResponse, error)) *MockRepository_UpdateTimeEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, req
func (_m *MockRepository) UpdateTodo(ctx context.Context, req tasks.UpdateTodoRequest) (tasks.TodoResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 tasks.TodoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTodoRequest) (tasks.TodoResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tasks.UpdateTodoRequest) tasks.TodoResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(tasks.TodoResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, tasks.UpdateTodoRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockRepository_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - req tasks.UpdateTodoRequest
func (_e *MockRepository_Expecter) UpdateTodo(ctx interface{}, req interface{}) *MockRepository_UpdateTodo_Call {
	return &MockRepository_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, req)}
}

func (_c *MockRepository_UpdateTodo_Call) Run(run func(ctx context.Context, req tasks.UpdateTodoRequest)) *MockRepository_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tasks.UpdateTodoRequest))
	})
	return _c
}

func (_c *MockRepository_UpdateTodo_Call) Return(_a0 tasks.TodoResponse, _a1 error) *MockRepository_UpdateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateTodo_Call) RunAndReturn(run func(context.Context, tasks.UpdateTodoRequest) (tasks.TodoResponse, error)) *MockRepository_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
