// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const getHabitsWithLogs = `-- name: GetHabitsWithLogs :many
SELECT h.id, h.name, h.description, hl.value
FROM habits h 
LEFT JOIN habit_logs hl ON h.id = hl.habit_id AND hl.log_date = $1
`

type GetHabitsWithLogsRow struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Value       sql.NullFloat64 `json:"value"`
}

func (q *Queries) GetHabitsWithLogs(ctx context.Context, logDate time.Time) ([]GetHabitsWithLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitsWithLogs, logDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitsWithLogsRow
	for rows.Next() {
		var i GetHabitsWithLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLog = `-- name: UpsertLog :exec
INSERT INTO habit_logs (habit_id, log_date, value)
VALUES ($1, $2, $3)
ON CONFLICT (habit_id, log_date)
DO UPDATE SET value = excluded.value
`

type UpsertLogParams struct {
	HabitID int32     `json:"habit_id"`
	LogDate time.Time `json:"log_date"`
	Value   float32   `json:"value"`
}

func (q *Queries) UpsertLog(ctx context.Context, arg UpsertLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertLog, arg.HabitID, arg.LogDate, arg.Value)
	return err
}
