// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type HabitComparisonType string

const (
	HabitComparisonTypeEquals           HabitComparisonType = "equals"
	HabitComparisonTypeGreaterThan      HabitComparisonType = "greater_than"
	HabitComparisonTypeLessThan         HabitComparisonType = "less_than"
	HabitComparisonTypeGreaterEqualThan HabitComparisonType = "greater_equal_than"
	HabitComparisonTypeLessEqualThan    HabitComparisonType = "less_equal_than"
	HabitComparisonTypeInRange          HabitComparisonType = "in_range"
)

func (e *HabitComparisonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitComparisonType(s)
	case string:
		*e = HabitComparisonType(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitComparisonType: %T", src)
	}
	return nil
}

type NullHabitComparisonType struct {
	HabitComparisonType HabitComparisonType `json:"habit_comparison_type"`
	Valid               bool                `json:"valid"` // Valid is true if HabitComparisonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitComparisonType) Scan(value interface{}) error {
	if value == nil {
		ns.HabitComparisonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitComparisonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitComparisonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitComparisonType), nil
}

type HabitFrequency string

const (
	HabitFrequencyDaily   HabitFrequency = "daily"
	HabitFrequencyWeekly  HabitFrequency = "weekly"
	HabitFrequencyMonthly HabitFrequency = "monthly"
)

func (e *HabitFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitFrequency(s)
	case string:
		*e = HabitFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitFrequency: %T", src)
	}
	return nil
}

type NullHabitFrequency struct {
	HabitFrequency HabitFrequency `json:"habit_frequency"`
	Valid          bool           `json:"valid"` // Valid is true if HabitFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.HabitFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitFrequency), nil
}

type HabitValueType string

const (
	HabitValueTypeBoolean HabitValueType = "boolean"
	HabitValueTypeNumeric HabitValueType = "numeric"
)

func (e *HabitValueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitValueType(s)
	case string:
		*e = HabitValueType(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitValueType: %T", src)
	}
	return nil
}

type NullHabitValueType struct {
	HabitValueType HabitValueType `json:"habit_value_type"`
	Valid          bool           `json:"valid"` // Valid is true if HabitValueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitValueType) Scan(value interface{}) error {
	if value == nil {
		ns.HabitValueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitValueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitValueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitValueType), nil
}

type Habit struct {
	ID             int32                   `json:"id"`
	Name           string                  `json:"name"`
	Description    sql.NullString          `json:"description"`
	ValueType      HabitValueType          `json:"value_type"`
	Unit           sql.NullString          `json:"unit"`
	Frequency      HabitFrequency          `json:"frequency"`
	TargetValue    sql.NullFloat64         `json:"target_value"`
	TargetMin      sql.NullFloat64         `json:"target_min"`
	TargetMax      sql.NullFloat64         `json:"target_max"`
	ComparisonType NullHabitComparisonType `json:"comparison_type"`
	StartDate      sql.NullTime            `json:"start_date"`
	EndDate        sql.NullTime            `json:"end_date"`
	DefaultValue   sql.NullFloat64         `json:"default_value"`
	StreakStrict   sql.NullBool            `json:"streak_strict"`
	Icon           string                  `json:"icon"`
	BigStep        sql.NullFloat64         `json:"big_step"`
	SmallStep      sql.NullFloat64         `json:"small_step"`
}

type HabitLog struct {
	HabitID int32     `json:"habit_id"`
	LogDate time.Time `json:"log_date"`
	Value   float32   `json:"value"`
}
