// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package lightsdb

import (
	"context"
)

type Querier interface {
	CreateLight(ctx context.Context, arg CreateLightParams) (CreateLightRow, error)
	DeleteLight(ctx context.Context, id string) (int64, error)
	GetLight(ctx context.Context, id string) (GetLightRow, error)
	ListLights(ctx context.Context) ([]ListLightsRow, error)
	UpdateLight(ctx context.Context, arg UpdateLightParams) (UpdateLightRow, error)
}

var _ Querier = (*Queries)(nil)
