// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (CreateTodoRow, error)
	FinishProject(ctx context.Context, arg FinishProjectParams) (Project, error)
	FinishTask(ctx context.Context, arg FinishTaskParams) (Task, error)
	FinishTimeEntry(ctx context.Context, arg FinishTimeEntryParams) (TimeEntry, error)
	GetActiveProjects(ctx context.Context) ([]GetActiveProjectsRow, error)
	GetHabitsWithLogs(ctx context.Context, logDate time.Time) ([]GetHabitsWithLogsRow, error)
	GetRootProjects(ctx context.Context) ([]GetRootProjectsRow, error)
	GetUnfinishedTasks(ctx context.Context) ([]GetUnfinishedTasksRow, error)
	UpsertLog(ctx context.Context, arg UpsertLogParams) error
}

var _ Querier = (*Queries)(nil)
