// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, due_at, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, due_at, parent_id
`

type CreateProjectParams struct {
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

type CreateProjectRow struct {
	ID          int32       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.DueAt,
		arg.ParentID,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.ParentID,
	)
	return i, err
}
