// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tasksdb

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (CreateTodoRow, error)
	DeleteProject(ctx context.Context, id int32) error
	DeleteRemovedTaskDependencies(ctx context.Context, arg DeleteRemovedTaskDependenciesParams) error
	DeleteTask(ctx context.Context, id int32) error
	DeleteTimeEntry(ctx context.Context, id int32) error
	DeleteTodo(ctx context.Context, id int32) error
	FinishDescendantProjects(ctx context.Context, id int32) error
	FinishTasksByProjectTree(ctx context.Context, id int32) error
	GetActiveProjects(ctx context.Context) ([]GetActiveProjectsRow, error)
	GetActiveTimeEntry(ctx context.Context) (GetActiveTimeEntryRow, error)
	GetProjectWithDescendants(ctx context.Context, id int32) ([]GetProjectWithDescendantsRow, error)
	GetRootProjects(ctx context.Context) ([]GetRootProjectsRow, error)
	GetTaskByID(ctx context.Context, id int32) ([]GetTaskByIDRow, error)
	GetTaskDependencies(ctx context.Context, taskID int32) (GetTaskDependenciesRow, error)
	GetTasksByDueDate(ctx context.Context) ([]GetTasksByDueDateRow, error)
	GetTasksByProjectIDs(ctx context.Context, projectIds []int32) ([]GetTasksByProjectIDsRow, error)
	GetTimeEntriesByDateRange(ctx context.Context, arg GetTimeEntriesByDateRangeParams) ([]GetTimeEntriesByDateRangeRow, error)
	GetTimeEntriesByTaskID(ctx context.Context, id int32) ([]GetTimeEntriesByTaskIDRow, error)
	GetTimeEntryHistory(ctx context.Context, arg GetTimeEntryHistoryParams) ([]GetTimeEntryHistoryRow, error)
	GetTimeEntrySummary(ctx context.Context, arg GetTimeEntrySummaryParams) (GetTimeEntrySummaryRow, error)
	GetUnfinishedTasks(ctx context.Context) ([]GetUnfinishedTasksRow, error)
	ListProjectsFast(ctx context.Context) ([]ListProjectsFastRow, error)
	ListTasksFast(ctx context.Context) ([]ListTasksFastRow, error)
	// Wraps the task_dependency_would_cycle SQL function (see migration 011).
	// Returns true if replacing @task_id's outgoing dep edges with @new_deps
	// would create a cycle.
	TaskDependencyWouldCycle(ctx context.Context, arg TaskDependencyWouldCycleParams) (bool, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpsertTaskDependencies(ctx context.Context, arg UpsertTaskDependenciesParams) error
}

var _ Querier = (*Queries)(nil)
