// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package tasksdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, due_at, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, due_at, parent_id
`

type CreateProjectParams struct {
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

type CreateProjectRow struct {
	ID          int32       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.DueAt,
		arg.ParentID,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.ParentID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, name, description, due_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, due_at
`

type CreateTaskParams struct {
	ProjectID   *int32      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
}

type CreateTaskRow struct {
	ID          int32       `db:"id" json:"id"`
	ProjectID   *int32      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.DueAt,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DueAt,
	)
	return i, err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (task_id, started_at, finished_at, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, started_at, finished_at, comment
`

type CreateTimeEntryParams struct {
	TaskID     int32              `db:"task_id" json:"task_id"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Comment    *string            `db:"comment" json:"comment"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.TaskID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Comment,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Comment,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (task_id, name)
VALUES ($1, $2)
RETURNING id, task_id, name
`

type CreateTodoParams struct {
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
}

type CreateTodoRow struct {
	ID     int32  `db:"id" json:"id"`
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (CreateTodoRow, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.TaskID, arg.Name)
	var i CreateTodoRow
	err := row.Scan(&i.ID, &i.TaskID, &i.Name)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries WHERE id = $1
`

func (q *Queries) DeleteTimeEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTimeEntry, id)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const finishDescendantProjects = `-- name: FinishDescendantProjects :exec
WITH RECURSIVE project_tree AS (
    SELECT p.id FROM projects p WHERE p.id = $1
    UNION ALL
    SELECT c.id FROM projects c JOIN project_tree pt ON c.parent_id = pt.id
)
UPDATE projects p2 SET finished_at = NOW()
FROM project_tree pt
WHERE p2.id = pt.id AND p2.id != $1 AND p2.finished_at IS NULL
`

func (q *Queries) FinishDescendantProjects(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, finishDescendantProjects, id)
	return err
}

const finishTasksByProjectTree = `-- name: FinishTasksByProjectTree :exec
WITH RECURSIVE project_tree AS (
    SELECT p.id FROM projects p WHERE p.id = $1
    UNION ALL
    SELECT c.id FROM projects c JOIN project_tree pt ON c.parent_id = pt.id
)
UPDATE tasks t SET finished_at = NOW()
FROM project_tree pt
WHERE t.project_id = pt.id AND t.finished_at IS NULL
`

func (q *Queries) FinishTasksByProjectTree(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, finishTasksByProjectTree, id)
	return err
}

const getActiveProjects = `-- name: GetActiveProjects :many
SELECT id, parent_id, name, due_at
FROM projects
WHERE started_at IS NOT NULL AND finished_at IS NULL
ORDER BY name
`

type GetActiveProjectsRow struct {
	ID       int32       `db:"id" json:"id"`
	ParentID *int32      `db:"parent_id" json:"parent_id"`
	Name     string      `db:"name" json:"name"`
	DueAt    pgtype.Date `db:"due_at" json:"due_at"`
}

func (q *Queries) GetActiveProjects(ctx context.Context) ([]GetActiveProjectsRow, error) {
	rows, err := q.db.Query(ctx, getActiveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveProjectsRow{}
	for rows.Next() {
		var i GetActiveProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTimeEntry = `-- name: GetActiveTimeEntry :one
SELECT id, task_id, started_at, finished_at, comment
FROM time_entries
WHERE finished_at IS NULL
`

func (q *Queries) GetActiveTimeEntry(ctx context.Context) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, getActiveTimeEntry)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Comment,
	)
	return i, err
}

const getProjectWithDescendants = `-- name: GetProjectWithDescendants :many
WITH RECURSIVE project_tree AS (
    SELECT p.id, p.parent_id, p.name, p.description, p.due_at, p.started_at, p.finished_at, 0 AS depth
    FROM projects p WHERE p.id = $1
    UNION ALL
    SELECT c.id, c.parent_id, c.name, c.description, c.due_at, c.started_at, c.finished_at, pt.depth + 1
    FROM projects c
    JOIN project_tree pt ON c.parent_id = pt.id
)
SELECT id, parent_id, name, description, due_at, started_at, finished_at, depth
FROM project_tree
ORDER BY depth, due_at ASC NULLS LAST, name
`

type GetProjectWithDescendantsRow struct {
	ID          int32              `db:"id" json:"id"`
	ParentID    *int32             `db:"parent_id" json:"parent_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Depth       int32              `db:"depth" json:"depth"`
}

func (q *Queries) GetProjectWithDescendants(ctx context.Context, id int32) ([]GetProjectWithDescendantsRow, error) {
	rows, err := q.db.Query(ctx, getProjectWithDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectWithDescendantsRow{}
	for rows.Next() {
		var i GetProjectWithDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootProjects = `-- name: GetRootProjects :many
SELECT id, name, description, due_at, parent_id, started_at
FROM projects
WHERE parent_id IS NULL AND finished_at IS NULL
ORDER BY name
`

type GetRootProjectsRow struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	ParentID    *int32             `db:"parent_id" json:"parent_id"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) GetRootProjects(ctx context.Context) ([]GetRootProjectsRow, error) {
	rows, err := q.db.Query(ctx, getRootProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRootProjectsRow{}
	for rows.Next() {
		var i GetRootProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.ParentID,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :many
WITH task_info AS (
    SELECT t.id, t.project_id, t.name, t.description, t.due_at, t.started_at, t.finished_at,
        COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.depends_on WHERE td.task_id = t.id AND t2.finished_at IS NULL), '[]')::json AS depends_on,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.task_id WHERE td.depends_on = t.id), '[]')::json AS blocks,
        EXISTS(SELECT 1 FROM task_dependencies td3 JOIN tasks t3 ON t3.id = td3.depends_on WHERE td3.task_id = t.id AND t3.finished_at IS NULL) AS blocked
    FROM tasks t
    LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
    WHERE t.id = $1
    GROUP BY t.id
)
SELECT
    ti.id, ti.project_id, ti.name, ti.description, ti.due_at, ti.started_at, ti.finished_at, ti.time_spent,
    ti.depends_on, ti.blocks, ti.blocked,
    td.id AS todo_id, td.name AS todo_name, td.is_done AS todo_is_done
FROM task_info ti
LEFT JOIN todos td ON td.task_id = ti.id
ORDER BY td.is_done ASC NULLS LAST, td.id
`

type GetTaskByIDRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   *int32             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	TimeSpent   int64              `db:"time_spent" json:"time_spent"`
	DependsOn   []byte             `db:"depends_on" json:"depends_on"`
	Blocks      []byte             `db:"blocks" json:"blocks"`
	Blocked     bool               `db:"blocked" json:"blocked"`
	TodoID      *int32             `db:"todo_id" json:"todo_id"`
	TodoName    *string            `db:"todo_name" json:"todo_name"`
	TodoIsDone  *bool              `db:"todo_is_done" json:"todo_is_done"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id int32) ([]GetTaskByIDRow, error) {
	rows, err := q.db.Query(ctx, getTaskByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskByIDRow{}
	for rows.Next() {
		var i GetTaskByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TimeSpent,
			&i.DependsOn,
			&i.Blocks,
			&i.Blocked,
			&i.TodoID,
			&i.TodoName,
			&i.TodoIsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDependencies = `-- name: GetTaskDependencies :one
SELECT
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.depends_on WHERE td.task_id = $1 AND t2.finished_at IS NULL), '[]')::json AS depends_on,
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.task_id WHERE td.depends_on = $1), '[]')::json AS blocks,
    EXISTS(SELECT 1 FROM task_dependencies td3 JOIN tasks t3 ON t3.id = td3.depends_on WHERE td3.task_id = $1 AND t3.finished_at IS NULL) AS blocked
`

type GetTaskDependenciesRow struct {
	DependsOn []byte `db:"depends_on" json:"depends_on"`
	Blocks    []byte `db:"blocks" json:"blocks"`
	Blocked   bool   `db:"blocked" json:"blocked"`
}

func (q *Queries) GetTaskDependencies(ctx context.Context, taskID int32) (GetTaskDependenciesRow, error) {
	row := q.db.QueryRow(ctx, getTaskDependencies, taskID)
	var i GetTaskDependenciesRow
	err := row.Scan(&i.DependsOn, &i.Blocks, &i.Blocked)
	return i, err
}

const getTasksByDueDate = `-- name: GetTasksByDueDate :many
SELECT
    t.id, t.name, t.description, t.due_at, t.started_at,
    p.id AS project_id, p.name AS project_name, p.due_at AS project_due_at,
    COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent,
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.depends_on WHERE td.task_id = t.id AND t2.finished_at IS NULL), '[]')::json AS depends_on,
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.task_id WHERE td.depends_on = t.id), '[]')::json AS blocks
FROM tasks t
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
WHERE t.finished_at IS NULL
GROUP BY t.id, p.id
ORDER BY t.due_at ASC NULLS LAST, p.due_at ASC NULLS LAST, t.name
`

type GetTasksByDueDateRow struct {
	ID           int32              `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Description  *string            `db:"description" json:"description"`
	DueAt        pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ProjectID    *int32             `db:"project_id" json:"project_id"`
	ProjectName  *string            `db:"project_name" json:"project_name"`
	ProjectDueAt pgtype.Date        `db:"project_due_at" json:"project_due_at"`
	TimeSpent    int64              `db:"time_spent" json:"time_spent"`
	DependsOn    []byte             `db:"depends_on" json:"depends_on"`
	Blocks       []byte             `db:"blocks" json:"blocks"`
}

func (q *Queries) GetTasksByDueDate(ctx context.Context) ([]GetTasksByDueDateRow, error) {
	rows, err := q.db.Query(ctx, getTasksByDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByDueDateRow{}
	for rows.Next() {
		var i GetTasksByDueDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectDueAt,
			&i.TimeSpent,
			&i.DependsOn,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByProjectIDs = `-- name: GetTasksByProjectIDs :many
WITH task_times AS (
    SELECT
        t.id, t.project_id, t.name, t.description, t.due_at, t.started_at, t.finished_at,
        COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td2 JOIN tasks t2 ON t2.id = td2.depends_on WHERE td2.task_id = t.id AND t2.finished_at IS NULL), '[]')::json AS depends_on,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td2 JOIN tasks t2 ON t2.id = td2.task_id WHERE td2.depends_on = t.id), '[]')::json AS blocks,
        EXISTS(SELECT 1 FROM task_dependencies td3 JOIN tasks t3 ON t3.id = td3.depends_on WHERE td3.task_id = t.id AND t3.finished_at IS NULL) AS blocked
    FROM tasks t
    LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
    WHERE t.project_id = ANY($1::int[])
    GROUP BY t.id
)
SELECT
    tt.id, tt.project_id, tt.name, tt.description, tt.due_at, tt.started_at, tt.finished_at,
    tt.time_spent, tt.depends_on, tt.blocks, tt.blocked,
    td.id AS todo_id, td.name AS todo_name, td.is_done AS todo_is_done
FROM task_times tt
LEFT JOIN todos td ON td.task_id = tt.id
ORDER BY
    CASE
        WHEN tt.finished_at IS NOT NULL THEN 2
        WHEN tt.started_at IS NOT NULL THEN 0
        ELSE 1
    END,
    tt.due_at ASC NULLS LAST,
    tt.name,
    td.is_done ASC NULLS LAST, todo_id
`

type GetTasksByProjectIDsRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   *int32             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	TimeSpent   int64              `db:"time_spent" json:"time_spent"`
	DependsOn   []byte             `db:"depends_on" json:"depends_on"`
	Blocks      []byte             `db:"blocks" json:"blocks"`
	Blocked     bool               `db:"blocked" json:"blocked"`
	TodoID      *int32             `db:"todo_id" json:"todo_id"`
	TodoName    *string            `db:"todo_name" json:"todo_name"`
	TodoIsDone  *bool              `db:"todo_is_done" json:"todo_is_done"`
}

func (q *Queries) GetTasksByProjectIDs(ctx context.Context, projectIds []int32) ([]GetTasksByProjectIDsRow, error) {
	rows, err := q.db.Query(ctx, getTasksByProjectIDs, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByProjectIDsRow{}
	for rows.Next() {
		var i GetTasksByProjectIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TimeSpent,
			&i.DependsOn,
			&i.Blocks,
			&i.Blocked,
			&i.TodoID,
			&i.TodoName,
			&i.TodoIsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeEntriesByTaskID = `-- name: GetTimeEntriesByTaskID :many
WITH task_info AS (
    SELECT t.id, t.project_id, t.name, t.description, t.due_at, t.started_at, t.finished_at,
        COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.depends_on WHERE td.task_id = t.id AND t2.finished_at IS NULL), '[]')::json AS depends_on,
        COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.task_id WHERE td.depends_on = t.id), '[]')::json AS blocks,
        EXISTS(SELECT 1 FROM task_dependencies td3 JOIN tasks t3 ON t3.id = td3.depends_on WHERE td3.task_id = t.id AND t3.finished_at IS NULL) AS blocked
    FROM tasks t
    LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
    WHERE t.id = $1
    GROUP BY t.id
)
SELECT
    ti.id AS task_id, ti.project_id, ti.name, ti.description, ti.due_at,
    ti.started_at AS task_started_at, ti.finished_at AS task_finished_at, ti.time_spent,
    ti.depends_on, ti.blocks, ti.blocked,
    te.id AS time_entry_id, te.started_at AS entry_started_at, te.finished_at AS entry_finished_at, te.comment
FROM task_info ti
LEFT JOIN time_entries te ON te.task_id = ti.id
ORDER BY te.started_at
`

type GetTimeEntriesByTaskIDRow struct {
	TaskID          int32              `db:"task_id" json:"task_id"`
	ProjectID       *int32             `db:"project_id" json:"project_id"`
	Name            string             `db:"name" json:"name"`
	Description     *string            `db:"description" json:"description"`
	DueAt           pgtype.Date        `db:"due_at" json:"due_at"`
	TaskStartedAt   pgtype.Timestamptz `db:"task_started_at" json:"task_started_at"`
	TaskFinishedAt  pgtype.Timestamptz `db:"task_finished_at" json:"task_finished_at"`
	TimeSpent       int64              `db:"time_spent" json:"time_spent"`
	DependsOn       []byte             `db:"depends_on" json:"depends_on"`
	Blocks          []byte             `db:"blocks" json:"blocks"`
	Blocked         bool               `db:"blocked" json:"blocked"`
	TimeEntryID     *int32             `db:"time_entry_id" json:"time_entry_id"`
	EntryStartedAt  pgtype.Timestamptz `db:"entry_started_at" json:"entry_started_at"`
	EntryFinishedAt pgtype.Timestamptz `db:"entry_finished_at" json:"entry_finished_at"`
	Comment         *string            `db:"comment" json:"comment"`
}

func (q *Queries) GetTimeEntriesByTaskID(ctx context.Context, id int32) ([]GetTimeEntriesByTaskIDRow, error) {
	rows, err := q.db.Query(ctx, getTimeEntriesByTaskID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeEntriesByTaskIDRow{}
	for rows.Next() {
		var i GetTimeEntriesByTaskIDRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.TaskStartedAt,
			&i.TaskFinishedAt,
			&i.TimeSpent,
			&i.DependsOn,
			&i.Blocks,
			&i.Blocked,
			&i.TimeEntryID,
			&i.EntryStartedAt,
			&i.EntryFinishedAt,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeEntryHistory = `-- name: GetTimeEntryHistory :many
WITH entry_periods AS (
    SELECT
        te.started_at,
        te.finished_at,
        gs.period_start
    FROM time_entries te,
    LATERAL generate_series(
        date_trunc($2::text, te.started_at AT TIME ZONE $1::text),
        date_trunc($2::text, te.finished_at AT TIME ZONE $1::text),
        ('1 ' || $2::text)::interval
    ) AS gs(period_start)
    WHERE te.finished_at IS NOT NULL
      AND (te.started_at AT TIME ZONE $1::text)::date >= $3::date
      AND (te.started_at AT TIME ZONE $1::text)::date <= $4::date
)
SELECT
    ep.period_start::date AS date,
    (SUM(EXTRACT(EPOCH FROM (
        LEAST(ep.finished_at, (ep.period_start + ('1 ' || $2::text)::interval) AT TIME ZONE $1::text)
        - GREATEST(ep.started_at, ep.period_start AT TIME ZONE $1::text)
    ))) / 3600)::REAL AS value
FROM entry_periods ep
GROUP BY ep.period_start
ORDER BY date
`

type GetTimeEntryHistoryParams struct {
	Timezone  string    `db:"timezone" json:"timezone"`
	Frequency string    `db:"frequency" json:"frequency"`
	StartAt   time.Time `db:"start_at" json:"start_at"`
	EndAt     time.Time `db:"end_at" json:"end_at"`
}

type GetTimeEntryHistoryRow struct {
	Date  time.Time `db:"date" json:"date"`
	Value float32   `db:"value" json:"value"`
}

func (q *Queries) GetTimeEntryHistory(ctx context.Context, arg GetTimeEntryHistoryParams) ([]GetTimeEntryHistoryRow, error) {
	rows, err := q.db.Query(ctx, getTimeEntryHistory,
		arg.Timezone,
		arg.Frequency,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeEntryHistoryRow{}
	for rows.Next() {
		var i GetTimeEntryHistoryRow
		if err := rows.Scan(&i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeEntrySummary = `-- name: GetTimeEntrySummary :one
SELECT
    COALESCE(SUM(CASE WHEN finished_at >= $1::timestamptz
        THEN EXTRACT(EPOCH FROM (finished_at - GREATEST(started_at, $1::timestamptz)))::bigint ELSE 0 END), 0)::bigint AS today,
    COALESCE(SUM(EXTRACT(EPOCH FROM (finished_at - GREATEST(started_at, $2::timestamptz)))::bigint), 0)::bigint AS week
FROM time_entries
WHERE finished_at IS NOT NULL
  AND finished_at >= $2::timestamptz
`

type GetTimeEntrySummaryParams struct {
	TodayStart pgtype.Timestamptz `db:"today_start" json:"today_start"`
	WeekStart  pgtype.Timestamptz `db:"week_start" json:"week_start"`
}

type GetTimeEntrySummaryRow struct {
	Today int64 `db:"today" json:"today"`
	Week  int64 `db:"week" json:"week"`
}

func (q *Queries) GetTimeEntrySummary(ctx context.Context, arg GetTimeEntrySummaryParams) (GetTimeEntrySummaryRow, error) {
	row := q.db.QueryRow(ctx, getTimeEntrySummary, arg.TodayStart, arg.WeekStart)
	var i GetTimeEntrySummaryRow
	err := row.Scan(&i.Today, &i.Week)
	return i, err
}

const getUnfinishedTasks = `-- name: GetUnfinishedTasks :many
SELECT t.id, t.project_id, t.name, t.description, t.due_at, t.started_at,
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name, 'due_at', t2.due_at) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.depends_on WHERE td.task_id = t.id AND t2.finished_at IS NULL), '[]')::json AS depends_on,
    COALESCE((SELECT json_agg(json_build_object('id', t2.id, 'name', t2.name) ORDER BY t2.name) FROM task_dependencies td JOIN tasks t2 ON t2.id = td.task_id WHERE td.depends_on = t.id), '[]')::json AS blocks
FROM tasks t
WHERE t.finished_at IS NULL
ORDER BY t.name
`

type GetUnfinishedTasksRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   *int32             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	DueAt       pgtype.Date        `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	DependsOn   []byte             `db:"depends_on" json:"depends_on"`
	Blocks      []byte             `db:"blocks" json:"blocks"`
}

func (q *Queries) GetUnfinishedTasks(ctx context.Context) ([]GetUnfinishedTasksRow, error) {
	rows, err := q.db.Query(ctx, getUnfinishedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnfinishedTasksRow{}
	for rows.Next() {
		var i GetUnfinishedTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.DependsOn,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsFast = `-- name: ListProjectsFast :many
SELECT id, name FROM projects WHERE finished_at IS NULL ORDER BY name
`

type ListProjectsFastRow struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) ListProjectsFast(ctx context.Context) ([]ListProjectsFastRow, error) {
	rows, err := q.db.Query(ctx, listProjectsFast)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsFastRow{}
	for rows.Next() {
		var i ListProjectsFastRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksFast = `-- name: ListTasksFast :many
SELECT id, name FROM tasks WHERE finished_at IS NULL ORDER BY name
`

type ListTasksFastRow struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) ListTasksFast(ctx context.Context) ([]ListTasksFastRow, error) {
	rows, err := q.db.Query(ctx, listTasksFast)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksFastRow{}
	for rows.Next() {
		var i ListTasksFastRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTaskDependencies = `-- name: ReplaceTaskDependencies :exec
WITH deleted AS (
    DELETE FROM task_dependencies WHERE task_id = $1
)
INSERT INTO task_dependencies (task_id, depends_on)
SELECT $1, t.id
FROM unnest($2::int[]) AS dep_id
JOIN tasks t ON t.id = dep_id AND t.finished_at IS NULL
WHERE array_length($2::int[], 1) IS NOT NULL
`

type ReplaceTaskDependenciesParams struct {
	TaskID    int32   `db:"task_id" json:"task_id"`
	DependsOn []int32 `db:"depends_on" json:"depends_on"`
}

func (q *Queries) ReplaceTaskDependencies(ctx context.Context, arg ReplaceTaskDependenciesParams) error {
	_, err := q.db.Exec(ctx, replaceTaskDependencies, arg.TaskID, arg.DependsOn)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name        = CASE WHEN $1::bool        THEN $2::text             ELSE name END,
    description = CASE WHEN $3::bool  THEN $4::text      ELSE description END,
    due_at      = CASE WHEN $5::bool       THEN $6::date           ELSE due_at END,
    parent_id   = CASE WHEN $7::bool    THEN $8::int         ELSE parent_id END,
    started_at  = CASE WHEN $9::bool   THEN $10::timestamptz  ELSE started_at END,
    finished_at = CASE WHEN $11::bool  THEN $12::timestamptz ELSE finished_at END
WHERE id = $13
RETURNING id, parent_id, name, description, due_at, started_at, finished_at
`

type UpdateProjectParams struct {
	SetName        bool               `db:"set_name" json:"set_name"`
	Name           string             `db:"name" json:"name"`
	SetDescription bool               `db:"set_description" json:"set_description"`
	Description    string             `db:"description" json:"description"`
	SetDueAt       bool               `db:"set_due_at" json:"set_due_at"`
	DueAt          time.Time          `db:"due_at" json:"due_at"`
	SetParentID    bool               `db:"set_parent_id" json:"set_parent_id"`
	ParentID       int32              `db:"parent_id" json:"parent_id"`
	SetStartedAt   bool               `db:"set_started_at" json:"set_started_at"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	SetFinishedAt  bool               `db:"set_finished_at" json:"set_finished_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ID             int32              `db:"id" json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetDueAt,
		arg.DueAt,
		arg.SetParentID,
		arg.ParentID,
		arg.SetStartedAt,
		arg.StartedAt,
		arg.SetFinishedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    name        = CASE WHEN $1::bool        THEN $2::text             ELSE name END,
    description = CASE WHEN $3::bool  THEN $4::text      ELSE description END,
    due_at      = CASE WHEN $5::bool       THEN $6::date           ELSE due_at END,
    project_id  = CASE WHEN $7::bool   THEN $8::int        ELSE project_id END,
    started_at  = CASE WHEN $9::bool   THEN $10::timestamptz  ELSE started_at END,
    finished_at = CASE WHEN $11::bool  THEN $12::timestamptz ELSE finished_at END
WHERE id = $13
RETURNING id, project_id, name, description, due_at, started_at, finished_at
`

type UpdateTaskParams struct {
	SetName        bool               `db:"set_name" json:"set_name"`
	Name           string             `db:"name" json:"name"`
	SetDescription bool               `db:"set_description" json:"set_description"`
	Description    string             `db:"description" json:"description"`
	SetDueAt       bool               `db:"set_due_at" json:"set_due_at"`
	DueAt          time.Time          `db:"due_at" json:"due_at"`
	SetProjectID   bool               `db:"set_project_id" json:"set_project_id"`
	ProjectID      int32              `db:"project_id" json:"project_id"`
	SetStartedAt   bool               `db:"set_started_at" json:"set_started_at"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	SetFinishedAt  bool               `db:"set_finished_at" json:"set_finished_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ID             int32              `db:"id" json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetDueAt,
		arg.DueAt,
		arg.SetProjectID,
		arg.ProjectID,
		arg.SetStartedAt,
		arg.StartedAt,
		arg.SetFinishedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entries SET
    task_id     = CASE WHEN $1::bool     THEN $2::int           ELSE task_id END,
    started_at  = CASE WHEN $3::bool  THEN $4::timestamptz  ELSE started_at END,
    finished_at = CASE WHEN $5::bool  THEN $6::timestamptz ELSE finished_at END,
    comment     = CASE WHEN $7::bool      THEN $8::text          ELSE comment END
WHERE id = $9
RETURNING id, task_id, started_at, finished_at, comment
`

type UpdateTimeEntryParams struct {
	SetTaskID     bool               `db:"set_task_id" json:"set_task_id"`
	TaskID        int32              `db:"task_id" json:"task_id"`
	SetStartedAt  bool               `db:"set_started_at" json:"set_started_at"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	SetFinishedAt bool               `db:"set_finished_at" json:"set_finished_at"`
	FinishedAt    pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	SetComment    bool               `db:"set_comment" json:"set_comment"`
	Comment       string             `db:"comment" json:"comment"`
	ID            int32              `db:"id" json:"id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, updateTimeEntry,
		arg.SetTaskID,
		arg.TaskID,
		arg.SetStartedAt,
		arg.StartedAt,
		arg.SetFinishedAt,
		arg.FinishedAt,
		arg.SetComment,
		arg.Comment,
		arg.ID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Comment,
	)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET
    task_id = CASE WHEN $1::bool THEN $2::int ELSE task_id END,
    name    = CASE WHEN $3::bool    THEN $4::text   ELSE name END,
    is_done = CASE WHEN $5::bool THEN $6::bool ELSE is_done END
WHERE id = $7
RETURNING id, task_id, name, is_done
`

type UpdateTodoParams struct {
	SetTaskID bool   `db:"set_task_id" json:"set_task_id"`
	TaskID    int32  `db:"task_id" json:"task_id"`
	SetName   bool   `db:"set_name" json:"set_name"`
	Name      string `db:"name" json:"name"`
	SetIsDone bool   `db:"set_is_done" json:"set_is_done"`
	IsDone    bool   `db:"is_done" json:"is_done"`
	ID        int32  `db:"id" json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.SetTaskID,
		arg.TaskID,
		arg.SetName,
		arg.Name,
		arg.SetIsDone,
		arg.IsDone,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.IsDone,
	)
	return i, err
}
