// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package tasksdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, due_at, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, due_at, parent_id
`

type CreateProjectParams struct {
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

type CreateProjectRow struct {
	ID          int32       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
	ParentID    *int32      `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.DueAt,
		arg.ParentID,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.ParentID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, name, description, due_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, due_at
`

type CreateTaskParams struct {
	ProjectID   *int32      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
}

type CreateTaskRow struct {
	ID          int32       `db:"id" json:"id"`
	ProjectID   *int32      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	DueAt       pgtype.Date `db:"due_at" json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.DueAt,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DueAt,
	)
	return i, err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (task_id, started_at, finished_at, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, started_at, finished_at, comment
`

type CreateTimeEntryParams struct {
	TaskID     int32            `db:"task_id" json:"task_id"`
	StartedAt  pgtype.Timestamp `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamp `db:"finished_at" json:"finished_at"`
	Comment    *string          `db:"comment" json:"comment"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.TaskID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Comment,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Comment,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (task_id, name)
VALUES ($1, $2)
RETURNING id, task_id, name
`

type CreateTodoParams struct {
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
}

type CreateTodoRow struct {
	ID     int32  `db:"id" json:"id"`
	TaskID int32  `db:"task_id" json:"task_id"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (CreateTodoRow, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.TaskID, arg.Name)
	var i CreateTodoRow
	err := row.Scan(&i.ID, &i.TaskID, &i.Name)
	return i, err
}

const finishProject = `-- name: FinishProject :one
UPDATE projects SET finished_at = $2
WHERE id = $1
RETURNING id, parent_id, name, description, due_at, started_at, finished_at
`

type FinishProjectParams struct {
	ID         int32            `db:"id" json:"id"`
	FinishedAt pgtype.Timestamp `db:"finished_at" json:"finished_at"`
}

func (q *Queries) FinishProject(ctx context.Context, arg FinishProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, finishProject, arg.ID, arg.FinishedAt)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishTask = `-- name: FinishTask :one
UPDATE tasks SET finished_at = $2
WHERE id = $1
RETURNING id, project_id, name, description, due_at, started_at, finished_at
`

type FinishTaskParams struct {
	ID         int32            `db:"id" json:"id"`
	FinishedAt pgtype.Timestamp `db:"finished_at" json:"finished_at"`
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, finishTask, arg.ID, arg.FinishedAt)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.DueAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishTimeEntry = `-- name: FinishTimeEntry :one
UPDATE time_entries SET finished_at = $2
WHERE id = $1
RETURNING id, task_id, started_at, finished_at, comment
`

type FinishTimeEntryParams struct {
	ID         int32            `db:"id" json:"id"`
	FinishedAt pgtype.Timestamp `db:"finished_at" json:"finished_at"`
}

func (q *Queries) FinishTimeEntry(ctx context.Context, arg FinishTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, finishTimeEntry, arg.ID, arg.FinishedAt)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Comment,
	)
	return i, err
}

const getActiveProjects = `-- name: GetActiveProjects :many
SELECT id, parent_id, name
FROM projects
WHERE started_at IS NOT NULL AND finished_at IS NULL
ORDER BY name
`

type GetActiveProjectsRow struct {
	ID       int32  `db:"id" json:"id"`
	ParentID *int32 `db:"parent_id" json:"parent_id"`
	Name     string `db:"name" json:"name"`
}

func (q *Queries) GetActiveProjects(ctx context.Context) ([]GetActiveProjectsRow, error) {
	rows, err := q.db.Query(ctx, getActiveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveProjectsRow{}
	for rows.Next() {
		var i GetActiveProjectsRow
		if err := rows.Scan(&i.ID, &i.ParentID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectWithDescendants = `-- name: GetProjectWithDescendants :many
WITH RECURSIVE project_tree AS (
    SELECT p.id, p.parent_id, p.name, p.description, p.due_at, p.started_at, p.finished_at, 0 AS depth
    FROM projects p WHERE p.id = $1
    UNION ALL
    SELECT c.id, c.parent_id, c.name, c.description, c.due_at, c.started_at, c.finished_at, pt.depth + 1
    FROM projects c
    JOIN project_tree pt ON c.parent_id = pt.id
)
SELECT id, parent_id, name, description, due_at, started_at, finished_at, depth
FROM project_tree
ORDER BY depth, name
`

type GetProjectWithDescendantsRow struct {
	ID          int32            `db:"id" json:"id"`
	ParentID    *int32           `db:"parent_id" json:"parent_id"`
	Name        string           `db:"name" json:"name"`
	Description *string          `db:"description" json:"description"`
	DueAt       pgtype.Date      `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamp `db:"finished_at" json:"finished_at"`
	Depth       int32            `db:"depth" json:"depth"`
}

func (q *Queries) GetProjectWithDescendants(ctx context.Context, id int32) ([]GetProjectWithDescendantsRow, error) {
	rows, err := q.db.Query(ctx, getProjectWithDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectWithDescendantsRow{}
	for rows.Next() {
		var i GetProjectWithDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootProjects = `-- name: GetRootProjects :many
SELECT id, name, description, due_at, parent_id, started_at
FROM projects
WHERE parent_id IS NULL AND finished_at IS NULL
ORDER BY name
`

type GetRootProjectsRow struct {
	ID          int32            `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description *string          `db:"description" json:"description"`
	DueAt       pgtype.Date      `db:"due_at" json:"due_at"`
	ParentID    *int32           `db:"parent_id" json:"parent_id"`
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
}

func (q *Queries) GetRootProjects(ctx context.Context) ([]GetRootProjectsRow, error) {
	rows, err := q.db.Query(ctx, getRootProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRootProjectsRow{}
	for rows.Next() {
		var i GetRootProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.ParentID,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByProjectIDs = `-- name: GetTasksByProjectIDs :many
WITH task_times AS (
    SELECT
        t.id, t.project_id, t.name, t.description, t.due_at, t.started_at, t.finished_at,
        COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent
    FROM tasks t
    LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
    WHERE t.project_id = ANY($1::int[])
    GROUP BY t.id
)
SELECT
    tt.id, tt.project_id, tt.name, tt.description, tt.due_at, tt.started_at, tt.finished_at,
    tt.time_spent,
    td.id AS todo_id, td.name AS todo_name
FROM task_times tt
LEFT JOIN todos td ON td.task_id = tt.id
ORDER BY tt.finished_at NULLS FIRST, tt.name, todo_id
`

type GetTasksByProjectIDsRow struct {
	ID          int32            `db:"id" json:"id"`
	ProjectID   *int32           `db:"project_id" json:"project_id"`
	Name        string           `db:"name" json:"name"`
	Description *string          `db:"description" json:"description"`
	DueAt       pgtype.Date      `db:"due_at" json:"due_at"`
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
	FinishedAt  pgtype.Timestamp `db:"finished_at" json:"finished_at"`
	TimeSpent   int64            `db:"time_spent" json:"time_spent"`
	TodoID      *int32           `db:"todo_id" json:"todo_id"`
	TodoName    *string          `db:"todo_name" json:"todo_name"`
}

func (q *Queries) GetTasksByProjectIDs(ctx context.Context, projectIds []int32) ([]GetTasksByProjectIDsRow, error) {
	rows, err := q.db.Query(ctx, getTasksByProjectIDs, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByProjectIDsRow{}
	for rows.Next() {
		var i GetTasksByProjectIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TimeSpent,
			&i.TodoID,
			&i.TodoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeEntriesByTaskID = `-- name: GetTimeEntriesByTaskID :many
WITH task_info AS (
    SELECT t.id, t.project_id, t.name, t.description, t.due_at, t.started_at, t.finished_at,
        COALESCE(SUM(EXTRACT(EPOCH FROM (te.finished_at - te.started_at)))::bigint, 0)::bigint AS time_spent
    FROM tasks t
    LEFT JOIN time_entries te ON te.task_id = t.id AND te.finished_at IS NOT NULL
    WHERE t.id = $1
    GROUP BY t.id
)
SELECT
    ti.id AS task_id, ti.project_id, ti.name, ti.description, ti.due_at,
    ti.started_at AS task_started_at, ti.finished_at AS task_finished_at, ti.time_spent,
    te.id AS time_entry_id, te.started_at AS entry_started_at, te.finished_at AS entry_finished_at, te.comment
FROM task_info ti
LEFT JOIN time_entries te ON te.task_id = ti.id
ORDER BY te.started_at
`

type GetTimeEntriesByTaskIDRow struct {
	TaskID          int32            `db:"task_id" json:"task_id"`
	ProjectID       *int32           `db:"project_id" json:"project_id"`
	Name            string           `db:"name" json:"name"`
	Description     *string          `db:"description" json:"description"`
	DueAt           pgtype.Date      `db:"due_at" json:"due_at"`
	TaskStartedAt   pgtype.Timestamp `db:"task_started_at" json:"task_started_at"`
	TaskFinishedAt  pgtype.Timestamp `db:"task_finished_at" json:"task_finished_at"`
	TimeSpent       int64            `db:"time_spent" json:"time_spent"`
	TimeEntryID     *int32           `db:"time_entry_id" json:"time_entry_id"`
	EntryStartedAt  pgtype.Timestamp `db:"entry_started_at" json:"entry_started_at"`
	EntryFinishedAt pgtype.Timestamp `db:"entry_finished_at" json:"entry_finished_at"`
	Comment         *string          `db:"comment" json:"comment"`
}

func (q *Queries) GetTimeEntriesByTaskID(ctx context.Context, id int32) ([]GetTimeEntriesByTaskIDRow, error) {
	rows, err := q.db.Query(ctx, getTimeEntriesByTaskID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeEntriesByTaskIDRow{}
	for rows.Next() {
		var i GetTimeEntriesByTaskIDRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.DueAt,
			&i.TaskStartedAt,
			&i.TaskFinishedAt,
			&i.TimeSpent,
			&i.TimeEntryID,
			&i.EntryStartedAt,
			&i.EntryFinishedAt,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnfinishedTasks = `-- name: GetUnfinishedTasks :many
SELECT id, project_id, name, started_at
FROM tasks
WHERE finished_at IS NULL
ORDER BY name
`

type GetUnfinishedTasksRow struct {
	ID        int32            `db:"id" json:"id"`
	ProjectID *int32           `db:"project_id" json:"project_id"`
	Name      string           `db:"name" json:"name"`
	StartedAt pgtype.Timestamp `db:"started_at" json:"started_at"`
}

func (q *Queries) GetUnfinishedTasks(ctx context.Context) ([]GetUnfinishedTasksRow, error) {
	rows, err := q.db.Query(ctx, getUnfinishedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnfinishedTasksRow{}
	for rows.Next() {
		var i GetUnfinishedTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
