// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	rutas "gv-api/internal/rutas"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) Create(ctx context.Context, req rutas.CreateMarkRequest) (rutas.ConcelloMark, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 rutas.ConcelloMark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rutas.CreateMarkRequest) (rutas.ConcelloMark, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rutas.CreateMarkRequest) rutas.ConcelloMark); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(rutas.ConcelloMark)
	}

	if rf, ok := ret.Get(1).(func(context.Context, rutas.CreateMarkRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req rutas.CreateMarkRequest
func (_e *MockServiceInterface_Expecter) Create(ctx interface{}, req interface{}) *MockServiceInterface_Create_Call {
	return &MockServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockServiceInterface_Create_Call) Run(run func(ctx context.Context, req rutas.CreateMarkRequest)) *MockServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rutas.CreateMarkRequest))
	})
	return _c
}

func (_c *MockServiceInterface_Create_Call) Return(_a0 rutas.ConcelloMark, _a1 error) *MockServiceInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Create_Call) RunAndReturn(run func(context.Context, rutas.CreateMarkRequest) (rutas.ConcelloMark, error)) *MockServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockServiceInterface) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockServiceInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockServiceInterface_Delete_Call {
	return &MockServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServiceInterface_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockServiceInterface_Delete_Call) Return(_a0 error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockServiceInterface) Get(ctx context.Context, id int32) (rutas.ConcelloMark, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 rutas.ConcelloMark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (rutas.ConcelloMark, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) rutas.ConcelloMark); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(rutas.ConcelloMark)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockServiceInterface_Expecter) Get(ctx interface{}, id interface{}) *MockServiceInterface_Get_Call {
	return &MockServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockServiceInterface_Get_Call) Run(run func(ctx context.Context, id int32)) *MockServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockServiceInterface_Get_Call) Return(_a0 rutas.ConcelloMark, _a1 error) *MockServiceInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Get_Call) RunAndReturn(run func(context.Context, int32) (rutas.ConcelloMark, error)) *MockServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockServiceInterface) List(ctx context.Context) ([]rutas.ConcelloMark, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []rutas.ConcelloMark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]rutas.ConcelloMark, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []rutas.ConcelloMark); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rutas.ConcelloMark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) List(ctx interface{}) *MockServiceInterface_List_Call {
	return &MockServiceInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockServiceInterface_List_Call) Run(run func(ctx context.Context)) *MockServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_List_Call) Return(_a0 []rutas.ConcelloMark, _a1 error) *MockServiceInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_List_Call) RunAndReturn(run func(context.Context) ([]rutas.ConcelloMark, error)) *MockServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockServiceInterface) Update(ctx context.Context, req rutas.UpdateMarkRequest) (rutas.ConcelloMark, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 rutas.ConcelloMark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rutas.UpdateMarkRequest) (rutas.ConcelloMark, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rutas.UpdateMarkRequest) rutas.ConcelloMark); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(rutas.ConcelloMark)
	}

	if rf, ok := ret.Get(1).(func(context.Context, rutas.UpdateMarkRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req rutas.UpdateMarkRequest
func (_e *MockServiceInterface_Expecter) Update(ctx interface{}, req interface{}) *MockServiceInterface_Update_Call {
	return &MockServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockServiceInterface_Update_Call) Run(run func(ctx context.Context, req rutas.UpdateMarkRequest)) *MockServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rutas.UpdateMarkRequest))
	})
	return _c
}

func (_c *MockServiceInterface_Update_Call) Return(_a0 rutas.ConcelloMark, _a1 error) *MockServiceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_Update_Call) RunAndReturn(run func(context.Context, rutas.UpdateMarkRequest) (rutas.ConcelloMark, error)) *MockServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
